const docEsc = valor => { const e=document.createElement("div");e.textContent=valor??"";return e.innerHTML; };
let checklistsDoc=[],itensDoc=[],checklistSelecionado=0;
const checklistModalDoc=document.getElementById("checklistModal")?new bootstrap.Modal(document.getElementById("checklistModal")):null;
const itemModalDoc=document.getElementById("itemModal")?new bootstrap.Modal(document.getElementById("itemModal")):null;

async function docApi(url,opcoes={}){const r=await fetch(url,{cache:"no-store",...opcoes});const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.mensagem||"Não foi possível processar a solicitação.");return d;}
async function carregarChecklists(){
 const d=await docApi("documentacao_api.jsp?acao=checklists");checklistsDoc=d.checklists;
 document.getElementById("checklistsBody").innerHTML=checklistsDoc.length?checklistsDoc.map(x=>`<tr class="${x.id===checklistSelecionado?'doc-row-selected':''}" data-checklist-linha="${x.id}"><td><strong>${docEsc(x.nome)}</strong></td><td><span class="badge-tag" style="${window.GruposCatalogo?GruposCatalogo.estilo(x.classe):''}">${docEsc(x.grupo)}</span></td><td><span class="badge ${x.status==='ATIVO'?'text-bg-success':'text-bg-secondary'}">${x.status==='ATIVO'?'Ativo':'Inativo'}</span></td><td>${x.itens}</td><td>${x.membros}</td><td class="text-end"><button class="btn btn-sm btn-outline-primary" onclick="event.stopPropagation();location.href='documentacao-acompanhamento.jsp?id=${x.id}'"><i class="bi bi-list-check"></i> Acompanhar</button>${window.documentacaoPodeEditar?` <button class="btn btn-sm btn-outline-secondary" onclick="event.stopPropagation();editarChecklist(${x.id})"><i class="bi bi-pencil"></i></button>`:""}</td></tr>`).join(""):'<tr><td colspan="6" class="text-center text-muted py-4">Nenhum checklist cadastrado.</td></tr>';
 document.querySelectorAll("[data-checklist-linha]").forEach(l=>l.addEventListener("click",()=>selecionarChecklist(Number(l.dataset.checklistLinha))));
}
async function selecionarChecklist(id){checklistSelecionado=id;const x=checklistsDoc.find(c=>c.id===id);document.getElementById("itensTitulo").textContent=x?x.nome:"Itens do checklist";document.getElementById("itensSubtitulo").textContent=x?`${x.grupo} · ${x.status==='ATIVO'?'Ativo':'Inativo'}`:"";document.getElementById("novoItemBtn")?.removeAttribute("disabled");await carregarItens();await carregarChecklists();}
async function carregarItens(){const d=await docApi(`documentacao_api.jsp?acao=itens&checklist=${checklistSelecionado}`);itensDoc=d.itens;const col=window.documentacaoPodeEditar?5:4;document.getElementById("itensBody").innerHTML=itensDoc.length?itensDoc.map(x=>`<tr><td>${x.ordem}</td><td><strong>${docEsc(x.descricao)}</strong>${x.permiteUpload?`<small class="d-block text-muted"><i class="bi bi-upload"></i> Upload · Prefixo ${docEsc(x.prefixo)}</small>`:''}</td><td><span class="${x.exibirMembro?'doc-visible':'doc-hidden'}"><i class="bi ${x.exibirMembro?'bi-eye-fill':'bi-eye-slash'}"></i> ${x.exibirMembro?'Sim':'Não'}</span></td><td>${x.status==='ATIVO'?'Ativo':'Inativo'}</td>${window.documentacaoPodeEditar?`<td class="text-end"><button class="btn btn-sm btn-outline-secondary" onclick="editarItem(${x.id})"><i class="bi bi-pencil"></i></button></td>`:""}</tr>`).join(""):`<tr><td colspan="${col}" class="text-center text-muted py-4">Nenhum item cadastrado.</td></tr>`;}
function novoChecklist(){document.getElementById("checklistId").value="";document.getElementById("checklistNome").value="";const grupo=document.getElementById("checklistClasse");grupo.value=grupo.options[0]?.value||"";document.getElementById("checklistStatus").value="ATIVO";checklistModalDoc.show();}
function editarChecklist(id){const x=checklistsDoc.find(c=>c.id===id);if(!x)return;document.getElementById("checklistId").value=x.id;document.getElementById("checklistNome").value=x.nome;document.getElementById("checklistClasse").value=x.classe;document.getElementById("checklistStatus").value=x.status;checklistModalDoc.show();}
async function salvarChecklist(){const body=new URLSearchParams({id:document.getElementById("checklistId").value,nome:document.getElementById("checklistNome").value.trim(),classe:document.getElementById("checklistClasse").value,status:document.getElementById("checklistStatus").value});if(!body.get("nome")){alert("Informe o nome do checklist.");return;}const d=await docApi("documentacao_api.jsp?acao=salvarChecklist",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded;charset=UTF-8"},body});checklistModalDoc.hide();checklistSelecionado=d.id;await carregarChecklists();await selecionarChecklist(d.id);}
function atualizarPrefixoItem(){const ativo=document.getElementById("itemPermiteUpload").checked;document.getElementById("itemPrefixoArea").classList.toggle("d-none",!ativo);document.getElementById("itemPrefixo").required=ativo;}
function novoItem(){document.getElementById("itemId").value="";document.getElementById("itemDescricao").value="";document.getElementById("itemOrdem").value=itensDoc.length+1;document.getElementById("itemStatus").value="ATIVO";document.getElementById("itemExibir").checked=true;document.getElementById("itemPermiteUpload").checked=false;document.getElementById("itemPrefixo").value="";atualizarPrefixoItem();itemModalDoc.show();}
function editarItem(id){const x=itensDoc.find(i=>i.id===id);if(!x)return;document.getElementById("itemId").value=x.id;document.getElementById("itemDescricao").value=x.descricao;document.getElementById("itemOrdem").value=x.ordem;document.getElementById("itemStatus").value=x.status;document.getElementById("itemExibir").checked=x.exibirMembro;document.getElementById("itemPermiteUpload").checked=!!x.permiteUpload;document.getElementById("itemPrefixo").value=x.prefixo||"";atualizarPrefixoItem();itemModalDoc.show();}
async function salvarItem(){const upload=document.getElementById("itemPermiteUpload").checked,prefixo=document.getElementById("itemPrefixo").value.trim();const body=new URLSearchParams({id:document.getElementById("itemId").value,checklist:checklistSelecionado,descricao:document.getElementById("itemDescricao").value.trim(),ordem:document.getElementById("itemOrdem").value,status:document.getElementById("itemStatus").value,exibirMembro:document.getElementById("itemExibir").checked?1:0,permiteUpload:upload?1:0,prefixo});if(!body.get("descricao")||(upload&&!prefixo)){alert("Informe a descrição e o prefixo do arquivo.");return;}await docApi("documentacao_api.jsp?acao=salvarItem",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded;charset=UTF-8"},body});itemModalDoc.hide();await carregarItens();await carregarChecklists();}
async function enviarDocumento(item,input){const arquivo=input.files?.[0];if(!arquivo)return;if(arquivo.size>3*1024*1024){alert("O arquivo deve ter no máximo 3 MB.");input.value="";return;}try{await docApi(`uploadDocumentoMembro.jsp?item=${encodeURIComponent(item)}`,{method:"POST",headers:{"Content-Type":arquivo.type||"application/octet-stream","X-File-Name":encodeURIComponent(arquivo.name)},body:arquivo});await carregarMeusDocumentos();}catch(e){alert(e.message);input.value="";}}
async function carregarMeusDocumentos(){const d=await docApi("documentacao_api.jsp?acao=meus");document.getElementById("meusDocsTotal").textContent=d.total;document.getElementById("meusDocsConcluidos").textContent=d.concluidos;document.getElementById("meusDocsPendentes").textContent=d.pendentes;const agrupados=Object.groupBy?Object.groupBy(d.documentos,x=>x.checklist):d.documentos.reduce((a,x)=>{(a[x.checklist]??=[]).push(x);return a;},{});document.getElementById("meusDocumentosLista").innerHTML=d.documentos.length?Object.entries(agrupados).map(([nome,itens])=>`<div class="mb-4"><h5>${docEsc(nome)}</h5><div class="list-group">${itens.map(x=>`<div class="list-group-item d-flex justify-content-between align-items-center gap-3 flex-wrap"><div><strong>${docEsc(x.descricao)}</strong>${x.conclusao?`<small class="d-block text-muted">Entregue em ${docEsc(x.conclusao)}</small>`:""}${x.arquivo?`<a class="d-block small" href="baixarDocumentoMembro.jsp?item=${x.itemId}" target="_blank"><i class="bi bi-paperclip"></i> ${docEsc(x.arquivo)}</a>`:""}</div><div class="d-flex align-items-center gap-2">${x.permiteUpload&&x.disponivelEnvio?`<label class="btn btn-sm btn-outline-primary mb-0"><i class="bi bi-upload"></i> ${x.arquivo?'Substituir':'Enviar arquivo'}<input type="file" class="d-none" accept="application/pdf,image/*" onchange="enviarDocumento(${x.itemId},this)"></label>`:''}<span class="badge rounded-pill ${x.status==='CONCLUIDO'?'text-bg-success':'text-bg-warning'}">${x.status==='CONCLUIDO'?'Entregue':'Pendente'}</span></div></div>`).join("")}</div></div>`).join(""):'<div class="text-center text-muted py-5"><i class="bi bi-folder-check fs-1 d-block mb-2"></i>Nenhum documento solicitado para o seu grupo.</div>';}
document.getElementById("itemPermiteUpload")?.addEventListener("change",atualizarPrefixoItem);
(async()=>{try{if(window.documentacaoGestao)await carregarChecklists();else await carregarMeusDocumentos();}catch(e){console.error(e);alert(e.message);}})();
