let finDados=[],finContas=[],finGrupos=[];const moeda=v=>Number(v).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});const finModal=new bootstrap.Modal("#finModal"),planoModal=new bootstrap.Modal("#planoModal");
async function apiFin(acao,opt){const r=await fetch(`financeiro_api.jsp?acao=${acao}`,opt),d=await r.json();if(!r.ok||!d.ok)throw new Error(d.mensagem||"Erro no financeiro.");return d}
async function iniciarFinanceiro(){const hoje=new Date();for(let m=1;m<=12;m++)finMes.add(new Option(new Intl.DateTimeFormat("pt-BR",{month:"long"}).format(new Date(2026,m-1,1)),m));finMes.value=hoje.getMonth()+1;for(let a=hoje.getFullYear()+1;a>=hoje.getFullYear()-5;a--)finAno.add(new Option(a,a));finAno.value=hoje.getFullYear();const [c,g]=await Promise.all([apiFin("contas"),apiFin("grupos")]);finContas=c.contas;finGrupos=g.grupos;if(window.finAdm)finGrupos.forEach(x=>finGrupo.add(new Option(x.nome,x.id)));lanGrupo.innerHTML=finGrupos.filter(x=>window.finAdm||x.id==window.finGrupoSessao).map(x=>`<option value="${x.id}">${x.nome}</option>`).join("");atualizarContas();lanTipo.onchange=atualizarContas;await carregarFinanceiro()}
function atualizarContas(){const tipo=lanTipo.value;lanConta.innerHTML=finContas.filter(x=>x.tipo===tipo&&x.status==="ATIVA").map(x=>`<option value="${x.id}">${x.codigo} — ${x.nome}</option>`).join("")}
async function carregarFinanceiro(){const d=await apiFin(`listar&mes=${finMes.value}&ano=${finAno.value}&grupo=${finGrupo.value}`);finDados=d.lancamentos;renderFin()}
function renderFin(){const sit=finSituacao.value,lista=finDados.filter(x=>!sit||x.situacao===sit);let ent=0,sai=0;finLinhas.innerHTML=lista.map(x=>{if(x.situacao==="REALIZADO")(x.tipo==="ENTRADA"?ent+=x.valor:sai+=x.valor);const log=`<button class="btn btn-sm btn-outline-primary" onclick="verLog(${x.id})"><i class="bi bi-clock-history"></i></button> `;const ed=`<button class="btn btn-sm btn-outline-secondary" onclick="editarLancamento(${x.id})"><i class="bi bi-pencil"></i></button> `;const a=x.origem==="CONTRIBUICOES"?`<button class="btn btn-sm btn-outline-secondary" onclick="verContribuicoes(${x.id})">Detalhes</button>`:x.situacao==="PREVISTO"?log+ed+`<button class="btn btn-sm btn-outline-success" onclick="realizar(${x.id},${x.grupoId},${x.valor})">Realizar</button> <button class="btn btn-sm btn-outline-danger" onclick="excluir(${x.id},${x.grupoId})">Excluir</button>`:x.situacao==="REALIZADO"?log+ed+`<button class="btn btn-sm btn-outline-danger" onclick="cancelar(${x.id},${x.grupoId})">Cancelar</button>`:log;return `<tr><td>${x.competencia.slice(0,7).split('-').reverse().join('/')}</td><td>${x.grupo}</td><td>${x.conta}</td><td>${x.descricao}${x.origem==='CONTRIBUICOES'?'<div class="fin-auto">Consolidado automaticamente</div>':''}</td><td><span class="badge fin-${x.situacao.toLowerCase()}">${x.situacao}</span></td><td class="text-end ${x.tipo==='ENTRADA'?'text-success':'text-danger'}">${x.tipo==='ENTRADA'?'+':'−'} ${moeda(x.valor)}</td><td class="fin-actions">${a}</td></tr>`}).join("")||'<tr><td colspan="7" class="text-center text-muted py-4">Nenhum lançamento.</td></tr>';finEntradas.textContent=moeda(ent);finSaidas.textContent=moeda(sai);finSaldo.textContent=moeda(ent-sai)}
function abrirLancamento(){lanId.value="";lanCompetencia.value=`${finAno.value}-${String(finMes.value).padStart(2,'0')}`;lanPrevista.value=new Date().toISOString().slice(0,10);lanDescricao.value="";lanValor.value="";finModal.show()}
function editarLancamento(id){const x=finDados.find(v=>v.id===id);if(!x)return;lanId.value=x.id;lanGrupo.value=x.grupoId;lanTipo.value=x.tipo;atualizarContas();const codigo=x.conta.split(' ')[0];const conta=finContas.find(c=>c.codigo===codigo);if(conta)lanConta.value=conta.id;lanCompetencia.value=x.competencia.slice(0,7);lanPrevista.value=x.prevista||x.realizada;lanDescricao.value=x.descricao;lanValor.value=x.valor;finModal.show()}
async function salvarLancamento(){const body=new URLSearchParams({id:lanId.value,grupo:lanGrupo.value,conta:lanConta.value,tipo:lanTipo.value,descricao:lanDescricao.value,competencia:lanCompetencia.value,prevista:lanPrevista.value,valor:lanValor.value});await apiFin("salvar",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body});finModal.hide();carregarFinanceiro()}
async function realizar(id,grupo,valor){const novo=prompt("Valor efetivamente realizado:",valor);if(novo===null)return;const data=prompt("Data da realização (AAAA-MM-DD):",new Date().toISOString().slice(0,10));if(!data)return;await apiFin("realizar",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:new URLSearchParams({id,grupo,valor:novo,data})});carregarFinanceiro()}
async function cancelar(id,grupo){const motivo=prompt("Motivo obrigatório do cancelamento:");if(!motivo)return;await apiFin("cancelar",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:new URLSearchParams({id,grupo,motivo})});carregarFinanceiro()}
async function excluir(id,grupo){if(!confirm("Excluir este lançamento previsto?"))return;await apiFin("excluir",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:new URLSearchParams({id,grupo})});carregarFinanceiro()}
function abrirPlano(){limparConta();planoLinhas.innerHTML=finContas.map(x=>`<tr><td>${x.codigo}</td><td>${x.nome}</td><td>${x.tipo}</td><td>${x.status}</td><td><button class="btn btn-sm btn-outline-secondary" onclick="editarConta(${x.id})"><i class="bi bi-pencil"></i></button></td></tr>`).join("");planoModal.show()}
function limparConta(){contaId.value="";contaCodigo.value="";contaNome.value="";contaTipo.value="ENTRADA";contaStatus.value="ATIVA"}
function editarConta(id){const x=finContas.find(c=>c.id===id);contaId.value=x.id;contaCodigo.value=x.codigo;contaNome.value=x.nome;contaTipo.value=x.tipo;contaStatus.value=x.status}
async function salvarConta(){await apiFin("salvarConta",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:new URLSearchParams({id:contaId.value,codigo:contaCodigo.value,nome:contaNome.value,tipo:contaTipo.value,status:contaStatus.value})});finContas=(await apiFin("contas")).contas;abrirPlano();atualizarContas()}
async function verContribuicoes(id){const d=await apiFin(`detalhesContribuicoes&id=${id}`);detalheFinTitulo.textContent="Detalhes das contribuições";detalheFinCorpo.innerHTML=`<div class="table-responsive"><table class="table"><thead><tr><th>Membro</th><th>Pagamento</th><th>Registrado por</th><th class="text-end">Valor</th></tr></thead><tbody>${d.itens.map(x=>`<tr><td>${x.membro}</td><td>${x.data||'—'}</td><td>${x.usuario||'—'}</td><td class="text-end">${moeda(x.valor)}</td></tr>`).join('')}</tbody></table></div>`;bootstrap.Modal.getOrCreateInstance("#detalheFinModal").show()}
async function verLog(id){const d=await apiFin(`log&id=${id}`);detalheFinTitulo.textContent="Histórico de modificações";detalheFinCorpo.innerHTML=d.logs.length?d.logs.map(x=>`<div class="border-bottom py-3"><div class="d-flex justify-content-between"><strong>${x.acao}</strong><span class="text-muted">${x.data}</span></div><div>${x.usuario||'Usuário não identificado'}</div>${x.motivo?`<div><strong>Motivo:</strong> ${x.motivo}</div>`:''}<details class="mt-2"><summary>Dados alterados</summary><div class="small mt-2"><strong>Antes:</strong> ${x.antes||'—'}<br><strong>Depois:</strong> ${x.depois||'—'}</div></details></div>`).join(''):'<p class="text-muted">Nenhum registro de alteração.</p>';bootstrap.Modal.getOrCreateInstance("#detalheFinModal").show()}
finSituacao.onchange=renderFin;iniciarFinanceiro().catch(e=>{console.error(e);alert(e.message)});
