const admEsc=valor=>{const e=document.createElement("div");e.textContent=valor??"";return e.innerHTML;};
const nomesGrupos=new Proxy({}, {get:(_, id)=>window.GruposCatalogo?GruposCatalogo.nome(id):`Grupo ${id}`});
function popularGruposPrograma(){
 const container=document.getElementById("programaGrupos");if(!container||!window.GruposCatalogo)return;
 container.innerHTML=GruposCatalogo.listar({modulo:"formacao",operacionais:true}).map(g=>`<label class="group-check"><input type="checkbox" value="${Number(g.id)}" data-programa-grupo> ${admEsc(g.plural)}</label>`).join("");
}
if(window.GruposCatalogo)GruposCatalogo.carregar().then(popularGruposPrograma);
let programasAdmin=[],disciplinasAdmin=[],programaSelecionado=0,modalPrograma,modalDisciplina;
async function carregarProgramas(){
 const r=await fetch("formacao_api.jsp?acao=adminProgramas",{cache:"no-store"}),d=await r.json();if(!r.ok||!d.ok)throw new Error(d.mensagem||"Erro ao carregar programas.");programasAdmin=d.programas;
 programasAdminBody.innerHTML=programasAdmin.map(p=>`<tr class="admin-program-row ${p.id===programaSelecionado?"table-active":""}" onclick="selecionarPrograma(${p.id})"><td><strong>${admEsc(p.nome)}</strong></td><td>${p.grupos.map(g=>nomesGrupos[g]).join(", ")||"-"}</td><td>${admEsc(p.dataInicio)||"-"}</td><td><span class="badge ${p.status==="ATIVO"?"text-bg-success":"text-bg-secondary"}">${p.status==="ATIVO"?"Ativo":"Inativo"}</span></td><td>${p.totalDisciplinas}</td><td><button class="btn btn-sm btn-outline-secondary" onclick="event.stopPropagation();editarPrograma(${p.id})"><i class="bi bi-pencil"></i></button></td></tr>`).join("")||'<tr><td colspan="6">Nenhum programa cadastrado.</td></tr>';
}
async function selecionarPrograma(id){programaSelecionado=id;await carregarProgramas();const p=programasAdmin.find(x=>x.id===id);disciplinasAdminTitulo.textContent=`Disciplinas — ${p.nome}`;novaDisciplinaBtn.disabled=false;await carregarDisciplinas();}
async function carregarDisciplinas(){const r=await fetch(`formacao_api.jsp?acao=adminDisciplinas&programa=${programaSelecionado}`,{cache:"no-store"}),d=await r.json();if(!r.ok||!d.ok)throw new Error(d.mensagem);disciplinasAdmin=d.disciplinas;disciplinasAdminBody.innerHTML=disciplinasAdmin.map(i=>`<tr><td>${i.ordem}</td><td>${admEsc(i.bloco)||"-"}</td><td><strong>${admEsc(i.descricao)}</strong></td><td>${i.tipo==="OBRIGATORIA"?"Obrigatória":"Opcional"}</td><td>${i.cargaHoraria?`${i.cargaHoraria}h`:"-"}</td><td><button class="btn btn-sm btn-outline-secondary" onclick="editarDisciplina(${i.id})"><i class="bi bi-pencil"></i></button></td></tr>`).join("")||'<tr><td colspan="6" class="text-muted">Nenhuma disciplina cadastrada.</td></tr>';}
function novoPrograma(){programaId.value="";programaNome.value="";programaData.value="";programaStatus.value="ATIVO";document.querySelectorAll("[data-programa-grupo]").forEach(c=>c.checked=false);modalPrograma.show();}
function editarPrograma(id){const p=programasAdmin.find(x=>x.id===id);programaId.value=p.id;programaNome.value=p.nome;programaData.value=p.dataInicio;programaStatus.value=p.status;document.querySelectorAll("[data-programa-grupo]").forEach(c=>c.checked=p.grupos.includes(Number(c.value)));modalPrograma.show();}
async function salvarPrograma(){const grupos=[...document.querySelectorAll("[data-programa-grupo]:checked")].map(c=>c.value).join(","),r=await fetch("formacao_api.jsp?acao=salvarPrograma",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded;charset=UTF-8"},body:new URLSearchParams({id:programaId.value,nome:programaNome.value,dataInicio:programaData.value,status:programaStatus.value,grupos})}),d=await r.json();if(!r.ok||!d.ok){alert(d.mensagem||"Erro ao salvar programa.");return;}modalPrograma.hide();await carregarProgramas();}
function novaDisciplina(){disciplinaId.value="";disciplinaDescricao.value="";disciplinaBloco.value="";disciplinaCarga.value="";disciplinaTipo.value="OBRIGATORIA";disciplinaOrdem.value="0";modalDisciplina.show();}
function editarDisciplina(id){const i=disciplinasAdmin.find(x=>x.id===id);disciplinaId.value=i.id;disciplinaDescricao.value=i.descricao;disciplinaBloco.value=i.bloco;disciplinaCarga.value=i.cargaHoraria||"";disciplinaTipo.value=i.tipo;disciplinaOrdem.value=i.ordem;modalDisciplina.show();}
async function salvarDisciplina(){const r=await fetch("formacao_api.jsp?acao=salvarDisciplina",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded;charset=UTF-8"},body:new URLSearchParams({id:disciplinaId.value,programa:programaSelecionado,descricao:disciplinaDescricao.value,bloco:disciplinaBloco.value,cargaHoraria:disciplinaCarga.value,tipo:disciplinaTipo.value,ordem:disciplinaOrdem.value})}),d=await r.json();if(!r.ok||!d.ok){alert(d.mensagem||"Erro ao salvar disciplina.");return;}modalDisciplina.hide();await carregarDisciplinas();await carregarProgramas();}
document.addEventListener("DOMContentLoaded",()=>{modalPrograma=new bootstrap.Modal(document.getElementById("programaModal"));modalDisciplina=new bootstrap.Modal(document.getElementById("disciplinaModal"));carregarProgramas().catch(e=>programasAdminBody.innerHTML=`<tr><td colspan="6" class="text-danger">${admEsc(e.message)}</td></tr>`);});
