<%@ page import="java.sql.*,java.time.Year,java.time.LocalDate,java.time.format.DateTimeFormatter,java.util.TreeSet,java.util.Collections,java.util.Locale" %>
<%@ page contentType="application/json; charset=UTF-8" pageEncoding="UTF-8" %>
<%!
private String j(String s){return s==null?"":s.replace("\\","\\\\").replace("\"","\\\"").replace("\r","\\r").replace("\n","\\n").replace("\t","\\t");}
private String grupo(int c){return cad.grupos.GrupoCatalogo.plural(c);}
private int inteiro(String v)throws Exception{return Integer.parseInt(v==null?"":v);}
%>
<%
response.setHeader("Cache-Control","no-store");
String perfil=(String)session.getAttribute("usuarioPerfil");
Integer usuarioId=(Integer)session.getAttribute("usuarioId");
boolean administrador="ADM".equals(perfil);
if((!administrador&&!"EXT".equals(perfil))||usuarioId==null){response.setStatus(403);out.print("{\"ok\":false,\"mensagem\":\"Acesso não autorizado.\"}");return;}
String acao=request.getParameter("acao"); if(acao==null)acao="ciclos";
try{
 try(Connection c=cad.db.Database.getConnection()){
  if("ciclos".equals(acao)){
String sql="SELECT c.IdCiclo,c.DtCiclo,c.Classe,c.Descricao,COUNT(a.IdAvaliacao) Avaliados,(SELECT COUNT(*) FROM pessoas p WHERE p.Classe=c.Classe AND p.status=1) Total FROM ciclos_avaliacao c JOIN grupos g ON g.IdGrupo=c.Classe AND g.StatusGrupo='ATIVO' AND g.GrupoOperacional=1 AND g.ModuloAvaliacoes=1 LEFT JOIN avaliacoes_pessoa a ON a.IdCiclo=c.IdCiclo GROUP BY c.IdCiclo,c.DtCiclo,c.Classe,c.Descricao ORDER BY c.DtCiclo DESC,c.IdCiclo DESC";
   StringBuilder b=new StringBuilder("{\"ok\":true,\"ciclos\":[");boolean f=true;
   try(PreparedStatement p=c.prepareStatement(sql);ResultSet r=p.executeQuery()){while(r.next()){if(!f)b.append(',');f=false;b.append("{\"id\":").append(r.getInt(1)).append(",\"data\":\"").append(r.getDate(2)).append("\",\"dataFormatada\":\"").append(r.getDate(2).toLocalDate().format(DateTimeFormatter.ofPattern("dd/MM/yyyy"))).append("\",\"classe\":").append(r.getInt(3)).append(",\"grupo\":\"").append(j(grupo(r.getInt(3)))).append("\",\"descricao\":\"").append(j(r.getString(4))).append("\",\"avaliados\":").append(r.getInt(5)).append(",\"total\":").append(r.getInt(6)).append('}');}}
   out.print(b.append("]}"));return;
  }
  if("salvarCiclo".equals(acao)){
   if(!administrador){response.setStatus(403);out.print("{\"ok\":false,\"mensagem\":\"Perfil autorizado apenas para consulta.\"}");return;}
   if(!"POST".equalsIgnoreCase(request.getMethod())){response.setStatus(405);out.print("{\"ok\":false,\"mensagem\":\"Método não permitido.\"}");return;}
   int id=request.getParameter("id")==null||request.getParameter("id").trim().isEmpty()?0:inteiro(request.getParameter("id"));int classe=inteiro(request.getParameter("classe"));
   String data=request.getParameter("data"),descricao=request.getParameter("descricao");
if(data==null||descricao==null||descricao.trim().isEmpty()){response.setStatus(400);out.print("{\"ok\":false,\"mensagem\":\"Informe data, grupo e descrição.\"}");return;}
try(PreparedStatement valida=c.prepareStatement("SELECT 1 FROM grupos WHERE IdGrupo=? AND StatusGrupo='ATIVO' AND GrupoOperacional=1 AND ModuloAvaliacoes=1")){valida.setInt(1,classe);try(ResultSet r=valida.executeQuery()){if(!r.next()){response.setStatus(400);out.print("{\"ok\":false,\"mensagem\":\"Grupo indisponível para avaliações.\"}");return;}}}
   if(id==0){try(PreparedStatement p=c.prepareStatement("INSERT INTO ciclos_avaliacao(DtCiclo,Classe,Descricao,IdUsuarioCriacao) VALUES(?,?,?,?)")){p.setDate(1,Date.valueOf(data));p.setInt(2,classe);p.setString(3,descricao.trim());p.setInt(4,usuarioId);p.executeUpdate();}}
   else{try(PreparedStatement p=c.prepareStatement("UPDATE ciclos_avaliacao SET DtCiclo=?,Classe=?,Descricao=?,IdUsuarioAtualizacao=?,DtAtualizacao=NOW() WHERE IdCiclo=?")){p.setDate(1,Date.valueOf(data));p.setInt(2,classe);p.setString(3,descricao.trim());p.setInt(4,usuarioId);p.setInt(5,id);if(p.executeUpdate()==0)throw new SQLException("Ciclo não encontrado");}}
   out.print("{\"ok\":true}");return;
  }
  if("membros".equals(acao)){
   int ciclo=inteiro(request.getParameter("ciclo"));String nome=request.getParameter("nome"),regiao=request.getParameter("regiao"),situacao=request.getParameter("situacao");
   String sql="SELECT c.IdCiclo,c.DtCiclo,c.Classe,c.Descricao,p.IdPessoa,p.Nome,IFNULL(s.Paroquia,''),IFNULL(s.Regiao,''),IFNULL(s.IdRegiao,0),CASE WHEN a.IdAvaliacao IS NULL THEN 0 ELSE 1 END Avaliado FROM ciclos_avaliacao c JOIN pessoas p ON (p.Classe=c.Classe AND p.status=1) OR EXISTS (SELECT 1 FROM avaliacoes_pessoa ax WHERE ax.IdCiclo=c.IdCiclo AND ax.IdPessoa=p.IdPessoa) LEFT JOIN sqlPessoas s ON s.IdPessoa=p.IdPessoa LEFT JOIN avaliacoes_pessoa a ON a.IdCiclo=c.IdCiclo AND a.IdPessoa=p.IdPessoa WHERE c.IdCiclo=? AND (?='' OR p.Nome LIKE CONCAT('%',?,'%')) AND (?='' OR CAST(IFNULL(s.IdRegiao,0) AS CHAR)=?) AND (?='' OR (?='AVALIADO' AND a.IdAvaliacao IS NOT NULL) OR (?='PENDENTE' AND a.IdAvaliacao IS NULL)) ORDER BY p.Nome";
   StringBuilder b=new StringBuilder();boolean f=true;boolean achou=false;
   try(PreparedStatement p=c.prepareStatement(sql)){String sit=situacao==null?"":situacao;p.setInt(1,ciclo);p.setString(2,nome==null?"":nome.trim());p.setString(3,nome==null?"":nome.trim());p.setString(4,regiao==null?"":regiao);p.setString(5,regiao==null?"":regiao);p.setString(6,sit);p.setString(7,sit);p.setString(8,sit);try(ResultSet r=p.executeQuery()){while(r.next()){if(!achou){achou=true;b.append("{\"ok\":true,\"ciclo\":{\"id\":").append(r.getInt(1)).append(",\"data\":\"").append(r.getDate(2)).append("\",\"dataFormatada\":\"").append(r.getDate(2).toLocalDate().format(DateTimeFormatter.ofPattern("dd/MM/yyyy"))).append("\",\"classe\":").append(r.getInt(3)).append(",\"grupo\":\"").append(j(grupo(r.getInt(3)))).append("\",\"descricao\":\"").append(j(r.getString(4))).append("\"},\"membros\":[");}if(!f)b.append(',');f=false;b.append("{\"id\":").append(r.getInt(5)).append(",\"nome\":\"").append(j(r.getString(6))).append("\",\"paroquia\":\"").append(j(r.getString(7))).append("\",\"regiao\":\"").append(j(r.getString(8))).append("\",\"idRegiao\":").append(r.getInt(9)).append(",\"avaliado\":").append(r.getInt(10)==1).append('}');}}}
   if(!achou){try(PreparedStatement p=c.prepareStatement("SELECT IdCiclo,DtCiclo,Classe,Descricao FROM ciclos_avaliacao WHERE IdCiclo=?")){p.setInt(1,ciclo);try(ResultSet r=p.executeQuery()){if(!r.next()){response.setStatus(404);out.print("{\"ok\":false,\"mensagem\":\"Ciclo não encontrado.\"}");return;}b.append("{\"ok\":true,\"ciclo\":{\"id\":").append(r.getInt(1)).append(",\"data\":\"").append(r.getDate(2)).append("\",\"dataFormatada\":\"").append(r.getDate(2).toLocalDate().format(DateTimeFormatter.ofPattern("dd/MM/yyyy"))).append("\",\"classe\":").append(r.getInt(3)).append(",\"grupo\":\"").append(j(grupo(r.getInt(3)))).append("\",\"descricao\":\"").append(j(r.getString(4))).append("\"},\"membros\":[");}}}
   out.print(b.append("]}"));return;
  }
  if("regioes".equals(acao)){
   StringBuilder b=new StringBuilder("{\"ok\":true,\"regioes\":[");boolean f=true;try(PreparedStatement p=c.prepareStatement("SELECT DISTINCT IdRegiao,Regiao FROM sqlPessoas WHERE IdRegiao IS NOT NULL AND Regiao IS NOT NULL AND Regiao<>'' ORDER BY Regiao");ResultSet r=p.executeQuery()){while(r.next()){if(!f)b.append(',');f=false;b.append("{\"id\":").append(r.getInt(1)).append(",\"nome\":\"").append(j(r.getString(2))).append("\"}");}}out.print(b.append("]}"));return;
  }
  if("indicadores".equals(acao)){
   int pessoa=inteiro(request.getParameter("pessoa")),ano=inteiro(request.getParameter("ano"));
   TreeSet<Integer> anos=new TreeSet<Integer>(Collections.reverseOrder());anos.add(ano);
   try(PreparedStatement p=c.prepareStatement("SELECT YEAR(e.DtEncontro) ano FROM Encontros e JOIN participanteEncontro pe ON pe.IdEncontro=e.IdEncontro WHERE pe.IdPessoa=? UNION SELECT YEAR(l.dtVencimento) FROM lancamentos l WHERE l.idPessoa=? AND l.tipoLancamento='1.1' ORDER BY ano DESC")){p.setInt(1,pessoa);p.setInt(2,pessoa);try(ResultSet r=p.executeQuery()){while(r.next())anos.add(r.getInt(1));}}
   int classe=0;try(PreparedStatement p=c.prepareStatement("SELECT Classe FROM pessoas WHERE IdPessoa=?")){p.setInt(1,pessoa);try(ResultSet r=p.executeQuery()){if(!r.next()){response.setStatus(404);out.print("{\"ok\":false,\"mensagem\":\"Pessoa não encontrada.\"}");return;}classe=r.getInt(1);}}
   StringBuilder b=new StringBuilder("{\"ok\":true,\"ano\":").append(ano).append(",\"anos\":[");boolean first=true;for(Integer a:anos){if(!first)b.append(',');first=false;b.append(a);}b.append("],\"presencas\":[");
   int totalPresencas=0,presentes=0;first=true;
   try(PreparedStatement p=c.prepareStatement("SELECT DATE_FORMAT(e.DtEncontro,'%d/%m/%Y'),e.Descricao,CASE pe.flgPresenca WHEN 1 THEN 'Presente' WHEN 2 THEN 'Justificado' ELSE 'Faltou' END,IFNULL(pe.Justificativa,'') FROM Encontros e JOIN participanteEncontro pe ON pe.IdEncontro=e.IdEncontro WHERE pe.IdPessoa=? AND YEAR(e.DtEncontro)=? ORDER BY e.DtEncontro DESC")){p.setInt(1,pessoa);p.setInt(2,ano);try(ResultSet r=p.executeQuery()){while(r.next()){totalPresencas++;if("Presente".equals(r.getString(3)))presentes++;if(!first)b.append(',');first=false;b.append("{\"data\":\"").append(j(r.getString(1))).append("\",\"descricao\":\"").append(j(r.getString(2))).append("\",\"situacao\":\"").append(j(r.getString(3))).append("\",\"justificativa\":\"").append(j(r.getString(4))).append("\"}");}}}
   int percentualPresenca=totalPresencas>0?(int)Math.round(presentes*100.0/totalPresencas):0;
   boolean[] mesesEsperados=new boolean[13];int esperadas=0;String periodicidade="NENHUMA";boolean ateAtual=true;
   try(PreparedStatement p=c.prepareStatement("SELECT ContribuicaoPeriodicidade,ContribuicaoAteMesAtual FROM grupos WHERE IdGrupo=? AND StatusGrupo='ATIVO' AND ModuloContribuicoes=1 AND ContribuicaoAtiva=1")){p.setInt(1,classe);try(ResultSet r=p.executeQuery()){if(r.next()){periodicidade=r.getString(1);ateAtual=r.getBoolean(2);}}}
   if("MENSAL".equals(periodicidade)){int anoAtual=Year.now().getValue();int limite=!ateAtual||ano<anoAtual?12:ano==anoAtual?LocalDate.now().getMonthValue():0;for(int m=1;m<=limite;m++){mesesEsperados[m]=true;esperadas++;}}
   else if("ENCONTRO".equals(periodicidade)){try(PreparedStatement p=c.prepareStatement("SELECT DISTINCT MONTH(DtEncontro) FROM Encontros WHERE Classe=? AND Checklist=0 AND YEAR(DtEncontro)=?"+(ateAtual?" AND DtEncontro<=CURDATE()":""))){p.setInt(1,classe);p.setInt(2,ano);try(ResultSet r=p.executeQuery()){while(r.next()){int m=r.getInt(1);if(m>=1&&m<=12&&!mesesEsperados[m]){mesesEsperados[m]=true;esperadas++;}}}}}
   else if("MANUAL".equals(periodicidade)){try(PreparedStatement p=c.prepareStatement("SELECT DISTINCT MONTH(dtVencimento) FROM lancamentos WHERE idPessoa=? AND tipoLancamento='1.1' AND YEAR(dtVencimento)=?")){p.setInt(1,pessoa);p.setInt(2,ano);try(ResultSet r=p.executeQuery()){while(r.next()){int m=r.getInt(1);if(m>=1&&m<=12&&!mesesEsperados[m]){mesesEsperados[m]=true;esperadas++;}}}}}
   b.append("],\"percentualPresenca\":").append(percentualPresenca).append(",\"contribuicoes\":[");int pagos=0;boolean[] mesesPagos=new boolean[13];first=true;
   try(PreparedStatement p=c.prepareStatement("SELECT MONTH(dtVencimento),DATE_FORMAT(dtVencimento,'%m/%Y'),DATE_FORMAT(dtPagamento,'%d/%m/%Y'),IFNULL(valorPago,0),status FROM lancamentos WHERE idPessoa=? AND tipoLancamento='1.1' AND YEAR(dtVencimento)=? ORDER BY dtVencimento DESC")){p.setInt(1,pessoa);p.setInt(2,ano);try(ResultSet r=p.executeQuery()){while(r.next()){int mes=r.getInt(1);if(r.getInt(5)==1&&mes>=1&&mes<=12&&mesesEsperados[mes]&&!mesesPagos[mes]){mesesPagos[mes]=true;pagos++;}if(!first)b.append(',');first=false;b.append("{\"competencia\":\"").append(j(r.getString(2))).append("\",\"pagamento\":\"").append(j(r.getString(3))).append("\",\"valor\":\"R$ ").append(String.format(Locale.US,"%.2f",r.getDouble(4)).replace('.',',')).append("\",\"paga\":").append(r.getInt(5)==1).append('}');}}}
   int percentualContribuicao=esperadas>0?(int)Math.round(pagos*100.0/esperadas):0;
   b.append("],\"percentualContribuicao\":").append(percentualContribuicao).append("}");out.print(b);return;
  }
  if("pessoa".equals(acao)){
   int ciclo=inteiro(request.getParameter("ciclo")),pessoa=inteiro(request.getParameter("pessoa"));
   String sql="SELECT c.IdCiclo,c.DtCiclo,c.Classe,c.Descricao,s.IdPessoa,s.Nome,s.DtNascimento,s.Idade,IFNULL(s.Paroquia,''),IFNULL(s.Regiao,''),IFNULL(s.flgTeologia,0),IFNULL(s.flgSeminarioLeitor,0),IFNULL(s.flgSeminarioAcolito,0),IFNULL(s.flgOrdemSacra,0),IFNULL(s.flgLeitor,0),IFNULL(s.flgAcolito,0),IFNULL(s.DtOrdenacao,''),IFNULL(s.DtProvisao,''),IFNULL(s.Pastoral,''),IFNULL(DATE_FORMAT(pd.DtCasamento,'%d/%m/%Y'),''),IFNULL(TIMESTAMPDIFF(YEAR,pd.DtCasamento,CURDATE()),0),IFNULL(s.Profissao,'') FROM ciclos_avaliacao c JOIN sqlPessoas s ON s.IdPessoa=? AND (s.Classe=c.Classe OR EXISTS (SELECT 1 FROM avaliacoes_pessoa ax WHERE ax.IdCiclo=c.IdCiclo AND ax.IdPessoa=s.IdPessoa)) LEFT JOIN pessoas pd ON pd.IdPessoa=s.IdPessoa WHERE c.IdCiclo=?";
   StringBuilder b=new StringBuilder();try(PreparedStatement p=c.prepareStatement(sql)){p.setInt(1,pessoa);p.setInt(2,ciclo);try(ResultSet r=p.executeQuery()){if(!r.next()){response.setStatus(404);out.print("{\"ok\":false,\"mensagem\":\"Pessoa não pertence ao grupo deste ciclo.\"}");return;}b.append("{\"ok\":true,\"ciclo\":{\"id\":").append(r.getInt(1)).append(",\"data\":\"").append(r.getDate(2)).append("\",\"descricao\":\"").append(j(r.getString(4))).append("\"},\"pessoa\":{\"id\":").append(r.getInt(5)).append(",\"nome\":\"").append(j(r.getString(6))).append("\",\"nascimento\":\"").append(j(r.getString(7))).append("\",\"idade\":\"").append(j(r.getString(8))).append("\",\"paroquia\":\"").append(j(r.getString(9))).append("\",\"regiao\":\"").append(j(r.getString(10))).append("\",\"casamento\":\"").append(j(r.getString(20))).append("\",\"anosMatrimonio\":").append(r.getInt(21)).append(",\"profissao\":\"").append(j(r.getString(22))).append("\",\"ministerial\":{\"teologia\":").append(r.getInt(11)==1).append(",\"seminarioLeitor\":").append(r.getInt(12)==1).append(",\"seminarioAcolito\":").append(r.getInt(13)==1).append(",\"ordemSacra\":").append(r.getInt(14)==1).append(",\"leitor\":").append(r.getInt(15)==1).append(",\"acolito\":").append(r.getInt(16)==1).append(",\"dataOrdenacao\":\"").append(j(r.getString(17))).append("\",\"dataProvisao\":\"").append(j(r.getString(18))).append("\",\"pastoral\":\"").append(j(r.getString(19))).append("\"}},\"avaliacoes\":[");}}
   boolean f=true;try(PreparedStatement p=c.prepareStatement("SELECT a.IdAvaliacao,a.IdCiclo,a.DtAvaliacao,a.TextoAvaliacao,a.Resultado,IFNULL(a.AcaoTexto,''),IFNULL(a.AcaoResponsavel,''),IFNULL(a.AcaoStatus,''),c.Descricao,c.Classe FROM avaliacoes_pessoa a JOIN ciclos_avaliacao c ON c.IdCiclo=a.IdCiclo WHERE a.IdPessoa=? ORDER BY a.DtAvaliacao DESC,a.IdAvaliacao DESC")){p.setInt(1,pessoa);try(ResultSet r=p.executeQuery()){while(r.next()){if(!f)b.append(',');f=false;b.append("{\"id\":").append(r.getInt(1)).append(",\"idCiclo\":").append(r.getInt(2)).append(",\"data\":\"").append(r.getDate(3)).append("\",\"dataFormatada\":\"").append(r.getDate(3).toLocalDate().format(DateTimeFormatter.ofPattern("dd/MM/yyyy"))).append("\",\"texto\":\"").append(j(r.getString(4))).append("\",\"resultado\":\"").append(r.getString(5)).append("\",\"acao\":\"").append(j(r.getString(6))).append("\",\"responsavel\":\"").append(j(r.getString(7))).append("\",\"status\":\"").append(j(r.getString(8))).append("\",\"ciclo\":\"").append(j(r.getString(9))).append("\",\"grupo\":\"").append(j(grupo(r.getInt(10)))).append("\"}");}}}
   out.print(b.append("]}"));return;
  }
  if("salvarAvaliacao".equals(acao)){
   if(!administrador){response.setStatus(403);out.print("{\"ok\":false,\"mensagem\":\"Perfil autorizado apenas para consulta.\"}");return;}
   if(!"POST".equalsIgnoreCase(request.getMethod())){response.setStatus(405);out.print("{\"ok\":false,\"mensagem\":\"Método não permitido.\"}");return;}
   int id=request.getParameter("id")==null||request.getParameter("id").isEmpty()?0:inteiro(request.getParameter("id")),ciclo=inteiro(request.getParameter("ciclo")),pessoa=inteiro(request.getParameter("pessoa"));
   String data=request.getParameter("data"),texto=request.getParameter("texto"),resultado=request.getParameter("resultado"),acaoTexto=request.getParameter("acaoTexto"),responsavel=request.getParameter("responsavel"),status=request.getParameter("status");
   if(data==null||texto==null||texto.trim().isEmpty()||(!"NEGATIVA".equals(resultado)&&!"NEUTRA".equals(resultado)&&!"POSITIVA".equals(resultado))){response.setStatus(400);out.print("{\"ok\":false,\"mensagem\":\"Informe data, avaliação e resultado.\"}");return;}
   boolean temAcao=acaoTexto!=null&&!acaoTexto.trim().isEmpty();if(!temAcao){acaoTexto=null;responsavel=null;status=null;}else if(!"PENDENTE".equals(status)&&!"CONCLUIDA".equals(status))status="PENDENTE";
   try(PreparedStatement validar=c.prepareStatement("SELECT 1 FROM ciclos_avaliacao c JOIN pessoas p ON p.IdPessoa=? AND (p.Classe=c.Classe OR EXISTS (SELECT 1 FROM avaliacoes_pessoa ax WHERE ax.IdCiclo=c.IdCiclo AND ax.IdPessoa=p.IdPessoa)) WHERE c.IdCiclo=?")){validar.setInt(1,pessoa);validar.setInt(2,ciclo);try(ResultSet r=validar.executeQuery()){if(!r.next()){response.setStatus(400);out.print("{\"ok\":false,\"mensagem\":\"Pessoa não pertence ao grupo deste ciclo.\"}");return;}}}
   if(id==0){try(PreparedStatement p=c.prepareStatement("INSERT INTO avaliacoes_pessoa(IdCiclo,IdPessoa,DtAvaliacao,TextoAvaliacao,Resultado,AcaoTexto,AcaoResponsavel,AcaoStatus,IdUsuarioCriacao) VALUES(?,?,?,?,?,?,?,?,?)")){p.setInt(1,ciclo);p.setInt(2,pessoa);p.setDate(3,Date.valueOf(data));p.setString(4,texto.trim());p.setString(5,resultado);p.setString(6,acaoTexto);p.setString(7,responsavel);p.setString(8,status);p.setInt(9,usuarioId);p.executeUpdate();}}
   else{try(PreparedStatement p=c.prepareStatement("UPDATE avaliacoes_pessoa SET DtAvaliacao=?,TextoAvaliacao=?,Resultado=?,AcaoTexto=?,AcaoResponsavel=?,AcaoStatus=?,IdUsuarioAtualizacao=?,DtAtualizacao=NOW() WHERE IdAvaliacao=? AND IdCiclo=? AND IdPessoa=?")){p.setDate(1,Date.valueOf(data));p.setString(2,texto.trim());p.setString(3,resultado);p.setString(4,acaoTexto);p.setString(5,responsavel);p.setString(6,status);p.setInt(7,usuarioId);p.setInt(8,id);p.setInt(9,ciclo);p.setInt(10,pessoa);if(p.executeUpdate()==0)throw new SQLException("Avaliação não encontrada");}}
   out.print("{\"ok\":true}");return;
  }
  response.setStatus(400);out.print("{\"ok\":false,\"mensagem\":\"Ação inválida.\"}");
 }
}catch(SQLIntegrityConstraintViolationException e){response.setStatus(409);out.print("{\"ok\":false,\"mensagem\":\"Esta pessoa já possui avaliação neste ciclo.\"}");}
catch(Exception e){response.setStatus(500);out.print("{\"ok\":false,\"mensagem\":\"Não foi possível processar a solicitação. Verifique se as tabelas do módulo foram criadas.\"}");}
%>
