<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ include file="includes/auth.jsp" %><%@ include file="includes/access.jsp" %>
<!DOCTYPE html><html lang="pt-br"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Contribuições</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"><link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet"><link rel="stylesheet" href="css/style.css"><style>#areaImpressaoContrib{display:none}@media print{body>*{display:none!important}#areaImpressaoContrib{display:block!important;color:#000;font-family:Arial,sans-serif}#areaImpressaoContrib h1{font-size:18pt;margin:0 0 4px}#areaImpressaoContrib p{margin:0 0 16px}#areaImpressaoContrib table{display:table!important;width:100%;border-collapse:collapse;font-size:10pt}#areaImpressaoContrib th,#areaImpressaoContrib td{display:table-cell!important;border:1px solid #555;padding:7px;text-align:left;vertical-align:top}#areaImpressaoContrib th{background:#e9ecef!important;-webkit-print-color-adjust:exact;print-color-adjust:exact}}</style></head><body>
<script>
document.addEventListener("DOMContentLoaded",function(){
 var filtros=document.querySelector(".container.py-4 .row.g-3.mb-4");
 if(!filtros)return;
 var area=document.createElement("div");
 area.className="d-flex justify-content-end mb-3";
 area.innerHTML='<a class="btn btn-outline-primary" href="relatorioContribuicoes.jsp"><i class="bi bi-table"></i> Mapa de contribuições</a>';
 filtros.parentNode.insertBefore(area,filtros);
});
</script>
<jsp:include page="includes/header.jsp"/><div class="container py-4"><div class="mb-4"><h1 class="fw-bold">Contribuições Financeiras</h1><p class="text-muted">Controle mensal de contribuições</p></div><div class="row g-3 mb-4"><div class="col-md-2"><select id="filterMesContrib" class="form-select"></select></div><div class="col-md-2"><select id="filterAnoContrib" class="form-select"></select></div><div class="col-md-3"><select id="filterGrupoContrib" class="form-select" data-catalogo-grupos data-grupos-modulo="contribuicoes" data-grupos-operacionais="true" data-grupos-todos="true"><option value="">Carregando grupos...</option></select></div><div class="col-md-2"><select id="filterStatusContrib" class="form-select"><option value="">Todos</option><option value="1">Já contribuíram</option><option value="0">Pendentes</option></select></div><div class="col-md-2"><input id="searchContrib" class="form-control" placeholder="Buscar por nome..."></div><div class="col-md-1"><button type="button" class="btn btn-outline-secondary w-100" onclick="imprimirContribuicoes()" title="Imprimir"><i class="bi bi-printer"></i></button></div></div><div class="row g-3 mb-4"><div class="col-md-6"><div class="dashboard-card contribution-stat"><h5>Contribuíram</h5><div id="totalPagos" class="card-number presenca-ok">0</div><span id="percentualPagos" class="text-muted">0%</span></div></div><div class="col-md-6"><div class="dashboard-card contribution-stat"><h5>Pendentes</h5><div id="totalPendentes" class="card-number presenca-falta">0</div><span id="percentualPendentes" class="text-muted">0%</span></div></div></div><div class="contribution-card"><div class="d-flex justify-content-between mb-4"><h3 id="competenciaTitulo"></h3><span id="resumoContrib" class="badge-tag tag-green"></span></div><div id="contributionsContainer"></div></div></div><div id="areaImpressaoContrib"></div><jsp:include page="includes/footer.jsp"/><script>window.podeRegistrarContribuicao=<%= "ADM".equals((String)session.getAttribute("usuarioPerfil")) || "FIN".equals((String)session.getAttribute("usuarioPerfil")) %>;</script><script src="js/contribuicoes.js?v=9"></script></body></html>
