<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %><%@ include file="includes/auth.jsp" %>
<% String perfilDocumentos=(String)session.getAttribute("usuarioPerfil");boolean admDocumentos="ADM".equals(perfilDocumentos),gestaoDocumentos=admDocumentos||"EXT".equals(perfilDocumentos); %>
<!DOCTYPE html><html lang="pt-br"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Documentações</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"><link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet"><link rel="stylesheet" href="css/style.css"><style>.doc-row-selected td{background:#fff5e9!important}.doc-status{font-size:.78rem}.doc-visible{color:#15803d}.doc-hidden{color:#94a3b8}</style></head><body><jsp:include page="includes/header.jsp"/>
<main class="container py-4">
<div class="d-flex justify-content-between align-items-start gap-3 flex-wrap mb-4"><div><h1 class="fw-bold mb-1">Documentações</h1><p class="text-muted mb-0"><%= gestaoDocumentos?"Checklists e acompanhamento de documentos por grupo":"Documentos solicitados para o seu grupo" %></p></div><% if(admDocumentos){ %><button class="btn btn-orange" onclick="novoChecklist()"><i class="bi bi-plus-lg"></i> Novo checklist</button><% } %></div>
<% if(gestaoDocumentos){ %>
<section class="profile-card mb-4"><div class="d-flex justify-content-between align-items-center mb-3"><h4 class="mb-0">Checklists cadastrados</h4><small class="text-muted">Selecione para visualizar os itens</small></div><div class="table-responsive"><table class="table table-hover align-middle"><thead><tr><th>Checklist</th><th>Grupo</th><th>Status</th><th>Itens</th><th>Membros ativos</th><th></th></tr></thead><tbody id="checklistsBody"><tr><td colspan="6" class="text-muted">Carregando...</td></tr></tbody></table></div></section>
<section class="profile-card"><div class="d-flex justify-content-between align-items-center gap-3 mb-3"><div><h4 id="itensTitulo" class="mb-1">Itens do checklist</h4><small id="itensSubtitulo" class="text-muted">Selecione um checklist acima.</small></div><% if(admDocumentos){ %><button id="novoItemBtn" class="btn btn-orange" onclick="novoItem()" disabled><i class="bi bi-plus-lg"></i> Novo item</button><% } %></div><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Ordem</th><th>Documento/atividade</th><th>Visível ao membro</th><th>Status</th><% if(admDocumentos){ %><th></th><% } %></tr></thead><tbody id="itensBody"><tr><td colspan="5" class="text-muted">Nenhum checklist selecionado.</td></tr></tbody></table></div></section>
<% }else{ %>
<div class="row g-3 mb-4"><div class="col-md-4"><div class="dashboard-card"><h5>Documentos solicitados</h5><div id="meusDocsTotal" class="card-number">—</div></div></div><div class="col-md-4"><div class="dashboard-card"><h5>Entregues</h5><div id="meusDocsConcluidos" class="card-number text-success">—</div></div></div><div class="col-md-4"><div class="dashboard-card"><h5>Pendentes</h5><div id="meusDocsPendentes" class="card-number text-warning">—</div></div></div></div>
<section class="profile-card"><h4 class="mb-3">Meus documentos</h4><div id="meusDocumentosLista"><div class="text-muted">Carregando...</div></div></section>
<% } %>
</main>
<% if(admDocumentos){ %>
<div class="modal fade" id="checklistModal" tabindex="-1"><div class="modal-dialog"><div class="modal-content"><div class="modal-header"><h5 class="modal-title">Checklist</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><input id="checklistId" type="hidden"><div class="mb-3"><label class="form-label">Nome do checklist</label><input id="checklistNome" class="form-control" placeholder="Ex.: Documentação para ingresso"></div><div class="row g-3"><div class="col-md-7"><label class="form-label">Grupo</label><select id="checklistClasse" class="form-select" data-catalogo-grupos data-grupos-modulo="documentacao" data-grupos-operacionais="true"><option value="">Carregando grupos...</option></select></div><div class="col-md-5"><label class="form-label">Status</label><select id="checklistStatus" class="form-select"><option value="ATIVO">Ativo</option><option value="INATIVO">Inativo</option></select></div></div></div><div class="modal-footer"><button class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button><button class="btn btn-orange" onclick="salvarChecklist()">Salvar</button></div></div></div></div>
<div class="modal fade" id="itemModal" tabindex="-1"><div class="modal-dialog"><div class="modal-content"><div class="modal-header"><h5 class="modal-title">Item do checklist</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><input id="itemId" type="hidden"><div class="mb-3"><label class="form-label">Documento ou atividade</label><input id="itemDescricao" class="form-control" placeholder="Ex.: Carta de indicação do pároco"></div><div class="row g-3"><div class="col-md-4"><label class="form-label">Ordem</label><input id="itemOrdem" type="number" class="form-control" value="0"></div><div class="col-md-4"><label class="form-label">Status</label><select id="itemStatus" class="form-select"><option value="ATIVO">Ativo</option><option value="INATIVO">Inativo</option></select></div><div class="col-md-4 d-flex align-items-end"><label class="form-check mb-2"><input id="itemExibir" type="checkbox" class="form-check-input" checked> <span class="form-check-label">Exibir ao membro</span></label></div><div class="col-12"><label class="form-check"><input id="itemPermiteUpload" type="checkbox" class="form-check-input"> <span class="form-check-label">Permitir que o membro envie um arquivo</span></label></div><div id="itemPrefixoArea" class="col-12 d-none"><label class="form-label">Prefixo do arquivo</label><input id="itemPrefixo" class="form-control text-uppercase" maxlength="40" placeholder="Ex.: CERTIDAO"><div class="form-text">PDF ou imagem, com tamanho máximo de 3 MB.</div></div></div></div><div class="modal-footer"><button class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button><button class="btn btn-orange" onclick="salvarItem()">Salvar</button></div></div></div></div>
<% } %>
<jsp:include page="includes/footer.jsp"/><script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script><script>window.documentacaoPodeEditar=<%= admDocumentos %>;window.documentacaoGestao=<%= gestaoDocumentos %>;</script><script src="js/documentacoes.js?v=20260824-2"></script></body></html>
