<%@ page import="java.sql.*,java.time.*" %><%@ page contentType="application/json; charset=UTF-8" pageEncoding="UTF-8" %>
<%!
String jf(String s){return s==null?"":s.replace("\\","\\\\").replace("\"","\\\"").replace("\r","\\r").replace("\n","\\n");}
int fi(String s,int d){try{return Integer.parseInt(s);}catch(Exception e){return d;}}
void estrutura(Connection c)throws SQLException{
 try(Statement s=c.createStatement()){
  s.executeUpdate("CREATE TABLE IF NOT EXISTS financeiro_contas(IdConta INT AUTO_INCREMENT PRIMARY KEY,Codigo VARCHAR(20) NOT NULL UNIQUE,Nome VARCHAR(120) NOT NULL,Tipo ENUM('ENTRADA','SAIDA') NOT NULL,StatusConta ENUM('ATIVA','INATIVA') NOT NULL DEFAULT 'ATIVA')");
  s.executeUpdate("CREATE TABLE IF NOT EXISTS financeiro_lancamentos(IdLancamento INT AUTO_INCREMENT PRIMARY KEY,IdGrupo INT NOT NULL,IdConta INT NOT NULL,Tipo ENUM('ENTRADA','SAIDA') NOT NULL,Descricao VARCHAR(255) NOT NULL,Competencia DATE NOT NULL,DtPrevista DATE NULL,DtRealizada DATE NULL,Valor DECIMAL(12,2) NOT NULL,Situacao ENUM('PREVISTO','REALIZADO','CANCELADO') NOT NULL DEFAULT 'PREVISTO',Origem ENUM('MANUAL','CONTRIBUICOES') NOT NULL DEFAULT 'MANUAL',Referencia VARCHAR(80) NULL,IdUsuarioCriacao INT NOT NULL,DtCriacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,IdUsuarioAtualizacao INT NULL,DtAtualizacao TIMESTAMP NULL,UNIQUE KEY uk_fin_origem_referencia(Origem,Referencia),KEY ix_fin_competencia(Competencia),KEY ix_fin_grupo(IdGrupo))");
  s.executeUpdate("CREATE TABLE IF NOT EXISTS financeiro_lancamentos_log(IdLog BIGINT AUTO_INCREMENT PRIMARY KEY,IdLancamento INT NULL,Acao VARCHAR(20) NOT NULL,IdUsuario INT NOT NULL,DtLog TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,DadosAnteriores TEXT NULL,DadosNovos TEXT NULL,Motivo VARCHAR(500) NULL)");
  s.executeUpdate("INSERT IGNORE INTO financeiro_contas(Codigo,Nome,Tipo) VALUES('1.01','Contribuições','ENTRADA'),('1.02','Doações','ENTRADA'),('1.03','Eventos','ENTRADA'),('2.01','Alimentação','SAIDA'),('2.02','Transporte','SAIDA'),('2.03','Material','SAIDA'),('2.04','Outras despesas','SAIDA')");
 }
}
void logf(Connection c,int id,String acao,int usuario,String antes,String depois,String motivo)throws SQLException{if("EDICAO".equals(acao)&&(antes==null||antes.isEmpty()))acao="CRIACAO";try(PreparedStatement p=c.prepareStatement("INSERT INTO financeiro_lancamentos_log(IdLancamento,Acao,IdUsuario,DadosAnteriores,DadosNovos,Motivo)VALUES(?,?,?,?,?,?)")){if(id==0)p.setNull(1,Types.INTEGER);else p.setInt(1,id);p.setString(2,acao);p.setInt(3,usuario);p.setString(4,antes);p.setString(5,depois);p.setString(6,motivo);p.executeUpdate();}}
String estado(Connection c,int id)throws SQLException{try(PreparedStatement p=c.prepareStatement("SELECT CONCAT('grupo=',IdGrupo,';conta=',IdConta,';tipo=',Tipo,';valor=',Valor,';situacao=',Situacao,';competencia=',Competencia,';descricao=',Descricao) FROM financeiro_lancamentos WHERE IdLancamento=?")){p.setInt(1,id);try(ResultSet r=p.executeQuery()){return r.next()?r.getString(1):"";}}}
void sincronizar(Connection c,int usuario)throws SQLException{
 int conta=0;try(PreparedStatement p=c.prepareStatement("SELECT IdConta FROM financeiro_contas WHERE Codigo='1.01'" );ResultSet r=p.executeQuery()){if(r.next())conta=r.getInt(1);}if(conta==0)return;
 String q="SELECT idClasse,YEAR(dtVencimento) ano,MONTH(dtVencimento) mes,SUM(valorPago) total,COUNT(*) qtd FROM lancamentos WHERE tipoLancamento='1.1' AND status=1 GROUP BY idClasse,YEAR(dtVencimento),MONTH(dtVencimento)";
 try(PreparedStatement p=c.prepareStatement(q);ResultSet r=p.executeQuery();PreparedStatement u=c.prepareStatement("INSERT INTO financeiro_lancamentos(IdGrupo,IdConta,Tipo,Descricao,Competencia,DtRealizada,Valor,Situacao,Origem,Referencia,IdUsuarioCriacao)VALUES(?,?,'ENTRADA',?,? ,LAST_DAY(?),?,'REALIZADO','CONTRIBUICOES',?,?) ON DUPLICATE KEY UPDATE Descricao=VALUES(Descricao),Valor=VALUES(Valor),DtRealizada=VALUES(DtRealizada),Situacao='REALIZADO',IdUsuarioAtualizacao=VALUES(IdUsuarioCriacao),DtAtualizacao=NOW()")){while(r.next()){Date comp=Date.valueOf(String.format("%04d-%02d-01",r.getInt("ano"),r.getInt("mes")));String ref="CONTRIB:"+r.getInt("idClasse")+":"+String.format("%04d-%02d",r.getInt("ano"),r.getInt("mes"));u.setInt(1,r.getInt("idClasse"));u.setInt(2,conta);u.setString(3,"Contribuições mensais — "+String.format("%02d/%04d",r.getInt("mes"),r.getInt("ano"))+" ("+r.getInt("qtd")+" pagamentos)");u.setDate(4,comp);u.setDate(5,comp);u.setBigDecimal(6,r.getBigDecimal("total"));u.setString(7,ref);u.setInt(8,usuario);u.addBatch();}u.executeBatch();}
}
%>
<%
String perfil=(String)session.getAttribute("usuarioPerfil");Integer usuario=(Integer)session.getAttribute("usuarioId"),grupoSessao=(Integer)session.getAttribute("usuarioGrupoId");
if((!"ADM".equals(perfil)&&!"FIN".equals(perfil))||usuario==null){response.setStatus(403);out.print("{\"ok\":false,\"mensagem\":\"Acesso não autorizado.\"}");return;}boolean adm="ADM".equals(perfil);String acao=request.getParameter("acao");
try(Connection c=cad.db.Database.getConnection()){estrutura(c);
 if("listar".equals(acao)){sincronizar(c,usuario);int mes=fi(request.getParameter("mes"),LocalDate.now().getMonthValue()),ano=fi(request.getParameter("ano"),LocalDate.now().getYear()),grupo=adm?fi(request.getParameter("grupo"),-1):grupoSessao;String sql="SELECT l.IdLancamento,l.IdGrupo,g.NomePlural,c.Codigo,c.Nome,l.Tipo,l.Descricao,l.Competencia,l.DtPrevista,l.DtRealizada,l.Valor,l.Situacao,l.Origem FROM financeiro_lancamentos l JOIN grupos g ON g.IdGrupo=l.IdGrupo JOIN financeiro_contas c ON c.IdConta=l.IdConta WHERE MONTH(l.Competencia)=? AND YEAR(l.Competencia)=?"+(grupo>=0?" AND l.IdGrupo=?":"")+" ORDER BY l.Competencia,l.IdLancamento";StringBuilder b=new StringBuilder("{\"ok\":true,\"lancamentos\":[");boolean f=true;try(PreparedStatement p=c.prepareStatement(sql)){p.setInt(1,mes);p.setInt(2,ano);if(grupo>=0)p.setInt(3,grupo);try(ResultSet r=p.executeQuery()){while(r.next()){if(!f)b.append(',');f=false;b.append("{\"id\":").append(r.getInt(1)).append(",\"grupoId\":").append(r.getInt(2)).append(",\"grupo\":\"").append(jf(r.getString(3))).append("\",\"conta\":\"").append(jf(r.getString(4)+" — "+r.getString(5))).append("\",\"tipo\":\"").append(r.getString(6)).append("\",\"descricao\":\"").append(jf(r.getString(7))).append("\",\"competencia\":\"").append(r.getDate(8)).append("\",\"prevista\":\"").append(r.getDate(9)==null?"":r.getDate(9)).append("\",\"realizada\":\"").append(r.getDate(10)==null?"":r.getDate(10)).append("\",\"valor\":").append(r.getBigDecimal(11)).append(",\"situacao\":\"").append(r.getString(12)).append("\",\"origem\":\"").append(r.getString(13)).append("\"}");}}}out.print(b.append("]}"));return;}
 if("contas".equals(acao)||"grupos".equals(acao)){String sql="contas".equals(acao)?"SELECT IdConta,Codigo,Nome,Tipo,StatusConta FROM financeiro_contas ORDER BY Tipo,Codigo":"SELECT IdGrupo,NomePlural FROM grupos WHERE StatusGrupo='ATIVO' AND GrupoOperacional=1 ORDER BY Ordem";String chave="contas".equals(acao)?"contas":"grupos";StringBuilder b=new StringBuilder("{\"ok\":true,\"").append(chave).append("\":[");boolean f=true;try(PreparedStatement p=c.prepareStatement(sql);ResultSet r=p.executeQuery()){while(r.next()){if(!f)b.append(',');f=false;if("contas".equals(acao))b.append("{\"id\":").append(r.getInt(1)).append(",\"codigo\":\"").append(jf(r.getString(2))).append("\",\"nome\":\"").append(jf(r.getString(3))).append("\",\"tipo\":\"").append(r.getString(4)).append("\",\"status\":\"").append(r.getString(5)).append("\"}");else b.append("{\"id\":").append(r.getInt(1)).append(",\"nome\":\"").append(jf(r.getString(2))).append("\"}");}}out.print(b.append("]}"));return;}
 if("detalhesContribuicoes".equals(acao)){int id=fi(request.getParameter("id"),0);String sql="SELECT l.IdGrupo,l.Competencia FROM financeiro_lancamentos l WHERE l.IdLancamento=? AND l.Origem='CONTRIBUICOES'"+(!adm?" AND l.IdGrupo=?":"");int grupo=0;Date competencia=null;try(PreparedStatement p=c.prepareStatement(sql)){p.setInt(1,id);if(!adm)p.setInt(2,grupoSessao);try(ResultSet r=p.executeQuery()){if(r.next()){grupo=r.getInt(1);competencia=r.getDate(2);}}}if(competencia==null)throw new SecurityException();StringBuilder b=new StringBuilder("{\"ok\":true,\"itens\":[");boolean f=true;try(PreparedStatement p=c.prepareStatement("SELECT pe.Nome,DATE_FORMAT(l.dtPagamento,'%d/%m/%Y'),l.valorPago,IFNULL(u.Nome,'') Usuario FROM lancamentos l JOIN pessoas pe ON pe.IdPessoa=l.idPessoa LEFT JOIN pessoas u ON u.IdPessoa=l.idUsuario WHERE l.tipoLancamento='1.1' AND l.status=1 AND l.idClasse=? AND YEAR(l.dtVencimento)=YEAR(?) AND MONTH(l.dtVencimento)=MONTH(?) ORDER BY pe.Nome")){p.setInt(1,grupo);p.setDate(2,competencia);p.setDate(3,competencia);try(ResultSet r=p.executeQuery()){while(r.next()){if(!f)b.append(',');f=false;b.append("{\"membro\":\"").append(jf(r.getString(1))).append("\",\"data\":\"").append(jf(r.getString(2))).append("\",\"valor\":").append(r.getBigDecimal(3)).append(",\"usuario\":\"").append(jf(r.getString(4))).append("\"}");}}}out.print(b.append("]}"));return;}
 if("log".equals(acao)){int id=fi(request.getParameter("id"),0);String acesso="SELECT 1 FROM financeiro_lancamentos WHERE IdLancamento=?"+(!adm?" AND IdGrupo=?":"");try(PreparedStatement p=c.prepareStatement(acesso)){p.setInt(1,id);if(!adm)p.setInt(2,grupoSessao);try(ResultSet r=p.executeQuery()){if(!r.next())throw new SecurityException();}}StringBuilder b=new StringBuilder("{\"ok\":true,\"logs\":[");boolean f=true;try(PreparedStatement p=c.prepareStatement("SELECT DATE_FORMAT(l.DtLog,'%d/%m/%Y %H:%i'),l.Acao,IFNULL(u.Nome,''),IFNULL(l.DadosAnteriores,''),IFNULL(l.DadosNovos,''),IFNULL(l.Motivo,'') FROM financeiro_lancamentos_log l LEFT JOIN pessoas u ON u.IdPessoa=l.IdUsuario WHERE l.IdLancamento=? ORDER BY l.IdLog DESC")){p.setInt(1,id);try(ResultSet r=p.executeQuery()){while(r.next()){if(!f)b.append(',');f=false;b.append("{\"data\":\"").append(jf(r.getString(1))).append("\",\"acao\":\"").append(jf(r.getString(2))).append("\",\"usuario\":\"").append(jf(r.getString(3))).append("\",\"antes\":\"").append(jf(r.getString(4))).append("\",\"depois\":\"").append(jf(r.getString(5))).append("\",\"motivo\":\"").append(jf(r.getString(6))).append("\"}");}}}out.print(b.append("]}"));return;}
 if(!"POST".equalsIgnoreCase(request.getMethod())){response.setStatus(400);out.print("{\"ok\":false}");return;}
 if("salvarConta".equals(acao)){if(!adm)throw new SecurityException();int contaId=fi(request.getParameter("id"),0);String codigo=request.getParameter("codigo"),nomeConta=request.getParameter("nome"),tipoConta=request.getParameter("tipo"),statusConta=request.getParameter("status");if(codigo==null||codigo.trim().isEmpty()||nomeConta==null||nomeConta.trim().isEmpty()||(!"ENTRADA".equals(tipoConta)&&!"SAIDA".equals(tipoConta)))throw new IllegalArgumentException("Informe os dados da conta.");codigo=codigo.trim();if(("ENTRADA".equals(tipoConta)&&!codigo.startsWith("1."))||("SAIDA".equals(tipoConta)&&!codigo.startsWith("2.")))throw new IllegalArgumentException("Use códigos 1.xx para entradas e 2.xx para saídas.");String sqlConta=contaId==0?"INSERT INTO financeiro_contas(Codigo,Nome,Tipo,StatusConta)VALUES(?,?,?,?)":"UPDATE financeiro_contas SET Codigo=?,Nome=?,Tipo=?,StatusConta=? WHERE IdConta=?";try(PreparedStatement p=c.prepareStatement(sqlConta)){p.setString(1,codigo);p.setString(2,nomeConta.trim());p.setString(3,tipoConta);p.setString(4,"INATIVA".equals(statusConta)?"INATIVA":"ATIVA");if(contaId>0)p.setInt(5,contaId);p.executeUpdate();}out.print("{\"ok\":true}");return;}
 int id=fi(request.getParameter("id"),0),grupo=adm?fi(request.getParameter("grupo"),-1):grupoSessao;if(grupo<0){response.setStatus(400);out.print("{\"ok\":false,\"mensagem\":\"Grupo inválido.\"}");return;}
 if("salvar".equals(acao)){int conta=fi(request.getParameter("conta"),0);String tipo=request.getParameter("tipo"),descricao=request.getParameter("descricao"),competencia=request.getParameter("competencia"),prevista=request.getParameter("prevista"),valor=request.getParameter("valor");if(id>0){try(PreparedStatement v=c.prepareStatement("SELECT 1 FROM financeiro_lancamentos WHERE IdLancamento=? AND IdGrupo=? AND Origem='MANUAL'")){v.setInt(1,id);v.setInt(2,grupo);try(ResultSet r=v.executeQuery()){if(!r.next())throw new SecurityException();}}}String antes=id>0?estado(c,id):"";String sql=id==0?"INSERT INTO financeiro_lancamentos(IdGrupo,IdConta,Tipo,Descricao,Competencia,DtPrevista,Valor,Situacao,Origem,IdUsuarioCriacao)VALUES(?,?,?,?,?,?,?,'PREVISTO','MANUAL',?)":"UPDATE financeiro_lancamentos SET IdConta=?,Tipo=?,Descricao=?,Competencia=?,DtPrevista=?,Valor=?,IdUsuarioAtualizacao=?,DtAtualizacao=NOW() WHERE IdLancamento=? AND IdGrupo=?";try(PreparedStatement p=c.prepareStatement(sql,Statement.RETURN_GENERATED_KEYS)){int x=1;if(id==0)p.setInt(x++,grupo);p.setInt(x++,conta);p.setString(x++,tipo);p.setString(x++,descricao.trim());p.setDate(x++,Date.valueOf(competencia+"-01"));p.setDate(x++,Date.valueOf(prevista));p.setBigDecimal(x++,new java.math.BigDecimal(valor));p.setInt(x++,usuario);if(id>0){p.setInt(x++,id);p.setInt(x++,grupo);}p.executeUpdate();if(id==0)try(ResultSet r=p.getGeneratedKeys()){if(r.next())id=r.getInt(1);}}logf(c,id,id==0?"CRIACAO":"EDICAO",usuario,antes,estado(c,id),null);out.print("{\"ok\":true}");return;}
 String antes=estado(c,id);if(antes.isEmpty()){response.setStatus(404);out.print("{\"ok\":false}");return;}try(PreparedStatement v=c.prepareStatement("SELECT Situacao,Origem FROM financeiro_lancamentos WHERE IdLancamento=? AND IdGrupo=?")){v.setInt(1,id);v.setInt(2,grupo);try(ResultSet r=v.executeQuery()){if(!r.next())throw new SecurityException();String sit=r.getString(1),origem=r.getString(2);if("CONTRIBUICOES".equals(origem))throw new IllegalArgumentException("Lançamento automático deve ser corrigido nas contribuições.");if("excluir".equals(acao)&&!"PREVISTO".equals(sit))throw new IllegalArgumentException("Somente previstos podem ser excluídos.");if("cancelar".equals(acao)&&!"REALIZADO".equals(sit))throw new IllegalArgumentException("Somente realizados podem ser cancelados.");}}
 if("realizar".equals(acao)){try(PreparedStatement p=c.prepareStatement("UPDATE financeiro_lancamentos SET Valor=?,Situacao='REALIZADO',DtRealizada=?,IdUsuarioAtualizacao=?,DtAtualizacao=NOW() WHERE IdLancamento=? AND IdGrupo=? AND Situacao='PREVISTO'")){p.setBigDecimal(1,new java.math.BigDecimal(request.getParameter("valor")));p.setDate(2,Date.valueOf(request.getParameter("data")));p.setInt(3,usuario);p.setInt(4,id);p.setInt(5,grupo);p.executeUpdate();}logf(c,id,"REALIZACAO",usuario,antes,estado(c,id),null);}
 else if("cancelar".equals(acao)){String motivo=request.getParameter("motivo");if(motivo==null||motivo.trim().isEmpty())throw new IllegalArgumentException("Informe o motivo.");try(PreparedStatement p=c.prepareStatement("UPDATE financeiro_lancamentos SET Situacao='CANCELADO',IdUsuarioAtualizacao=?,DtAtualizacao=NOW() WHERE IdLancamento=? AND IdGrupo=?")){p.setInt(1,usuario);p.setInt(2,id);p.setInt(3,grupo);p.executeUpdate();}logf(c,id,"CANCELAMENTO",usuario,antes,estado(c,id),motivo);}
 else if("excluir".equals(acao)){logf(c,id,"EXCLUSAO",usuario,antes,null,request.getParameter("motivo"));try(PreparedStatement p=c.prepareStatement("DELETE FROM financeiro_lancamentos WHERE IdLancamento=? AND IdGrupo=?")){p.setInt(1,id);p.setInt(2,grupo);p.executeUpdate();}}
 out.print("{\"ok\":true}");
}catch(SecurityException e){response.setStatus(403);out.print("{\"ok\":false,\"mensagem\":\"Acesso não autorizado ao grupo.\"}");}catch(Exception e){e.printStackTrace();response.setStatus(400);out.print("{\"ok\":false,\"mensagem\":\""+jf(e.getMessage()==null?"Não foi possível processar o lançamento.":e.getMessage())+"\"}");}
%>
