<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ include file="includes/auth.jsp" %>
<%
String perfilFormacao=(String)session.getAttribute("usuarioPerfil");Integer usuarioFormacao=(Integer)session.getAttribute("usuarioId");int pessoaFormacao=usuarioFormacao==null?0:usuarioFormacao,programaFormacao=0;
try{programaFormacao=Integer.parseInt(request.getParameter("programa"));String id=request.getParameter("pessoa");if(id!=null&&("ADM".equals(perfilFormacao)||"REP".equals(perfilFormacao)||"EXT".equals(perfilFormacao)))pessoaFormacao=Integer.parseInt(id);}catch(Exception ignored){}
boolean podeEditarFormacao="ADM".equals(perfilFormacao)||(usuarioFormacao!=null&&usuarioFormacao.intValue()==pessoaFormacao);if("EXT".equals(perfilFormacao))podeEditarFormacao=false;
%>
<!DOCTYPE html><html lang="pt-br"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Programa de Formação</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"><link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet"><link rel="stylesheet" href="css/style.css"><style>
.formation-hero{background:#fff;border:1px solid #e8edf3;border-radius:18px;padding:24px;box-shadow:0 3px 14px rgba(15,23,42,.05)}.formation-progress{height:13px;border-radius:999px;background:#e9eef4;overflow:hidden}.formation-progress-bar{height:100%;background:linear-gradient(90deg,#c96a0a,#e99a45)}.formation-stat{height:100%;padding:15px;border-radius:13px;background:#f8fafc}.formation-stat strong{display:block;font-size:24px}.block-title{font-size:16px;font-weight:750;color:#475569;margin:26px 0 10px}.formation-table-card{background:#fff;border:1px solid #e8edf3;border-radius:14px;overflow:hidden}.formation-table{margin:0}.formation-table th{background:#f8fafc;color:#64748b;font-size:12px;text-transform:uppercase;letter-spacing:.03em;white-space:nowrap}.formation-table td{vertical-align:middle}.formation-name{font-weight:650}.formation-type{display:inline-block;font-size:11px;border-radius:999px;padding:5px 9px;background:#f1f5f9;color:#475569;font-weight:700}.formation-status{min-width:180px}.formation-status .form-select{width:100%;min-width:0}
@media (max-width:767.98px){.formation-hero{padding:18px}.formation-table-card{overflow:visible;border:0;background:transparent}.formation-table,.formation-table tbody,.formation-table tr,.formation-table td{display:block;width:100%}.formation-table thead{display:none}.formation-table tbody{display:grid;gap:12px}.formation-table tr{padding:14px;background:#fff;border:1px solid #e8edf3;border-radius:14px;box-shadow:0 2px 9px rgba(15,23,42,.04)}.formation-table td{border:0;padding:5px 0}.formation-table td:not(.formation-name){display:grid;grid-template-columns:minmax(105px,36%) minmax(0,1fr);gap:10px;align-items:center}.formation-table td:nth-child(2)::before{content:"Tipo"}.formation-table td:nth-child(3)::before{content:"Carga horária"}.formation-table td:nth-child(4)::before{content:"Status"}.formation-table td::before{color:#64748b;font-size:12px;font-weight:700;text-transform:uppercase}.formation-name{font-size:16px;margin-bottom:6px}.formation-status{min-width:0}.formation-status .form-select{max-width:none;width:100%}}
</style></head><body><jsp:include page="includes/header.jsp"/><main class="container py-4"><div class="d-flex justify-content-between align-items-center mb-3"><a href="formacoes.jsp?pessoa=<%= pessoaFormacao %>" class="btn btn-link px-0"><i class="bi bi-arrow-left"></i> Voltar às formações</a><% if("ADM".equals(perfilFormacao)){ %><a href="formacao-admin.jsp" class="btn btn-outline-secondary"><i class="bi bi-gear"></i> Manutenção</a><% } %></div><section class="formation-hero mb-4"><div class="d-flex justify-content-between gap-3 flex-wrap"><div><span id="formacaoStatusPrograma" class="badge text-bg-success">Ativo</span><h1 id="formacaoPrograma" class="fw-bold mt-2 mb-1">Carregando...</h1><p id="formacaoPessoa" class="text-muted mb-0"></p></div><div class="text-end"><strong id="formacaoPercentual" class="display-5">0%</strong><div class="text-muted">obrigatórias concluídas</div></div></div><div class="formation-progress my-4"><div id="formacaoBarra" class="formation-progress-bar" style="width:0"></div></div><div class="row g-3"><div class="col-md-3"><div class="formation-stat"><span class="text-muted">Obrigatórias</span><strong id="formacaoObrigatorias">0</strong></div></div><div class="col-md-3"><div class="formation-stat"><span class="text-muted">Opcionais</span><strong id="formacaoOpcionais">0</strong></div></div><div class="col-md-3"><div class="formation-stat"><span class="text-muted">Concluídas obrigatórias</span><strong id="formacaoConcluidas" class="text-success">0</strong></div></div><div class="col-md-3"><div class="formation-stat"><span class="text-muted">Em andamento</span><strong id="formacaoAndamento" class="text-warning">0</strong></div></div></div></section><div class="row g-3 mb-3"><div class="col-md-7"><input id="pesquisaFormacao" class="form-control search-box" placeholder="Pesquisar disciplina..."></div><div class="col-md-5"><select id="filtroFormacaoStatus" class="form-select search-box"><option value="">Todos os status</option><option value="PENDENTE">Pendentes</option><option value="EM_ANDAMENTO">Em andamento</option><option value="CONCLUIDA">Concluídas</option></select></div></div><div id="formacaoItens">Carregando disciplinas...</div></main><jsp:include page="includes/footer.jsp"/><script>window.formacaoPessoaId=<%= pessoaFormacao %>;window.formacaoProgramaId=<%= programaFormacao %>;window.podeEditarFormacao=<%= podeEditarFormacao %>;</script><script src="js/formacao.js?v=3"></script></body></html>
