<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ include file="includes/auth.jsp" %>
<%@ include file="includes/access.jsp" %>
<!DOCTYPE html>
<html lang="pt-br"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Cadastro de grupos</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"><link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet"><link rel="stylesheet" href="css/style.css"><link rel="stylesheet" href="css/grupos.css?v=20260821-1"></head>
<body><jsp:include page="includes/header.jsp"/>
<main class="container-fluid px-lg-5 py-4">
 <div id="gruposAlerta" class="alert d-none" role="alert"></div>
 <div class="d-flex flex-wrap justify-content-between align-items-start gap-3 mb-4"><div><h1 class="fw-bold mb-1">Cadastro de grupos</h1><p class="text-muted mb-0">Configure os grupos, módulos e regras institucionais.</p></div><button type="button" class="btn btn-orange" id="novoGrupo"><i class="bi bi-plus-lg"></i> Novo grupo</button></div>
 <div class="groups-layout">
  <aside class="groups-panel groups-sidebar"><div class="groups-search"><div class="input-group"><span class="input-group-text bg-white border-end-0"><i class="bi bi-search"></i></span><input id="buscaGrupo" class="form-control border-start-0" placeholder="Buscar grupo"></div></div><div id="listaGrupos" class="groups-list"><div class="text-muted p-3">Carregando...</div></div></aside>
  <form id="grupoForm" class="groups-panel overflow-hidden">
   <div class="group-editor-head d-flex justify-content-between align-items-center gap-3"><div><h2 id="grupoTitulo" class="h5 fw-bold mb-1">Grupo</h2><small id="grupoSubtitulo" class="text-muted"></small></div><div class="form-check form-switch"><input id="statusGrupo" class="form-check-input" type="checkbox" checked><label for="statusGrupo" class="form-check-label fw-semibold">Ativo</label></div></div>
   <input type="hidden" id="grupoId">
   <ul class="nav nav-pills group-tabs"><li><button type="button" class="nav-link active" data-bs-toggle="pill" data-bs-target="#tabIdentificacao">Identificação</button></li><li><button type="button" class="nav-link" data-bs-toggle="pill" data-bs-target="#tabModulos">Módulos</button></li><li><button type="button" class="nav-link" data-bs-toggle="pill" data-bs-target="#tabContribuicao">Contribuição</button></li><li><button type="button" class="nav-link" data-bs-toggle="pill" data-bs-target="#tabPresenca">Presença</button></li><li><button type="button" class="nav-link" data-bs-toggle="pill" data-bs-target="#tabProgressao">Progressão</button></li><li><button type="button" class="nav-link" data-bs-toggle="pill" data-bs-target="#tabAcesso">Acesso</button></li></ul>
   <div class="tab-content">
    <section class="tab-pane fade show active group-tab" id="tabIdentificacao"><div class="group-section"><h3 class="group-section-title">Identificação</h3><p class="group-section-note">Nomes utilizados nos cadastros, filtros e relatórios.</p><div class="row g-3"><div class="col-md-6"><label class="form-label">Nome no singular *</label><input id="nomeSingular" class="form-control" required maxlength="100"></div><div class="col-md-6"><label class="form-label">Nome no plural *</label><input id="nomePlural" class="form-control" required maxlength="100"></div><div class="col-md-3"><label class="form-label">Sigla</label><input id="siglaGrupo" class="form-control" maxlength="10"></div><div class="col-md-3"><label class="form-label">Ordem</label><input id="ordemGrupo" class="form-control" type="number" min="1" required></div><div class="col-md-3"><label class="form-label">Cor</label><input id="corGrupo" class="form-control form-control-color w-100" type="color"></div><div class="col-md-3"><label class="form-label">Contexto</label><select id="contextoGrupo" class="form-select"><option value="CAD">CAD</option><option value="ESCOLA">Escola Diaconal</option><option value="OUTRO">Outro</option></select></div><div class="col-12"><label class="form-label">Descrição</label><textarea id="descricaoGrupo" class="form-control" rows="3" maxlength="1000"></textarea></div></div></div><div class="group-section"><h3 class="group-section-title">Comportamento</h3><p class="group-section-note">Diferencie grupos operacionais de categorias apenas institucionais.</p><div class="group-module-grid"><label class="group-option"><span class="group-option-icon"><i class="bi bi-person-vcard"></i></span><span class="group-option-copy"><strong>Grupo operacional</strong><small>Participa da gestão de membros e atividades.</small></span><input id="grupoOperacional" class="form-check-input" type="checkbox"></label><label class="group-option"><span class="group-option-icon"><i class="bi bi-person-lock"></i></span><span class="group-option-copy"><strong>Disponível para usuários</strong><small>Permite contas de acesso vinculadas ao grupo.</small></span><input id="disponivelUsuarios" class="form-check-input" type="checkbox"></label></div></div></section>
    <section class="tab-pane fade group-tab" id="tabModulos"><h3 class="group-section-title">Módulos habilitados</h3><p class="group-section-note">O grupo será oferecido nos módulos selecionados.</p><div id="modulosGrupo" class="group-module-grid"></div></section>
    <section class="tab-pane fade group-tab" id="tabContribuicao"><div class="d-flex justify-content-between gap-3 mb-4"><div><h3 class="group-section-title">Regra de contribuição</h3><p class="group-section-note mb-0">Valor e calendário esperados para o grupo.</p></div><div class="form-check form-switch"><input id="contribuicaoAtiva" class="form-check-input" type="checkbox"><label class="form-check-label fw-semibold">Controlar</label></div></div><fieldset id="camposContribuicao"><div class="row g-3"><div class="col-md-4"><label class="form-label">Valor padrão</label><div class="input-group"><span class="input-group-text">R$</span><input id="contribuicaoValor" class="form-control" inputmode="decimal"></div></div><div class="col-md-5"><label class="form-label">Competências esperadas</label><select id="contribuicaoPeriodicidade" class="form-select"><option value="MENSAL">Todos os meses decorridos</option><option value="ENCONTRO">Somente meses com encontro</option><option value="MANUAL">Definidas manualmente</option><option value="NENHUMA">Não calcular expectativa</option></select></div><div class="col-md-3"><label class="form-label">Dia do vencimento</label><input id="contribuicaoDia" class="form-control" type="number" min="1" max="28"></div><div class="col-md-6 form-check"><input id="contribuicaoEditavel" class="form-check-input" type="checkbox"><label class="form-check-label">Permitir alterar o valor no lançamento</label></div><div class="col-md-6 form-check"><input id="contribuicaoAteAtual" class="form-check-input" type="checkbox"><label class="form-check-label">Considerar somente até o mês atual</label></div></div><div id="previaContribuicao" class="group-preview mt-4"></div></fieldset></section>
    <section class="tab-pane fade group-tab" id="tabPresenca"><div class="d-flex justify-content-between gap-3 mb-4"><div><h3 class="group-section-title">Presença e indicadores</h3><p class="group-section-note mb-0">Forma de cálculo da participação.</p></div><div class="form-check form-switch"><input id="presencaAtiva" class="form-check-input" type="checkbox"><label class="form-check-label fw-semibold">Controlar</label></div></div><fieldset id="camposPresenca"><div class="row g-3"><div class="col-md-5"><label class="form-label">Participações esperadas</label><select id="presencaFonte" class="form-select"><option value="ENCONTROS">Encontros cadastrados</option><option value="MENSAL">Uma por mês</option><option value="FIXA">Quantidade anual fixa</option><option value="NAO">Não calcular percentual</option></select></div><div class="col-md-3"><label class="form-label">Quantidade anual</label><input id="presencaQuantidade" class="form-control" type="number" min="1"></div><div class="col-md-2"><label class="form-label">Meta mínima (%)</label><input id="presencaMeta" class="form-control" type="number" min="0" max="100"></div><div class="col-md-6 form-check"><input id="presencaJustificada" class="form-check-input" type="checkbox"><label class="form-check-label">Justificada cumpre a meta</label></div><div class="col-md-6 form-check"><input id="permiteEsposas" class="form-check-input" type="checkbox"><label class="form-check-label">Disponibilizar participação de esposas</label></div></div></fieldset></section>
    <section class="tab-pane fade group-tab" id="tabProgressao"><div class="d-flex justify-content-between align-items-start gap-3 mb-3"><div><h3 class="group-section-title">Transições de saída</h3><p class="group-section-note">Ações que movimentam o membro para outro grupo.</p></div><button id="adicionarTransicao" type="button" class="btn btn-outline-secondary"><i class="bi bi-plus-lg"></i> Adicionar</button></div><div id="transicoesGrupo"></div><div class="group-section"><h3 class="group-section-title">Acompanhamento ministerial</h3><p class="group-section-note">Indicadores aplicáveis aos membros do grupo.</p><div id="ministerialGrupo" class="row g-2"></div></div></section>
    <section class="tab-pane fade group-tab" id="tabAcesso"><h3 class="group-section-title">Escopo do representante</h3><p class="group-section-note">Defina o alcance do perfil REP em cada módulo.</p><div class="row g-3"><div class="col-md-6"><label class="form-label">Membros</label><select id="escopoMembros" class="form-select escopo"></select></div><div class="col-md-6"><label class="form-label">Encontros</label><select id="escopoEncontros" class="form-select escopo"></select></div><div class="col-md-6"><label class="form-label">Contribuições</label><select id="escopoContribuicoes" class="form-select escopo"></select></div><div class="col-md-6"><label class="form-label">Relatórios</label><select id="escopoRelatorios" class="form-select escopo"></select></div></div><div class="alert alert-success mt-4 mb-0"><i class="bi bi-check-circle me-1"></i> Os escopos configurados já estão ativos nos módulos de Membros, Encontros, Contribuições e Relatórios.</div></section>
   </div>
   <div class="group-actions d-flex justify-content-between align-items-center gap-3"><small class="text-muted">Grupos utilizados não são excluídos; devem ser inativados.</small><div class="d-flex gap-2"><button id="descartarGrupo" type="button" class="btn btn-light">Descartar</button><button type="submit" class="btn btn-orange"><i class="bi bi-check-lg"></i> Salvar grupo</button></div></div>
  </form>
 </div>
</main><jsp:include page="includes/footer.jsp"/><script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script><script src="js/grupos.js?v=20260821-2"></script></body></html>
