<%@ page import="java.sql.*" %><%@ page contentType="application/json; charset=UTF-8" pageEncoding="UTF-8" %>
<%!
private String jmc(String s){return s==null?"":s.replace("\\","\\\\").replace("\"","\\\"").replace("\r","\\r").replace("\n","\\n");}
private int imc(String s,int d){try{return Integer.parseInt(s);}catch(Exception e){return d;}}
private boolean podeVerPessoa(Connection c,String perfil,Integer usuario,Integer grupo,Integer regiao,int pessoa)throws SQLException{
 if(usuario==null)return false;if(usuario==pessoa||"ADM".equals(perfil)||"EXT".equals(perfil))return true;if(!"REP".equals(perfil)||grupo==null)return false;
 try(PreparedStatement p=c.prepareStatement("SELECT p.Classe,IFNULL(pa.IdRegiao,0),g.EscopoRepMembros FROM pessoas p LEFT JOIN paroquia pa ON pa.IdParoquia=p.IdParoquia JOIN grupos g ON g.IdGrupo=? WHERE p.IdPessoa=?")){p.setInt(1,grupo);p.setInt(2,pessoa);try(ResultSet r=p.executeQuery()){if(!r.next())return false;String e=r.getString(3);return "TODOS".equals(e)||("PROPRIO".equals(e)&&r.getInt(1)==grupo)||("REGIAO_TODOS".equals(e)&&regiao!=null&&r.getInt(2)==regiao);}}
}
%><%
String perfil=(String)session.getAttribute("usuarioPerfil"),acao=request.getParameter("acao");Integer usuario=(Integer)session.getAttribute("usuarioId"),grupo=(Integer)session.getAttribute("usuarioGrupoId"),regiao=(Integer)session.getAttribute("usuarioRegiaoId");
if(usuario==null){response.setStatus(401);out.print("{\"ok\":false,\"mensagem\":\"Sessão inválida.\"}");return;}response.setHeader("Cache-Control","no-store");
try(Connection c=cad.db.Database.getConnection()){
 if("listar".equals(acao)){
  if(!("ADM".equals(perfil)||"REP".equals(perfil)||"EXT".equals(perfil))){response.setStatus(403);out.print("{\"ok\":false,\"mensagem\":\"Acesso não autorizado.\"}");return;}
  int status=imc(request.getParameter("status"),1);String escopo="TODOS";if("REP".equals(perfil)){escopo="NENHUM";if(grupo!=null)try(PreparedStatement p=c.prepareStatement("SELECT EscopoRepMembros FROM grupos WHERE IdGrupo=?")){p.setInt(1,grupo);try(ResultSet r=p.executeQuery()){if(r.next())escopo=r.getString(1);}}}
  String restricao="REP".equals(perfil)?"NENHUM".equals(escopo)?" AND 1=0":"PROPRIO".equals(escopo)?" AND sp.Classe=?":"REGIAO_TODOS".equals(escopo)?" AND sp.IdRegiao=?":"":"";
  String sql="SELECT sp.IdPessoa,sp.Nome,g.NomeSingular Grupo,IFNULL(sp.Paroquia,'') Paroquia,IFNULL(pa.Bairro,'') Bairro,IFNULL(sp.Regiao,'') Regiao,IFNULL(sp.Fone1,'') Telefone FROM sqlPessoas sp JOIN grupos g ON g.IdGrupo=sp.Classe AND g.StatusGrupo='ATIVO' AND g.GrupoOperacional=1 AND g.ModuloMembros=1 LEFT JOIN paroquia pa ON pa.IdParoquia=sp.IdParoquia WHERE sp.Status=?"+restricao+" ORDER BY sp.Nome";
  StringBuilder b=new StringBuilder("{\"ok\":true,\"membros\":[");boolean f=true;try(PreparedStatement p=c.prepareStatement(sql)){int i=1;p.setInt(i++,status);if("REP".equals(perfil)&&"PROPRIO".equals(escopo))p.setInt(i++,grupo==null?-1:grupo);else if("REP".equals(perfil)&&"REGIAO_TODOS".equals(escopo))p.setInt(i++,regiao==null?-1:regiao);try(ResultSet r=p.executeQuery()){while(r.next()){if(!f)b.append(',');f=false;b.append("{\"id\":").append(r.getInt(1)).append(",\"nome\":\"").append(jmc(r.getString(2))).append("\",\"grupo\":\"").append(jmc(r.getString(3))).append("\",\"paroquia\":\"").append(jmc(r.getString(4))).append("\",\"bairro\":\"").append(jmc(r.getString(5))).append("\",\"regiao\":\"").append(jmc(r.getString(6))).append("\",\"telefone\":\"").append(jmc(r.getString(7))).append("\"}");}}}out.print(b.append("]}"));return;
 }
 if("perfil".equals(acao)){
  int pessoa=imc(request.getParameter("pessoa"),usuario);if(!podeVerPessoa(c,perfil,usuario,grupo,regiao,pessoa)){response.setStatus(403);out.print("{\"ok\":false,\"mensagem\":\"Membro fora do escopo de acesso.\"}");return;}
  String sql="SELECT s.*,g.NomeSingular GrupoDinamico,IFNULL(pa.Bairro,'') BairroDinamico FROM sqlPessoas s JOIN grupos g ON g.IdGrupo=s.Classe LEFT JOIN paroquia pa ON pa.IdParoquia=s.IdParoquia WHERE s.IdPessoa=?";
  try(PreparedStatement p=c.prepareStatement(sql)){p.setInt(1,pessoa);try(ResultSet r=p.executeQuery()){if(!r.next()){response.setStatus(404);out.print("{\"ok\":false,\"mensagem\":\"Membro não encontrado.\"}");return;}String[] campos={"IdPessoa","Nome","Matricula","tpMatricula","Fone1","Fone2","Email","DtNascimento","Profissao","Pastoral","NomeEsposa","FoneEsposa","DtNascEsposa","DtCasamento","ProfissaoEsposa","IdParoquia","Paroquia","Regiao","Turma","DtOrdenacao","DtProvisao","BispoOrdenante","Transferido","DioceseTransf","Status","flgTeologia","flgSeminarioLeitor","flgSeminarioAcolito","flgLeitor","flgAcolito","flgOrdemSacra","Obs","Idade"};StringBuilder b=new StringBuilder("{\"ok\":true,\"perfil\":{");boolean f=true;for(String campo:campos){if(!f)b.append(',');f=false;b.append('\"').append(campo).append("\":\"").append(jmc(r.getString(campo))).append('\"');}b.append(",\"status\":\"").append(jmc(r.getString("Status"))).append("\",\"DescClasse\":\"").append(jmc(r.getString("GrupoDinamico"))).append("\",\"Bairro\":\"").append(jmc(r.getString("BairroDinamico"))).append("\"}}");out.print(b);return;}}
 }
 if("presencas".equals(acao)){
  int pessoa=imc(request.getParameter("pessoa"),usuario);if(!podeVerPessoa(c,perfil,usuario,grupo,regiao,pessoa)){response.setStatus(403);out.print("{\"ok\":false,\"mensagem\":\"Membro fora do escopo de acesso.\"}");return;}
  StringBuilder b=new StringBuilder("{\"ok\":true,\"presencas\":[");boolean f=true;String sql="SELECT e.IdEncontro,DATE_FORMAT(e.DtEncontro,'%d/%m/%Y') Data,IFNULL(e.Descricao,'') Descricao,CASE pe.flgPresenca WHEN 1 THEN 'Presente' WHEN 2 THEN 'Justificado' ELSE 'Faltou' END Presenca,IFNULL(pe.Justificativa,'') Justificativa FROM Encontros e JOIN participanteEncontro pe ON pe.IdEncontro=e.IdEncontro WHERE pe.IdPessoa=? ORDER BY e.DtEncontro DESC";try(PreparedStatement p=c.prepareStatement(sql)){p.setInt(1,pessoa);try(ResultSet r=p.executeQuery()){while(r.next()){if(!f)b.append(',');f=false;b.append("{\"idEncontro\":").append(r.getInt(1)).append(",\"data\":\"").append(jmc(r.getString(2))).append("\",\"descricao\":\"").append(jmc(r.getString(3))).append("\",\"presenca\":\"").append(jmc(r.getString(4))).append("\",\"justificativa\":\"").append(jmc(r.getString(5))).append("\"}");}}}out.print(b.append("]}"));return;
 }
 if("paroquias".equals(acao)){
  StringBuilder b=new StringBuilder("{\"ok\":true,\"paroquias\":[");boolean f=true;try(PreparedStatement p=c.prepareStatement("SELECT IdParoquia,Descricao,IFNULL(Bairro,''),IFNULL(Regiao,'') FROM paroquia WHERE Descricao IS NOT NULL AND Descricao<>'' ORDER BY Descricao");ResultSet r=p.executeQuery()){while(r.next()){if(!f)b.append(',');f=false;b.append("{\"id\":").append(r.getInt(1)).append(",\"nome\":\"").append(jmc(r.getString(2))).append("\",\"bairro\":\"").append(jmc(r.getString(3))).append("\",\"regiao\":\"").append(jmc(r.getString(4))).append("\"}");}}out.print(b.append("]}"));return;
 }
 response.setStatus(400);out.print("{\"ok\":false,\"mensagem\":\"Ação inválida.\"}");
}catch(Exception e){e.printStackTrace();response.setStatus(500);out.print("{\"ok\":false,\"mensagem\":\"Não foi possível carregar os dados.\"}");}
%>
