<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ include file="includes/auth.jsp" %>
<%
String perfilParticipantes=(String)session.getAttribute("usuarioPerfil");
if(!"ADM".equals(perfilParticipantes)&&!"REP".equals(perfilParticipantes)&&!"EXT".equals(perfilParticipantes)){response.sendRedirect("encontros.jsp");return;}
%>
<!DOCTYPE html><html lang="pt-br"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Participantes do Encontro</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"><link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet"><link rel="stylesheet" href="css/style.css"><style>@media print {.navbar,.no-print,th:last-child,td:last-child{display:none!important}.container{max-width:100%!important;padding:0!important}}</style></head><body>
<jsp:include page="includes/header.jsp"/><div class="container py-4"><div class="d-flex justify-content-between align-items-center no-print"><a href="encontros.jsp" class="btn btn-link px-0"><i class="bi bi-arrow-left"></i> Voltar para encontros</a><button type="button" class="btn btn-outline-secondary" onclick="window.print()"><i class="bi bi-printer"></i> Imprimir lista</button></div><h1 id="tituloEncontro" class="fw-bold">Participantes</h1><p id="subtituloEncontro" class="text-muted"></p><div id="resumoPresencas" class="row g-3 mb-4"></div><div class="profile-card mb-4 no-print"><div class="row g-3 align-items-end"><div class="col-md-7"><label for="filtroNomeParticipante" class="form-label fw-semibold">Pesquisar participante</label><div class="input-group"><span class="input-group-text bg-white"><i class="bi bi-search"></i></span><input type="search" id="filtroNomeParticipante" class="form-control" placeholder="Digite o nome do participante..." autocomplete="off"></div></div><div class="col-md-5"><label for="filtroStatusPresenca" class="form-label fw-semibold">Status de presença</label><select id="filtroStatusPresenca" class="form-select"><option value="">Todos os status</option><option value="Presente">Presentes</option><option value="Faltou">Faltosos</option><option value="Justificado">Justificados</option></select></div></div></div><div class="d-flex justify-content-between align-items-center mb-2"><span id="participantesFiltradosInfo" class="text-muted small"></span></div><div class="table-responsive"><table class="table table-striped"><thead><tr><th>Participante</th><th>Presença</th><th>Justificativa</th><% if("ADM".equals(perfilParticipantes)){ %><th>Ações</th><% } %></tr></thead><tbody id="participantesBody"><tr><td colspan="4">Carregando...</td></tr></tbody></table></div></div>
<script>window.idEncontro=new URLSearchParams(location.search).get("id");window.podeEditarPresenca=<%= "ADM".equals(perfilParticipantes) %>;</script><script src="js/participantes-encontro.js?v=3"></script><style>@media print {th:nth-child(3),td:nth-child(3){display:table-cell!important}}</style></body></html>
