<%@ page import="java.sql.*,java.util.*" %>
<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ include file="includes/auth.jsp" %>
<%@ include file="includes/escopoRelatorios.jspf" %>
<%!
private String hlr(String v){return v==null?"":v.replace("&","&amp;").replace("<","&lt;").replace(">","&gt;").replace("\"","&quot;").replace("'","&#39;");}
private int ilr(String v,int d){try{return Integer.parseInt(v);}catch(Exception e){return d;}}
private String glr(int c){return c==0?"Todos os grupos":cad.grupos.GrupoCatalogo.plural(c);}
%>
<%
String perfilLr=(String)session.getAttribute("usuarioPerfil");if(!"ADM".equals(perfilLr)&&!"REP".equals(perfilLr)&&!"EXT".equals(perfilLr)){response.sendRedirect("index.jsp");return;}
boolean repLr="REP".equals(perfilLr);Integer regiaoSessaoLr=(Integer)session.getAttribute("usuarioRegiaoId");
String escopoLr=cadEscopoRelatorios(session);Integer grupoSessaoLr=(Integer)session.getAttribute("usuarioGrupoId");boolean restringeRegiaoLr=repLr&&"REGIAO_TODOS".equals(escopoLr);
int classeLr=ilr(request.getParameter("classe"),0);if(classeLr<0)classeLr=0;int regiaoLr=ilr(request.getParameter("regiao"),0);if(repLr&&"PROPRIO".equals(escopoLr))classeLr=grupoSessaoLr==null?-1:grupoSessaoLr;else if(restringeRegiaoLr)regiaoLr=regiaoSessaoLr==null?-1:regiaoSessaoLr;else if(repLr&&"NENHUM".equals(escopoLr))classeLr=-1;
String nomeLr=request.getParameter("nome");if(nomeLr==null)nomeLr="";nomeLr=nomeLr.trim();
class MembroLr{int id,idade;String nome,nascimento;}
class ParoquiaLr{int id;String nome,bairro,cidade;List<MembroLr> membros=new ArrayList<MembroLr>();}
class RegiaoLr{int id;String nome;LinkedHashMap<Integer,ParoquiaLr> paroquias=new LinkedHashMap<Integer,ParoquiaLr>();int total=0;}
LinkedHashMap<Integer,String> opcoesRegiaoLr=new LinkedHashMap<Integer,String>();LinkedHashMap<Integer,RegiaoLr> dadosLr=new LinkedHashMap<Integer,RegiaoLr>();String erroLr=null,nomeRegiaoLr="";int totalLr=0,totalParoquiasLr=0;
try{
 try(Connection c=cad.db.Database.getConnection()){
  try(PreparedStatement p=c.prepareStatement("SELECT DISTINCT IdRegiao,Regiao FROM paroquia WHERE IdRegiao IS NOT NULL AND Regiao IS NOT NULL AND Regiao<>'' ORDER BY Regiao");ResultSet r=p.executeQuery()){while(r.next()){int id=r.getInt(1);String nome=r.getString(2);if(!restringeRegiaoLr||id==regiaoLr)opcoesRegiaoLr.put(id,nome);if(id==regiaoLr)nomeRegiaoLr=nome;}}
  String sql="SELECT pa.IdRegiao,IFNULL(pa.Regiao,'') Regiao,pa.IdParoquia,IFNULL(pa.Descricao,'') Paroquia,IFNULL(pa.Cidade,'') Cidade,IFNULL(pa.Bairro,'') Bairro,p.IdPessoa,p.Nome,DATE_FORMAT(p.DtNascimento,'%d/%m/%Y') DtNascimento,TIMESTAMPDIFF(YEAR,p.DtNascimento,CURDATE()) Idade FROM pessoas p JOIN grupos g ON g.IdGrupo=p.Classe AND g.StatusGrupo='ATIVO' AND g.GrupoOperacional=1 AND g.ModuloRelatorios=1 JOIN paroquia pa ON pa.IdParoquia=p.IdParoquia WHERE p.Status=1 AND (?=0 OR p.Classe=?) AND (?=0 OR pa.IdRegiao=?) AND (?='' OR p.Nome LIKE CONCAT('%',?,'%')) ORDER BY pa.Regiao,pa.Descricao,p.Nome";
  try(PreparedStatement p=c.prepareStatement(sql)){p.setInt(1,classeLr);p.setInt(2,classeLr);p.setInt(3,regiaoLr);p.setInt(4,regiaoLr);p.setString(5,nomeLr);p.setString(6,nomeLr);try(ResultSet r=p.executeQuery()){while(r.next()){int idRegiao=r.getInt("IdRegiao"),idParoquia=r.getInt("IdParoquia");RegiaoLr regiao=dadosLr.get(idRegiao);if(regiao==null){regiao=new RegiaoLr();regiao.id=idRegiao;regiao.nome=r.getString("Regiao");dadosLr.put(idRegiao,regiao);}ParoquiaLr paroquia=regiao.paroquias.get(idParoquia);if(paroquia==null){paroquia=new ParoquiaLr();paroquia.id=idParoquia;paroquia.nome=r.getString("Paroquia");paroquia.bairro=r.getString("Bairro");paroquia.cidade=r.getString("Cidade");regiao.paroquias.put(idParoquia,paroquia);totalParoquiasLr++;}MembroLr membro=new MembroLr();membro.id=r.getInt("IdPessoa");membro.nome=r.getString("Nome");membro.nascimento=r.getString("DtNascimento");membro.idade=r.getInt("Idade");paroquia.membros.add(membro);regiao.total++;totalLr++;}}}
 }
}catch(Exception erro){erro.printStackTrace();erroLr="Não foi possível carregar a listagem por região.";}
%>
<!DOCTYPE html><html lang="pt-br"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Listagem por Região</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"><link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet"><link rel="stylesheet" href="css/style.css"><style>
.lr-filter{background:#fff;border:1px solid #e8edf3;border-radius:16px;padding:20px}.lr-region-card{background:#fff;border:1px solid #e4eaf1;border-radius:16px;overflow:hidden;margin-bottom:18px}.lr-region-header{padding:16px 20px;background:linear-gradient(90deg,#fff8f1,#fff);border-bottom:1px solid #e8edf3}.lr-parish{padding:18px 20px;border-bottom:1px solid #e8edf3}.lr-parish:last-child{border-bottom:0}.lr-parish-title{font-weight:700}.lr-table th{font-size:11px;text-transform:uppercase;color:#64748b}.lr-summary-region{background:#fff;border:1px solid #e8edf3;border-radius:13px;padding:14px 16px}.lr-summary-count{color:#a85108;background:#fff1e6;border-radius:9px;padding:5px 10px;font-weight:700}.lr-print-title{display:none}
@media print{@page{size:A4;margin:11mm}.navbar,footer,.no-print{display:none!important}body{background:#fff!important}.container{max-width:none!important;padding:0!important}.dashboard-card,.lr-region-card,.lr-summary-region{box-shadow:none!important}.lr-region-card{break-inside:avoid;margin-bottom:10px}.lr-region-header{padding:8px 11px}.lr-parish{padding:8px 11px;break-inside:avoid}.lr-table{font-size:9pt}.lr-table th,.lr-table td{padding:4px 6px}body.print-list-only .lr-main-summary,body.print-list-only .lr-region-summary{display:none!important}.lr-print-title{display:block}}
</style></head><body><jsp:include page="includes/header.jsp"/><main class="container py-4">
<div class="d-flex justify-content-between align-items-start gap-3 flex-wrap mb-4"><div><a href="relatorios.jsp" class="btn btn-link px-0 no-print"><i class="bi bi-arrow-left"></i> Voltar aos relatórios</a><h1 class="fw-bold mb-1">Listagem por Região</h1><p class="text-muted mb-0">Membros ativos · <%= hlr(glr(classeLr)) %><%= regiaoLr!=0?" · "+hlr(nomeRegiaoLr):"" %></p></div><div class="d-flex gap-2 no-print"><button class="btn btn-outline-secondary" onclick="imprimirLr(false)"><i class="bi bi-printer"></i> Relatório completo</button><button class="btn btn-orange" onclick="imprimirLr(true)"><i class="bi bi-list-ul"></i> Somente listagem</button></div></div>
<form method="get" class="lr-filter mb-4 no-print"><div class="row g-3 align-items-end"><div class="col-md-3"><label class="form-label">Grupo</label><select name="classe" class="form-select"><option value="0" <%= classeLr==0?"selected":"" %>>Todos</option><option value="1" <%= classeLr==1?"selected":"" %>>Diáconos</option><option value="2" <%= classeLr==2?"selected":"" %>>Candidatos</option><option value="3" <%= classeLr==3?"selected":"" %>>Vocacionados</option></select></div><div class="col-md-3"><label class="form-label">Região episcopal</label><% if(repLr){ %><input class="form-control" value="<%= hlr(nomeRegiaoLr.isEmpty()?"Região não identificada":nomeRegiaoLr) %>" disabled><% }else{ %><select name="regiao" class="form-select"><option value="0">Todas as regiões</option><% for(Map.Entry<Integer,String> x:opcoesRegiaoLr.entrySet()){ %><option value="<%= x.getKey() %>" <%= x.getKey()==regiaoLr?"selected":"" %>><%= hlr(x.getValue()) %></option><% } %></select><% } %></div><div class="col-md-4"><label class="form-label">Nome</label><input name="nome" value="<%= hlr(nomeLr) %>" class="form-control" placeholder="Pesquisar membro"></div><div class="col-md-2"><button class="btn btn-orange w-100"><i class="bi bi-funnel"></i> Aplicar</button></div></div></form>
<% if(erroLr!=null){ %><div class="alert alert-danger"><%= hlr(erroLr) %></div><% } %>
<div class="row g-3 mb-4 lr-main-summary"><div class="col-md-3"><div class="dashboard-card"><h5>Membros</h5><div class="card-number"><%= totalLr %></div></div></div><div class="col-md-3"><div class="dashboard-card"><h5>Regiões</h5><div class="card-number"><%= dadosLr.size() %></div></div></div><div class="col-md-3"><div class="dashboard-card"><h5>Paróquias</h5><div class="card-number"><%= totalParoquiasLr %></div></div></div><div class="col-md-3"><div class="dashboard-card"><h5>Grupo</h5><span class="badge-tag <%= classeLr==0?"":classeLr==1?"tag-green":classeLr==2?"tag-yellow":"tag-blue" %>"><%= hlr(glr(classeLr)) %></span></div></div></div>
<% if(!dadosLr.isEmpty()){ %><section class="mb-4 lr-region-summary"><h4 class="mb-3">Resumo por região</h4><div class="row g-3"><% for(RegiaoLr regiao:dadosLr.values()){ %><div class="col-md-4"><div class="lr-summary-region d-flex justify-content-between align-items-center"><div><strong><%= hlr(regiao.nome) %></strong><small class="d-block text-muted"><%= regiao.paroquias.size() %> paróquia(s)</small></div><span class="lr-summary-count"><%= regiao.total %></span></div></div><% } %></div></section><% } %>
<h2 class="lr-print-title fs-5 mb-3"><%= hlr(glr(classeLr)) %><%= regiaoLr!=0?" · "+hlr(nomeRegiaoLr):"" %></h2>
<div class="d-flex justify-content-between align-items-center mb-3"><h4 class="mb-0">Membros por região e paróquia</h4><span class="text-muted"><%= totalLr %> registro(s)</span></div>
<% if(dadosLr.isEmpty()){ %><div class="profile-card text-center text-muted py-5"><i class="bi bi-search fs-1 d-block mb-2"></i>Nenhum membro encontrado para os filtros selecionados.</div><% }else{for(RegiaoLr regiao:dadosLr.values()){ %><section class="lr-region-card"><div class="lr-region-header d-flex justify-content-between align-items-center"><h4 class="mb-0"><i class="bi bi-geo-alt-fill text-warning"></i> <%= hlr(regiao.nome) %></h4><span class="badge rounded-pill text-bg-light"><%= regiao.total %> membros</span></div><% for(ParoquiaLr paroquia:regiao.paroquias.values()){ %><div class="lr-parish"><div class="d-flex justify-content-between align-items-start gap-3 mb-2"><div><div class="lr-parish-title"><%= hlr(paroquia.nome) %></div><small class="text-muted"><%= hlr(paroquia.bairro) %><%= !paroquia.bairro.isEmpty()&&!paroquia.cidade.isEmpty()?" · ":"" %><%= hlr(paroquia.cidade) %></small></div><small class="text-muted"><%= paroquia.membros.size() %> membro(s)</small></div><div class="table-responsive"><table class="table table-sm table-hover lr-table mb-0"><thead><tr><th style="width:45px">#</th><th>Nome</th><th style="width:145px">Nascimento</th><th style="width:90px">Idade</th></tr></thead><tbody><% int ordem=0;for(MembroLr membro:paroquia.membros){ordem++; %><tr><td class="text-muted"><%= ordem %></td><td><strong><%= hlr(membro.nome) %></strong></td><td><%= membro.nascimento==null?"—":hlr(membro.nascimento) %></td><td><%= membro.nascimento==null?"—":membro.idade+" anos" %></td></tr><% } %></tbody></table></div></div><% } %></section><% }} %>
</main><jsp:include page="includes/footer.jsp"/><script>function imprimirLr(somenteLista){document.body.classList.toggle("print-list-only",somenteLista);window.print()}window.addEventListener("afterprint",()=>document.body.classList.remove("print-list-only"));</script></body></html>
