<%@ page import="java.sql.*,java.util.*,java.time.*" %>
<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ include file="includes/auth.jsp" %>
<%@ include file="includes/escopoRelatorios.jspf" %>
<%!
private String han(String v){return v==null?"":v.replace("&","&amp;").replace("<","&lt;").replace(">","&gt;").replace("\"","&quot;").replace("'","&#39;");}
private int ian(String v,int d){try{return Integer.parseInt(v);}catch(Exception e){return d;}}
private String gan(int c){return c==0?"Todos os grupos":cad.grupos.GrupoCatalogo.plural(c);}
private String man(int m){String[] n={"","Janeiro","Fevereiro","Março","Abril","Maio","Junho","Julho","Agosto","Setembro","Outubro","Novembro","Dezembro"};return m>=1&&m<=12?n[m]:"Todos os meses";}
%>
<%
String perfilAn=(String)session.getAttribute("usuarioPerfil");if(!"ADM".equals(perfilAn)&&!"REP".equals(perfilAn)&&!"EXT".equals(perfilAn)){response.sendRedirect("index.jsp");return;}
boolean repAn="REP".equals(perfilAn);Integer regiaoSessaoAn=(Integer)session.getAttribute("usuarioRegiaoId");
String escopoAn=cadEscopoRelatorios(session);Integer grupoSessaoAn=(Integer)session.getAttribute("usuarioGrupoId");boolean restringeRegiaoAn=repAn&&"REGIAO_TODOS".equals(escopoAn);
int classeAn=ian(request.getParameter("classe"),0);if(classeAn<0)classeAn=0;int mesAn=ian(request.getParameter("mes"),LocalDate.now().getMonthValue());if(mesAn<0||mesAn>12)mesAn=0;int regiaoAn=ian(request.getParameter("regiao"),0);if(repAn&&"PROPRIO".equals(escopoAn))classeAn=grupoSessaoAn==null?-1:grupoSessaoAn;else if(restringeRegiaoAn)regiaoAn=regiaoSessaoAn==null?-1:regiaoSessaoAn;else if(repAn&&"NENHUM".equals(escopoAn))classeAn=-1;
String tipoAn=request.getParameter("tipo");if(!"NASCIMENTO".equals(tipoAn)&&!"ESPOSA".equals(tipoAn)&&!"CASAMENTO".equals(tipoAn)&&!"ORDENACAO".equals(tipoAn))tipoAn="";
class EventoAn{int classe,idade;String membro,esposa,paroquia,regiao,tipo,data;LocalDate dataOriginal;}
List<EventoAn> eventosAn=new ArrayList<EventoAn>();LinkedHashMap<Integer,String> regioesAn=new LinkedHashMap<Integer,String>();String nomeRegiaoAn="",erroAn=null;int nascimentosAn=0,esposasAn=0,casamentosAn=0,ordenacoesAn=0;
try{
 try(Connection c=cad.db.Database.getConnection()){
  try(PreparedStatement p=c.prepareStatement("SELECT DISTINCT IdRegiao,Regiao FROM paroquia WHERE IdRegiao IS NOT NULL AND Regiao IS NOT NULL AND Regiao<>'' ORDER BY Regiao");ResultSet r=p.executeQuery()){while(r.next()){int id=r.getInt(1);String nome=r.getString(2);if(!restringeRegiaoAn||id==regiaoAn)regioesAn.put(id,nome);if(id==regiaoAn)nomeRegiaoAn=nome;}}
  String sql="SELECT p.Classe,p.Nome,IFNULL(p.NomeEsposa,'') NomeEsposa,p.DtNascimento,p.DtNascEsposa,p.DtCasamento,p.DtOrdenacao,IFNULL(pa.Descricao,'') Paroquia,IFNULL(pa.Regiao,'') Regiao FROM pessoas p JOIN grupos g ON g.IdGrupo=p.Classe AND g.StatusGrupo='ATIVO' AND g.GrupoOperacional=1 AND g.ModuloRelatorios=1 LEFT JOIN paroquia pa ON pa.IdParoquia=p.IdParoquia WHERE p.Status=1 AND (?=0 OR p.Classe=?) AND (?=0 OR IFNULL(pa.IdRegiao,0)=?) ORDER BY p.Nome";
  try(PreparedStatement p=c.prepareStatement(sql)){p.setInt(1,classeAn);p.setInt(2,classeAn);p.setInt(3,regiaoAn);p.setInt(4,regiaoAn);try(ResultSet r=p.executeQuery()){while(r.next()){int classe=r.getInt("Classe");String membro=r.getString("Nome"),esposa=r.getString("NomeEsposa"),paroquia=r.getString("Paroquia"),regiao=r.getString("Regiao");java.sql.Date[] datas={r.getDate("DtNascimento"),r.getDate("DtNascEsposa"),r.getDate("DtCasamento"),r.getDate("DtOrdenacao")};String[] tipos={"NASCIMENTO","ESPOSA","CASAMENTO","ORDENACAO"};for(int x=0;x<4;x++){if(datas[x]==null||(!tipoAn.isEmpty()&&!tipoAn.equals(tipos[x])))continue;LocalDate data=datas[x].toLocalDate();if(mesAn!=0&&data.getMonthValue()!=mesAn)continue;EventoAn e=new EventoAn();e.classe=classe;e.membro=membro;e.esposa=esposa;e.paroquia=paroquia;e.regiao=regiao;e.tipo=tipos[x];e.dataOriginal=data;e.data=data.format(java.time.format.DateTimeFormatter.ofPattern("dd/MM/yyyy"));e.idade=Math.max(0,LocalDate.now().getYear()-data.getYear());eventosAn.add(e);if(x==0)nascimentosAn++;else if(x==1)esposasAn++;else if(x==2)casamentosAn++;else ordenacoesAn++;}}}}
  Collections.sort(eventosAn,new Comparator<EventoAn>(){public int compare(EventoAn a,EventoAn b){int c=Integer.compare(a.dataOriginal.getMonthValue(),b.dataOriginal.getMonthValue());if(c==0)c=Integer.compare(a.dataOriginal.getDayOfMonth(),b.dataOriginal.getDayOfMonth());if(c==0)c=a.membro.compareToIgnoreCase(b.membro);return c;}});
 }
}catch(Exception erro){erro.printStackTrace();erroAn="Não foi possível carregar o relatório de aniversários.";}
%>
<!DOCTYPE html><html lang="pt-br"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Aniversários e Datas Comemorativas</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"><link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet"><link rel="stylesheet" href="css/style.css"><style>
.an-filter{background:#fff;border:1px solid #e8edf3;border-radius:16px;padding:20px}.an-table th{font-size:11px;text-transform:uppercase;color:#64748b}.an-table td{vertical-align:middle}.an-date{white-space:nowrap;font-weight:700}.an-type{white-space:nowrap}.an-birthday{color:#7c3aed}.an-spouse{color:#db2777}.an-wedding{color:#b45309}.an-print-title{display:none}
@media print{@page{size:landscape;margin:9mm}.navbar,footer,.no-print{display:none!important}body{background:#fff!important}.container{max-width:none!important;padding:0!important}.dashboard-card,.profile-card{box-shadow:none!important}.an-table{font-size:9pt}.an-table th,.an-table td{padding:5px 7px}.an-print-title{display:block}}
</style></head><body><jsp:include page="includes/header.jsp"/><main class="container py-4">
<div class="d-flex justify-content-between align-items-start gap-3 flex-wrap mb-4"><div><a href="relatorios.jsp" class="btn btn-link px-0 no-print"><i class="bi bi-arrow-left"></i> Voltar aos relatórios</a><h1 class="fw-bold mb-1">Aniversários e Datas Comemorativas</h1><p class="text-muted mb-0"><%= han(gan(classeAn)) %> · <%= han(man(mesAn)) %><%= regiaoAn!=0?" · "+han(nomeRegiaoAn):"" %></p></div><button class="btn btn-outline-secondary no-print" onclick="window.print()"><i class="bi bi-printer"></i> Imprimir</button></div>
<form method="get" class="an-filter mb-4 no-print"><div class="row g-3 align-items-end"><div class="col-md-2"><label class="form-label">Grupo</label><select name="classe" class="form-select"><option value="0" <%= classeAn==0?"selected":"" %>>Todos</option><option value="1" <%= classeAn==1?"selected":"" %>>Diáconos</option><option value="2" <%= classeAn==2?"selected":"" %>>Candidatos</option><option value="3" <%= classeAn==3?"selected":"" %>>Vocacionados</option></select></div><div class="col-md-2"><label class="form-label">Mês</label><select name="mes" class="form-select"><option value="0" <%= mesAn==0?"selected":"" %>>Todos</option><% for(int m=1;m<=12;m++){ %><option value="<%= m %>" <%= mesAn==m?"selected":"" %>><%= han(man(m)) %></option><% } %></select></div><div class="col-md-2"><label class="form-label">Tipo</label><select name="tipo" class="form-select"><option value="" <%= tipoAn.isEmpty()?"selected":"" %>>Todos</option><option value="NASCIMENTO" <%= "NASCIMENTO".equals(tipoAn)?"selected":"" %>>Nascimento do membro</option><option value="ESPOSA" <%= "ESPOSA".equals(tipoAn)?"selected":"" %>>Nascimento da esposa</option><option value="CASAMENTO" <%= "CASAMENTO".equals(tipoAn)?"selected":"" %>>Casamento</option><option value="ORDENACAO" <%= "ORDENACAO".equals(tipoAn)?"selected":"" %>>Ordenação</option></select></div><div class="col-md-4"><label class="form-label">Região episcopal</label><% if(repAn){ %><input class="form-control" value="<%= han(nomeRegiaoAn.isEmpty()?"Região não identificada":nomeRegiaoAn) %>" disabled><% }else{ %><select name="regiao" class="form-select"><option value="0">Todas as regiões</option><% for(Map.Entry<Integer,String> x:regioesAn.entrySet()){ %><option value="<%= x.getKey() %>" <%= x.getKey()==regiaoAn?"selected":"" %>><%= han(x.getValue()) %></option><% } %></select><% } %></div><div class="col-md-2"><button class="btn btn-orange w-100"><i class="bi bi-funnel"></i> Aplicar</button></div></div></form>
<% if(erroAn!=null){ %><div class="alert alert-danger"><%= han(erroAn) %></div><% } %>
<div class="row g-3 mb-4"><div class="col"><div class="dashboard-card"><h5>Datas encontradas</h5><div class="card-number"><%= eventosAn.size() %></div></div></div><div class="col"><div class="dashboard-card"><h5>Nascimentos</h5><div class="card-number an-birthday"><%= nascimentosAn %></div></div></div><div class="col"><div class="dashboard-card"><h5>Esposas</h5><div class="card-number an-spouse"><%= esposasAn %></div></div></div><div class="col"><div class="dashboard-card"><h5>Casamentos</h5><div class="card-number an-wedding"><%= casamentosAn %></div></div></div><div class="col"><div class="dashboard-card"><h5>Ordenações</h5><div class="card-number text-primary"><%= ordenacoesAn %></div></div></div></div>
<h2 class="an-print-title fs-5 mb-3"><%= han(gan(classeAn)) %> · <%= han(man(mesAn)) %><%= regiaoAn!=0?" · "+han(nomeRegiaoAn):"" %></h2>
<section class="profile-card"><div class="table-responsive"><table class="table table-hover an-table"><thead><tr><th>Grupo</th><th>Membro</th><th>Esposa</th><th>Paróquia</th><th>Região</th><th>Data</th><th>Idade / Anos</th><th>Tipo</th></tr></thead><tbody><% for(EventoAn e:eventosAn){String descricao="NASCIMENTO".equals(e.tipo)?"Nascimento":"ESPOSA".equals(e.tipo)?"Esposa":"CASAMENTO".equals(e.tipo)?"Matrimônio":"Ordenação";String classeTipo="NASCIMENTO".equals(e.tipo)?"an-birthday":"ESPOSA".equals(e.tipo)?"an-spouse":"CASAMENTO".equals(e.tipo)?"an-wedding":"text-primary"; %><tr><td><span class="badge-tag <%= e.classe==1?"tag-green":e.classe==2?"tag-yellow":"tag-blue" %>"><%= han(gan(e.classe)) %></span></td><td><strong><%= han(e.membro) %></strong></td><td><%= e.esposa==null||e.esposa.isEmpty()?"—":han(e.esposa) %></td><td><%= e.paroquia==null||e.paroquia.isEmpty()?"—":han(e.paroquia) %></td><td><%= e.regiao==null||e.regiao.isEmpty()?"—":han(e.regiao) %></td><td class="an-date"><%= han(e.data) %></td><td><%= e.idade %> <%= "CASAMENTO".equals(e.tipo)?"anos de matrimônio":"ORDENACAO".equals(e.tipo)?"anos de ordenação":"anos" %></td><td class="an-type <%= classeTipo %>"><i class="bi <%= "NASCIMENTO".equals(e.tipo)?"bi-gift":"ESPOSA".equals(e.tipo)?"bi-balloon-heart":"CASAMENTO".equals(e.tipo)?"bi-heart-fill":"bi-award-fill" %>"></i> <%= descricao %></td></tr><% } %><% if(eventosAn.isEmpty()){ %><tr><td colspan="8" class="text-center text-muted py-5">Nenhuma data encontrada para os filtros selecionados.</td></tr><% } %></tbody></table></div></section>
</main><jsp:include page="includes/footer.jsp"/></body></html>
