<%@ page import="java.sql.*,java.util.Calendar,java.util.List,java.util.ArrayList,java.util.Locale" %>
<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ include file="includes/auth.jsp" %>
<%!
private String raHtml(String v){if(v==null)return "";return v.replace("&","&amp;").replace("<","&lt;").replace(">","&gt;").replace("\"","&quot;");}
private String raNomePagina(String pagina,String titulo){if(titulo!=null&&!titulo.trim().isEmpty()&&!"Clerical".equalsIgnoreCase(titulo.trim()))return titulo.trim();String nome=pagina==null?"":pagina;int barra=nome.lastIndexOf('/');if(barra>=0)nome=nome.substring(barra+1);nome=nome.replaceFirst("\\.(jsp|html)$","").replace('-',' ').replace('_',' ');return nome.isEmpty()?"Página":nome.substring(0,1).toUpperCase()+nome.substring(1);}
%>
<%
if(!"ADM".equals((String)session.getAttribute("usuarioPerfil"))){response.sendRedirect("index.jsp");return;}
Date fimRa=new Date(Calendar.getInstance().getTimeInMillis());Calendar inicioCalRa=Calendar.getInstance();inicioCalRa.add(Calendar.DAY_OF_MONTH,-29);Date inicioRa=new Date(inicioCalRa.getTimeInMillis());
try{String v=request.getParameter("inicio");if(v!=null&&v.matches("\\d{4}-\\d{2}-\\d{2}"))inicioRa=Date.valueOf(v);}catch(Exception e){}
try{String v=request.getParameter("fim");if(v!=null&&v.matches("\\d{4}-\\d{2}-\\d{2}"))fimRa=Date.valueOf(v);}catch(Exception e){}
if(inicioRa.after(fimRa)){Date t=inicioRa;inicioRa=fimRa;fimRa=t;}
long totalRa=0,usuariosRa=0,paginasRa=0;List<String[]> rankingRa=new ArrayList<String[]>(),diasRa=new ArrayList<String[]>(),perfisRa=new ArrayList<String[]>();String erroRa=null;
try(Connection c=cad.db.Database.getConnection()){
 try(Statement s=c.createStatement()){s.executeUpdate("CREATE TABLE IF NOT EXISTS estatistica_acessos (IdAcesso BIGINT NOT NULL AUTO_INCREMENT,IdPessoa INT NOT NULL,Perfil VARCHAR(10) NOT NULL,IdGrupo INT NULL,Pagina VARCHAR(120) NOT NULL,Titulo VARCHAR(160) NULL,DtAcesso DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(IdAcesso),KEY ix_estatistica_data(DtAcesso),KEY ix_estatistica_pagina_data(Pagina,DtAcesso),KEY ix_estatistica_pessoa_data(IdPessoa,DtAcesso)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");}
 String periodo=" DtAcesso>=? AND DtAcesso<DATE_ADD(?,INTERVAL 1 DAY) ";
 try(PreparedStatement p=c.prepareStatement("SELECT COUNT(*),COUNT(DISTINCT IdPessoa),COUNT(DISTINCT Pagina) FROM estatistica_acessos WHERE"+periodo)){p.setDate(1,inicioRa);p.setDate(2,fimRa);try(ResultSet r=p.executeQuery()){if(r.next()){totalRa=r.getLong(1);usuariosRa=r.getLong(2);paginasRa=r.getLong(3);}}}
 try(PreparedStatement p=c.prepareStatement("SELECT Pagina,MAX(Titulo),COUNT(*),COUNT(DISTINCT IdPessoa) FROM estatistica_acessos WHERE"+periodo+"GROUP BY Pagina ORDER BY COUNT(*) DESC,Pagina LIMIT 50")){p.setDate(1,inicioRa);p.setDate(2,fimRa);try(ResultSet r=p.executeQuery()){while(r.next())rankingRa.add(new String[]{r.getString(1),r.getString(2),r.getString(3),r.getString(4)});}}
 try(PreparedStatement p=c.prepareStatement("SELECT DATE_FORMAT(DtAcesso,'%d/%m/%Y'),COUNT(*),COUNT(DISTINCT IdPessoa) FROM estatistica_acessos WHERE"+periodo+"GROUP BY DATE(DtAcesso) ORDER BY DATE(DtAcesso)")){p.setDate(1,inicioRa);p.setDate(2,fimRa);try(ResultSet r=p.executeQuery()){while(r.next())diasRa.add(new String[]{r.getString(1),r.getString(2),r.getString(3)});}}
 try(PreparedStatement p=c.prepareStatement("SELECT Perfil,COUNT(*),COUNT(DISTINCT IdPessoa) FROM estatistica_acessos WHERE"+periodo+"GROUP BY Perfil ORDER BY COUNT(*) DESC")){p.setDate(1,inicioRa);p.setDate(2,fimRa);try(ResultSet r=p.executeQuery()){while(r.next())perfisRa.add(new String[]{r.getString(1),r.getString(2),r.getString(3)});}}
}catch(Exception e){e.printStackTrace();erroRa="Não foi possível consultar as estatísticas de acesso.";}
%>
<!doctype html><html lang="pt-br"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Estatísticas de acesso</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"><link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet"><link rel="stylesheet" href="css/style.css"><style>.ra-filter{background:#fff;border:1px solid #e5eaf0;border-radius:16px;padding:18px}.ra-bar{height:8px;background:#e9eef5;border-radius:8px;overflow:hidden}.ra-bar span{display:block;height:100%;background:#f28c28;border-radius:8px}.ra-num{font-variant-numeric:tabular-nums;white-space:nowrap}.ra-chart-wrap{position:relative;width:100%;height:360px}.ra-chart-legend{display:flex;gap:20px;flex-wrap:wrap}.ra-chart-key{display:inline-flex;align-items:center;gap:7px;font-size:.9rem;color:#64748b}.ra-chart-key::before{content:"";width:24px;height:3px;border-radius:4px;background:var(--ra-cor)}@media(max-width:576px){.ra-chart-wrap{height:280px}}</style></head><body><jsp:include page="includes/header.jsp"/>
<main class="container py-4"><a href="relatorios.jsp" class="btn btn-link px-0"><i class="bi bi-arrow-left"></i> Voltar aos relatórios</a><div class="mb-4"><h1 class="fw-bold mb-1">Estatísticas de acesso</h1><p class="text-muted mb-0">Páginas visualizadas por usuários autenticados</p></div>
<form class="ra-filter mb-4" method="get"><div class="row g-3 align-items-end"><div class="col-md-4"><label class="form-label">Data inicial</label><input class="form-control" type="date" name="inicio" value="<%= inicioRa %>"></div><div class="col-md-4"><label class="form-label">Data final</label><input class="form-control" type="date" name="fim" value="<%= fimRa %>"></div><div class="col-md-4"><button class="btn btn-orange w-100" type="submit"><i class="bi bi-funnel"></i> Aplicar período</button></div></div></form>
<% if(erroRa!=null){ %><div class="alert alert-danger"><%= erroRa %></div><% } %>
<div class="row g-3 mb-4"><div class="col-md-4"><div class="dashboard-card"><h5>Visualizações</h5><div class="card-number"><%= totalRa %></div></div></div><div class="col-md-4"><div class="dashboard-card"><h5>Usuários únicos</h5><div class="card-number"><%= usuariosRa %></div></div></div><div class="col-md-4"><div class="dashboard-card"><h5>Páginas acessadas</h5><div class="card-number"><%= paginasRa %></div></div></div></div>
<div class="row g-4"><div class="col-lg-8"><section class="profile-card h-100"><h4 class="mb-3">Páginas mais acessadas</h4><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Página</th><th class="text-end">Acessos</th><th class="text-end">Usuários</th><th style="width:25%">Participação</th></tr></thead><tbody><% if(rankingRa.isEmpty()){ %><tr><td colspan="4" class="text-center text-muted py-4">Ainda não existem acessos registrados neste período.</td></tr><% }else{for(String[] x:rankingRa){long n=Long.parseLong(x[2]);double pct=totalRa==0?0:(n*100.0/totalRa); %><tr><td><strong><%= raHtml(raNomePagina(x[0],x[1])) %></strong><small class="d-block text-muted"><%= raHtml(x[0]) %></small></td><td class="text-end ra-num"><%= x[2] %></td><td class="text-end ra-num"><%= x[3] %></td><td><div class="small mb-1"><%= String.format(Locale.US,"%.1f",pct).replace('.',',') %>%</div><div class="ra-bar"><span style="width:<%= Math.min(100.0,pct) %>%"></span></div></td></tr><% }} %></tbody></table></div></section></div>
<div class="col-lg-4"><section class="profile-card mb-4"><h4 class="mb-3">Acessos por perfil</h4><table class="table align-middle mb-0"><thead><tr><th>Perfil</th><th class="text-end">Acessos</th><th class="text-end">Usuários</th></tr></thead><tbody><% if(perfisRa.isEmpty()){ %><tr><td colspan="3" class="text-muted">Sem dados.</td></tr><% }else{for(String[] x:perfisRa){ %><tr><td><span class="badge text-bg-light"><%= raHtml(x[0]) %></span></td><td class="text-end ra-num"><%= x[1] %></td><td class="text-end ra-num"><%= x[2] %></td></tr><% }} %></tbody></table></section>
<section class="profile-card"><h4 class="mb-3">Evolução diária</h4><div class="table-responsive" style="max-height:390px"><table class="table table-sm align-middle"><thead><tr><th>Data</th><th class="text-end">Acessos</th><th class="text-end">Usuários</th></tr></thead><tbody><% if(diasRa.isEmpty()){ %><tr><td colspan="3" class="text-muted">Sem dados.</td></tr><% }else{for(String[] x:diasRa){ %><tr><td><%= x[0] %></td><td class="text-end ra-num"><%= x[1] %></td><td class="text-end ra-num"><%= x[2] %></td></tr><% }} %></tbody></table></div></section></div></div>
<section class="profile-card mt-4"><div class="d-flex justify-content-between align-items-start gap-3 flex-wrap mb-3"><div><h4 class="mb-1">Evolução dos acessos no período</h4><p class="text-muted mb-0">Comparativo diário entre visualizações e usuários únicos</p></div><div class="ra-chart-legend"><span class="ra-chart-key" style="--ra-cor:#f28c28">Acessos</span><span class="ra-chart-key" style="--ra-cor:#2563eb">Usuários únicos</span></div></div><% if(diasRa.isEmpty()){ %><div class="text-center text-muted py-5">Não há dados suficientes para gerar o gráfico.</div><% }else{ %><div class="ra-chart-wrap"><canvas id="raGrafico" role="img" aria-label="Gráfico da evolução diária dos acessos e usuários únicos"></canvas></div><% } %></section>
</main><jsp:include page="includes/footer.jsp"/>
<% if(!diasRa.isEmpty()){ %><script>
(function(){
 var dados=[<% for(int i=0;i<diasRa.size();i++){String[] x=diasRa.get(i);if(i>0)out.print(','); %>{data:'<%= x[0] %>',acessos:<%= x[1] %>,usuarios:<%= x[2] %>}<% } %>],canvas=document.getElementById('raGrafico'),wrap=canvas.parentElement;
 function desenhar(){
  var dpr=window.devicePixelRatio||1,w=Math.max(320,wrap.clientWidth),h=wrap.clientHeight;canvas.width=w*dpr;canvas.height=h*dpr;canvas.style.width=w+'px';canvas.style.height=h+'px';var c=canvas.getContext('2d');c.scale(dpr,dpr);c.clearRect(0,0,w,h);
  var margem={e:18,d:18,t:18,b:48},cw=w-margem.e-margem.d,ch=h-margem.t-margem.b,max=Math.max(1,...dados.map(function(x){return Math.max(x.acessos,x.usuarios);}));max=Math.ceil(max/5)*5||5;
  c.font='12px Arial';c.textBaseline='middle';c.strokeStyle='#e2e8f0';c.fillStyle='#64748b';c.lineWidth=1;
  for(var y=0;y<=5;y++){var py=margem.t+ch*y/5,valor=Math.round(max*(5-y)/5);c.beginPath();c.moveTo(margem.e,py);c.lineTo(w-margem.d,py);c.stroke();c.textAlign='left';c.fillText(String(valor),margem.e+4,py-9);}
  var passo=dados.length>1?cw/(dados.length-1):0,rotuloPasso=Math.max(1,Math.ceil(dados.length/(w<600?5:10)));c.textAlign='center';dados.forEach(function(x,i){if(i%rotuloPasso===0||i===dados.length-1)c.fillText(x.data.substring(0,5),margem.e+(dados.length===1?cw/2:i*passo),h-18);});
  function linha(campo,cor){c.strokeStyle=cor;c.fillStyle=cor;c.lineWidth=3;c.lineJoin='round';c.lineCap='round';c.beginPath();dados.forEach(function(x,i){var px=margem.e+(dados.length===1?cw/2:i*passo),py=margem.t+ch-(x[campo]/max)*ch;if(i===0)c.moveTo(px,py);else c.lineTo(px,py);});c.stroke();dados.forEach(function(x,i){var px=margem.e+(dados.length===1?cw/2:i*passo),py=margem.t+ch-(x[campo]/max)*ch;c.beginPath();c.arc(px,py,3.5,0,Math.PI*2);c.fill();});}
  linha('acessos','#f28c28');linha('usuarios','#2563eb');
 }
 desenhar();var timer;window.addEventListener('resize',function(){clearTimeout(timer);timer=setTimeout(desenhar,120);});
})();
</script><% } %></body></html>
