<%@ page import="java.sql.*,java.util.*,java.math.BigDecimal,java.time.Year" %>
<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ include file="includes/auth.jsp" %>
<%!
private String hc(String v){return v==null?"":v.replace("&","&amp;").replace("<","&lt;").replace(">","&gt;").replace("\"","&quot;");}
private int ic(String v,int d){try{return Integer.parseInt(v);}catch(Exception e){return d;}}
private String mc(BigDecimal v){return v==null?"—":"R$ "+String.format(Locale.US,"%,.2f",v).replace(",","#").replace(".",",").replace("#",".");}
%>
<%
String pf=(String)session.getAttribute("usuarioPerfil");Integer gs=(Integer)session.getAttribute("usuarioGrupoId"),rs=(Integer)session.getAttribute("usuarioRegiaoId");
if(!"ADM".equals(pf)&&!"FIN".equals(pf)&&!"REP".equals(pf)&&!"EXT".equals(pf)){response.sendRedirect("index.jsp");return;}
int ano=ic(request.getParameter("ano"),Year.now().getValue()),grupo=ic(request.getParameter("classe"),0),regiao=ic(request.getParameter("regiao"),0);String filtro=request.getParameter("situacao");if(filtro==null)filtro="";
class Col{int mes;String titulo,sub;}
class Pes{int id,pagas;String nome,paroquia,regiao;Map<Integer,Integer> st=new HashMap<Integer,Integer>();Map<Integer,BigDecimal> vl=new HashMap<Integer,BigDecimal>();BigDecimal total=BigDecimal.ZERO;}
LinkedHashMap<Integer,String> grupos=new LinkedHashMap<Integer,String>(),regioes=new LinkedHashMap<Integer,String>();List<Integer> anos=new ArrayList<Integer>();List<Col> cols=new ArrayList<Col>();List<Pes> pessoas=new ArrayList<Pes>();String nomeGrupo="",periodicidade="MENSAL",escopo="TODOS",erro=null,nomeRegiao="";boolean ateAtual=false,restringeRegiao=false,fixaGrupo=false;
try(Connection c=cad.db.Database.getConnection()){
 if("REP".equals(pf)){escopo="NENHUM";if(gs!=null)try(PreparedStatement p=c.prepareStatement("SELECT IFNULL(EscopoRepContribuicoes,'NENHUM') FROM grupos WHERE IdGrupo=?")){p.setInt(1,gs);try(ResultSet r=p.executeQuery()){if(r.next())escopo=r.getString(1);}}}
 fixaGrupo="FIN".equals(pf)||("REP".equals(pf)&&"PROPRIO".equals(escopo));if(fixaGrupo)grupo=gs==null?-1:gs;if("REP".equals(pf)&&"NENHUM".equals(escopo))grupo=-1;restringeRegiao="REP".equals(pf)&&"REGIAO_TODOS".equals(escopo);if(restringeRegiao)regiao=rs==null?-1:rs;
 String qg="SELECT IdGrupo,NomePlural FROM grupos WHERE StatusGrupo='ATIVO' AND GrupoOperacional=1 AND ModuloContribuicoes=1 AND ContribuicaoAtiva=1"+(fixaGrupo?" AND IdGrupo=?":"")+" ORDER BY Ordem,NomePlural";try(PreparedStatement p=c.prepareStatement(qg)){if(fixaGrupo)p.setInt(1,gs==null?-1:gs);try(ResultSet r=p.executeQuery()){while(r.next())grupos.put(r.getInt(1),r.getString(2));}}
 if(grupo==0&&!grupos.isEmpty())grupo=grupos.keySet().iterator().next();try(PreparedStatement p=c.prepareStatement("SELECT NomePlural,ContribuicaoPeriodicidade,ContribuicaoAteMesAtual FROM grupos WHERE IdGrupo=?")){p.setInt(1,grupo);try(ResultSet r=p.executeQuery()){if(r.next()){nomeGrupo=r.getString(1);periodicidade=r.getString(2);ateAtual=r.getBoolean(3);}}}
 TreeSet<Integer> aa=new TreeSet<Integer>(Collections.reverseOrder());aa.add(Year.now().getValue());try(PreparedStatement p=c.prepareStatement("SELECT DISTINCT YEAR(dtVencimento) a FROM lancamentos WHERE tipoLancamento='1.1' AND idClasse=? UNION SELECT DISTINCT YEAR(DtEncontro) FROM Encontros WHERE Checklist=0 AND Classe=?")){p.setInt(1,grupo);p.setInt(2,grupo);try(ResultSet r=p.executeQuery()){while(r.next())if(r.getInt(1)>0)aa.add(r.getInt(1));}}anos.addAll(aa);if(!aa.contains(ano))anos.add(ano);
 try(PreparedStatement p=c.prepareStatement("SELECT DISTINCT IdRegiao,Regiao FROM paroquia WHERE IdRegiao IS NOT NULL AND Regiao<>'' ORDER BY Regiao");ResultSet r=p.executeQuery()){while(r.next()){int id=r.getInt(1);if(!restringeRegiao||id==regiao)regioes.put(id,r.getString(2));if(id==regiao)nomeRegiao=r.getString(2);}}
 String[] nm={"Jan","Fev","Mar","Abr","Mai","Jun","Jul","Ago","Set","Out","Nov","Dez"};if("ENCONTRO".equals(periodicidade)){try(PreparedStatement p=c.prepareStatement("SELECT MONTH(DtEncontro),COUNT(*),DATE_FORMAT(MIN(DtEncontro),'%d/%m') FROM Encontros WHERE Classe=? AND Checklist=0 AND YEAR(DtEncontro)=? AND DtEncontro<=CURDATE() GROUP BY MONTH(DtEncontro) ORDER BY MONTH(DtEncontro)")){p.setInt(1,grupo);p.setInt(2,ano);try(ResultSet r=p.executeQuery()){while(r.next()){Col x=new Col();x.mes=r.getInt(1);x.titulo=r.getInt(2)==1?r.getString(3):nm[x.mes-1];x.sub=r.getInt(2)==1?"Encontro":r.getInt(2)+" encontros";cols.add(x);}}}}else{int lim=12;if(ateAtual&&ano==Year.now().getValue())lim=Calendar.getInstance().get(Calendar.MONTH)+1;else if(ateAtual&&ano>Year.now().getValue())lim=0;for(int m=1;m<=lim;m++){Col x=new Col();x.mes=m;x.titulo=nm[m-1];x.sub="Mensal";cols.add(x);}}
 LinkedHashMap<Integer,Pes> mapa=new LinkedHashMap<Integer,Pes>();String qp="SELECT IdPessoa,Nome,IFNULL(Paroquia,''),IFNULL(Regiao,'') FROM sqlPessoas WHERE Status=1 AND Classe=?"+(regiao!=0?" AND IFNULL(IdRegiao,0)=?":"")+" ORDER BY Nome";try(PreparedStatement p=c.prepareStatement(qp)){p.setInt(1,grupo);if(regiao!=0)p.setInt(2,regiao);try(ResultSet r=p.executeQuery()){while(r.next()){Pes x=new Pes();x.id=r.getInt(1);x.nome=r.getString(2);x.paroquia=r.getString(3);x.regiao=r.getString(4);mapa.put(x.id,x);}}}
 try(PreparedStatement p=c.prepareStatement("SELECT idPessoa,MONTH(dtVencimento),status,IFNULL(valorPago,0) FROM lancamentos l WHERE tipoLancamento='1.1' AND idClasse=? AND YEAR(dtVencimento)=? AND idLancamento=(SELECT MAX(x.idLancamento) FROM lancamentos x WHERE x.idPessoa=l.idPessoa AND x.tipoLancamento='1.1' AND YEAR(x.dtVencimento)=YEAR(l.dtVencimento) AND MONTH(x.dtVencimento)=MONTH(l.dtVencimento))")){p.setInt(1,grupo);p.setInt(2,ano);try(ResultSet r=p.executeQuery()){while(r.next()){Pes x=mapa.get(r.getInt(1));if(x!=null){x.st.put(r.getInt(2),r.getInt(3));x.vl.put(r.getInt(2),r.getBigDecimal(4));}}}}
 for(Pes x:mapa.values()){for(Col z:cols)if(x.st.containsKey(z.mes)&&x.st.get(z.mes)==1){x.pagas++;BigDecimal v=x.vl.get(z.mes);if(v!=null)x.total=x.total.add(v);}boolean ok="PAGO".equals(filtro)?x.pagas==cols.size()&&!cols.isEmpty():"PENDENTE".equals(filtro)?x.pagas<cols.size():true;if(ok)pessoas.add(x);}
}catch(Exception e){e.printStackTrace();erro="Não foi possível carregar o relatório de contribuições.";}
int esperadas=pessoas.size()*cols.size(),pagas=0;BigDecimal recebido=BigDecimal.ZERO;for(Pes x:pessoas){pagas+=x.pagas;recebido=recebido.add(x.total);}double pct=esperadas==0?0:pagas*100.0/esperadas;
%>
<!doctype html><html lang="pt-br"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Mapa de Contribuições</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"><link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet"><link rel="stylesheet" href="css/style.css"><style>.cf{background:#fff;border:1px solid #e8edf3;border-radius:16px;padding:20px}.cw{overflow-x:auto}.ct{min-width:900px;margin:0}.ct th,.ct td{text-align:center;vertical-align:middle;border-right:1px solid #e2e8f0;padding:7px}.ct th{font-size:11px;white-space:nowrap}.ct .cn{text-align:left;min-width:220px;position:sticky;left:0;background:#fff;z-index:1}.ct thead .cn{background:#f8fafc;z-index:2}.cs{display:inline-grid;place-items:center;min-width:32px;height:28px;border-radius:8px;font-size:12px;font-weight:800}.co{background:#dcfce7;color:#15803d}.cp{background:#fee2e2;color:#b91c1c}.cv{font-size:10px;white-space:nowrap}@media print{@page{size:landscape;margin:7mm}.navbar,footer,.no-print{display:none!important}.container{max-width:none!important;padding:0!important}.cw{overflow:visible}.ct{min-width:0;font-size:7pt}.ct th,.ct td{padding:3px 2px}.ct .cn{position:static;min-width:100px}.cs{min-width:18px;height:18px;font-size:7pt}.cv{font-size:6pt}}</style></head><body><jsp:include page="includes/header.jsp"/><main class="container py-4">
<div class="d-flex justify-content-between align-items-start flex-wrap gap-3 mb-4"><div><a href="contribuicoes.jsp" class="btn btn-link px-0 no-print"><i class="bi bi-arrow-left"></i> Voltar às contribuições</a><h1 class="fw-bold mb-1">Mapa de Contribuições</h1><p class="text-muted mb-0"><%= hc(nomeGrupo) %> · <%= ano %> · <%= "ENCONTRO".equals(periodicidade)?"Por encontro":"Mensal" %></p></div><button class="btn btn-outline-secondary no-print" onclick="window.print()"><i class="bi bi-printer"></i> Imprimir</button></div>
<form class="cf mb-4 no-print"><div class="row g-3 align-items-end"><div class="col-md-2"><label class="form-label">Ano</label><select name="ano" class="form-select"><% for(Integer a:anos){ %><option <%= a==ano?"selected":"" %>><%= a %></option><% } %></select></div><div class="col-md-3"><label class="form-label">Grupo</label><% if(fixaGrupo){ %><input class="form-control" value="<%= hc(nomeGrupo) %>" disabled><input type="hidden" name="classe" value="<%= grupo %>"><% }else{ %><select name="classe" class="form-select"><% for(Map.Entry<Integer,String> g:grupos.entrySet()){ %><option value="<%= g.getKey() %>" <%= g.getKey()==grupo?"selected":"" %>><%= hc(g.getValue()) %></option><% } %></select><% } %></div><div class="col-md-3"><label class="form-label">Região</label><% if(restringeRegiao){ %><input class="form-control" value="<%= hc(nomeRegiao) %>" disabled><% }else{ %><select name="regiao" class="form-select"><option value="0">Todas</option><% for(Map.Entry<Integer,String> r:regioes.entrySet()){ %><option value="<%= r.getKey() %>" <%= r.getKey()==regiao?"selected":"" %>><%= hc(r.getValue()) %></option><% } %></select><% } %></div><div class="col-md-2"><label class="form-label">Situação</label><select name="situacao" class="form-select"><option value="">Todos</option><option value="PAGO" <%= "PAGO".equals(filtro)?"selected":"" %>>Em dia</option><option value="PENDENTE" <%= "PENDENTE".equals(filtro)?"selected":"" %>>Com pendência</option></select></div><div class="col-md-2"><button class="btn btn-orange w-100"><i class="bi bi-funnel"></i> Aplicar</button></div></div></form>
<% if(erro!=null){ %><div class="alert alert-danger"><%= hc(erro) %></div><% } %><div class="row g-3 mb-4"><div class="col-md-3"><div class="dashboard-card"><h5>Membros</h5><div class="card-number"><%= pessoas.size() %></div></div></div><div class="col-md-3"><div class="dashboard-card"><h5>Contribuições</h5><div class="card-number text-success"><%= pagas %></div><small class="text-muted">de <%= esperadas %> esperadas</small></div></div><div class="col-md-3"><div class="dashboard-card"><h5>Adimplência</h5><div class="card-number"><%= String.format(Locale.US,"%.1f",pct).replace('.',',') %>%</div></div></div><div class="col-md-3"><div class="dashboard-card"><h5>Total recebido</h5><div class="card-number" style="font-size:1.5rem"><%= mc(recebido) %></div></div></div></div>
<section class="profile-card p-0 overflow-hidden"><div class="p-3 border-bottom"><h4 class="mb-0">Contribuições por membro</h4></div><% if(pessoas.isEmpty()||cols.isEmpty()){ %><div class="text-center text-muted py-5">Nenhuma informação encontrada.</div><% }else{ %><div class="cw"><table class="table table-hover ct"><thead><tr><th class="cn">Membro</th><th>Paróquia / Região</th><th>Resultado</th><% for(Col z:cols){ %><th><%= hc(z.titulo) %><small class="d-block text-muted"><%= hc(z.sub) %></small></th><% } %><th>Total</th></tr></thead><tbody><% for(Pes x:pessoas){ %><tr><td class="cn"><strong><%= hc(x.nome) %></strong></td><td><%= hc(x.paroquia.isEmpty()?"—":x.paroquia) %><small class="d-block text-muted"><%= hc(x.regiao) %></small></td><td><strong><%= cols.isEmpty()?0:Math.round(x.pagas*100.0/cols.size()) %>%</strong><small class="d-block text-muted"><%= x.pagas %>/<%= cols.size() %></small></td><% for(Col z:cols){boolean pago=x.st.containsKey(z.mes)&&x.st.get(z.mes)==1; %><td><span class="cs <%= pago?"co":"cp" %>"><%= pago?"P":"—" %></span><% if(pago){ %><small class="d-block cv text-muted"><%= mc(x.vl.get(z.mes)) %></small><% } %></td><% } %><td class="fw-bold text-nowrap"><%= mc(x.total) %></td></tr><% } %></tbody></table></div><% } %></section>
</main><jsp:include page="includes/footer.jsp"/></body></html>
