<%@ page import="java.sql.*,java.util.*,java.text.SimpleDateFormat" %>
<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ include file="includes/auth.jsp" %>
<%@ include file="includes/escopoRelatorios.jspf" %>
<%!
private String rdH(String v){return v==null?"":v.replace("&","&amp;").replace("<","&lt;").replace(">","&gt;").replace("\"","&quot;").replace("'","&#39;");}
private String rdLabel(String c){String s=c.replace('_',' ').replaceAll("([a-z])([A-Z])","$1 $2");return s.length()==0?s:s.substring(0,1).toUpperCase()+s.substring(1);}
private boolean rdOn(String v){return "1".equals(v)||"on".equalsIgnoreCase(v)||"true".equalsIgnoreCase(v);}
%>
<%
String perfilRd=(String)session.getAttribute("usuarioPerfil");if(!"ADM".equals(perfilRd)&&!"REP".equals(perfilRd)&&!"EXT".equals(perfilRd)){response.sendRedirect("index.jsp");return;}
boolean gerarRd="1".equals(request.getParameter("gerar")),repRd="REP".equals(perfilRd);String escopoRd=cadEscopoRelatorios(session);Integer grupoRd=(Integer)session.getAttribute("usuarioGrupoId"),regiaoRd=(Integer)session.getAttribute("usuarioRegiaoId");
LinkedHashMap<String,Integer> disponiveisRd=new LinkedHashMap<String,Integer>();List<String> camposRd=new ArrayList<String>(),cabecalhosRd=new ArrayList<String>();List<String[]> linhasRd=new ArrayList<String[]>();String erroRd=null;
String tituloRd=request.getParameter("titulo");if(tituloRd==null||tituloRd.trim().isEmpty())tituloRd="Relatório Dinâmico de Membros";if(tituloRd.length()>120)tituloRd=tituloRd.substring(0,120);
boolean linhaRd=rdOn(request.getParameter("exibe_linha")),totalRd=!gerarRd||rdOn(request.getParameter("exibe_total")),dataRd=rdOn(request.getParameter("exibe_data")),gradeRd=!gerarRd||rdOn(request.getParameter("exibe_grade")),zebraRd=!gerarRd||rdOn(request.getParameter("lista_zebrada")),ativosRd=!gerarRd||rdOn(request.getParameter("somente_ativos"));
String orientacaoRd="paisagem".equals(request.getParameter("orientacao"))?"paisagem":"retrato",densidadeRd="compacta".equals(request.getParameter("densidade"))?"compacta":"normal",ordemRd=request.getParameter("ordem"),direcaoRd="DESC".equals(request.getParameter("direcao"))?"DESC":"ASC",grupoVisualRd=request.getParameter("agrupar");
try(Connection c=cad.db.Database.getConnection()){
 try(PreparedStatement p=c.prepareStatement("SELECT * FROM sqlPessoas WHERE 1=0");ResultSet r=p.executeQuery()){ResultSetMetaData m=r.getMetaData();for(int i=1;i<=m.getColumnCount();i++){String n=m.getColumnLabel(i);String low=n.toLowerCase(Locale.ROOT);if(!low.contains("senha")&&!low.contains("password")&&!low.contains("token"))disponiveisRd.put(n,m.getColumnType(i));}}
 String[] enviados=request.getParameterValues("campos");if(enviados!=null)for(String x:enviados)if(disponiveisRd.containsKey(x)&&!camposRd.contains(x))camposRd.add(x);
 if(!gerarRd){String[] padrao={"Nome","Grupo","Regiao","Paroquia"};for(String x:padrao)if(disponiveisRd.containsKey(x))camposRd.add(x);}
 if(gerarRd&&camposRd.isEmpty())erroRd="Selecione pelo menos um campo para gerar o relatório.";
 if(ordemRd==null||!disponiveisRd.containsKey(ordemRd))ordemRd=camposRd.isEmpty()?null:camposRd.get(0);if(grupoVisualRd==null||!camposRd.contains(grupoVisualRd))grupoVisualRd="";
 if(gerarRd&&erroRd==null){
  StringBuilder sql=new StringBuilder("SELECT ");for(int i=0;i<camposRd.size();i++){if(i>0)sql.append(',');sql.append('`').append(camposRd.get(i)).append('`');String rot=request.getParameter("rotulo_"+camposRd.get(i));cabecalhosRd.add(rot==null||rot.trim().isEmpty()?rdLabel(camposRd.get(i)):rot.trim());}sql.append(" FROM sqlPessoas WHERE 1=1");List<String> valores=new ArrayList<String>();
  if(ativosRd&&disponiveisRd.containsKey("status"))sql.append(" AND `status`=1");
  if(repRd){if("NENHUM".equals(escopoRd))sql.append(" AND 1=0");else if("PROPRIO".equals(escopoRd)&&disponiveisRd.containsKey("Classe")){sql.append(" AND `Classe`=?");valores.add(String.valueOf(grupoRd==null?-1:grupoRd));}else if("REGIAO_TODOS".equals(escopoRd)&&disponiveisRd.containsKey("IdRegiao")){sql.append(" AND `IdRegiao`=?");valores.add(String.valueOf(regiaoRd==null?-1:regiaoRd));}}
  for(int f=1;f<=3;f++){String campo=request.getParameter("fcampo"+f),op=request.getParameter("fop"+f),valor=request.getParameter("fvalor"+f);if(campo==null||!disponiveisRd.containsKey(campo)||op==null)continue;if("VAZIO".equals(op))sql.append(" AND (`").append(campo).append("` IS NULL OR CAST(`").append(campo).append("` AS CHAR)='')");else if("PREENCHIDO".equals(op))sql.append(" AND (`").append(campo).append("` IS NOT NULL AND CAST(`").append(campo).append("` AS CHAR)<>'')");else if(valor!=null&&!valor.trim().isEmpty()){sql.append(" AND CAST(`").append(campo).append("` AS CHAR) ");if("IGUAL".equals(op)){sql.append("=?");valores.add(valor.trim());}else if("INICIA".equals(op)){sql.append("LIKE ?");valores.add(valor.trim()+"%");}else{sql.append("LIKE ?");valores.add("%"+valor.trim()+"%");}}}
  if(!grupoVisualRd.isEmpty())sql.append(" ORDER BY `").append(grupoVisualRd).append("` ").append(direcaoRd).append(ordemRd.equals(grupoVisualRd)?"":",`"+ordemRd+"` "+direcaoRd);else if(ordemRd!=null)sql.append(" ORDER BY `").append(ordemRd).append("` ").append(direcaoRd);sql.append(" LIMIT 2000");
  try(PreparedStatement p=c.prepareStatement(sql.toString())){for(int i=0;i<valores.size();i++)p.setString(i+1,valores.get(i));try(ResultSet r=p.executeQuery()){while(r.next()){String[] l=new String[camposRd.size()];for(int i=0;i<l.length;i++)l[i]=r.getString(i+1);linhasRd.add(l);}}}
 }
}catch(Exception e){e.printStackTrace();erroRd="Não foi possível preparar o relatório dinâmico.";}
%>
<!doctype html><html lang="pt-br"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Relatório Dinâmico</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"><link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet"><link rel="stylesheet" href="css/style.css"><style>.rd-box{background:#fff;border:1px solid #e5eaf0;border-radius:16px;padding:20px}.rd-fields{max-height:430px;overflow:auto;border:1px solid #e5eaf0;border-radius:12px}.rd-field{display:grid;grid-template-columns:32px minmax(130px,1fr) minmax(150px,1fr);gap:10px;align-items:center;padding:9px 12px;border-bottom:1px solid #edf1f5}.rd-field:last-child{border:0}.rd-result{overflow-x:auto}.rd-table th{white-space:nowrap}.rd-table.grade th,.rd-table.grade td{border:1px solid #cbd5e1}.rd-table.zebra tbody tr:nth-child(even) td{background:#f8fafc}.rd-table.compacta th,.rd-table.compacta td{padding:4px 6px;font-size:12px}.rd-group td{background:#fff3e8!important;color:#8a4307;font-weight:700}.rd-print-head{display:none}@media(max-width:650px){.rd-field{grid-template-columns:32px 1fr}.rd-field .rd-label{grid-column:2}}@media print{@page{size:<%= "paisagem".equals(orientacaoRd)?"landscape":"portrait" %>;margin:9mm}.navbar,footer,.no-print{display:none!important}body{background:#fff!important}.container{max-width:none!important;padding:0!important}.rd-box{border:0;box-shadow:none;padding:0}.rd-print-head{display:block}.rd-result{overflow:visible}.rd-table{font-size:9pt}}</style></head><body><jsp:include page="includes/header.jsp"/><main class="container py-4">
<style>@media print{main>.rd-page-heading{display:none!important}.rd-print-head+div{display:none!important}}</style>
<style>.rd-order{display:flex;gap:4px}.rd-order .btn{padding:2px 7px}.rd-field-number{color:#94a3b8;font-size:12px;text-align:center}@media(min-width:651px){.rd-field{grid-template-columns:32px 28px minmax(130px,1fr) minmax(150px,1fr) 72px}}@media(max-width:650px){.rd-field-number{display:none}.rd-order{grid-column:2}}</style>
<div class="d-flex justify-content-between align-items-start gap-3 flex-wrap mb-4 rd-page-heading"><div><a href="relatorios.jsp" class="btn btn-link px-0 no-print"><i class="bi bi-arrow-left"></i> Voltar aos relatórios</a><h1 class="fw-bold mb-1">Relatório Dinâmico</h1><p class="text-muted mb-0">Escolha campos, filtros e apresentação do relatório</p></div><% if(gerarRd&&erroRd==null){ %><button class="btn btn-outline-secondary no-print" onclick="window.print()"><i class="bi bi-printer"></i> Imprimir</button><% } %></div>
<form method="post" class="no-print"><input type="hidden" name="gerar" value="1"><section class="rd-box mb-4"><h4 class="mb-3">Identificação e apresentação</h4><div class="row g-3"><div class="col-md-6"><label class="form-label">Título</label><input name="titulo" maxlength="120" class="form-control" value="<%= rdH(tituloRd) %>"></div><div class="col-md-3"><label class="form-label">Orientação</label><select name="orientacao" class="form-select"><option value="retrato">Retrato</option><option value="paisagem" <%= "paisagem".equals(orientacaoRd)?"selected":"" %>>Paisagem</option></select></div><div class="col-md-3"><label class="form-label">Densidade</label><select name="densidade" class="form-select"><option value="normal">Normal</option><option value="compacta" <%= "compacta".equals(densidadeRd)?"selected":"" %>>Compacta</option></select></div></div><div class="d-flex flex-wrap gap-4 mt-3"><label class="form-check"><input class="form-check-input" type="checkbox" name="somente_ativos" value="1" <%= ativosRd?"checked":"" %>> Somente membros ativos</label><label class="form-check"><input class="form-check-input" type="checkbox" name="exibe_linha" value="1" <%= linhaRd?"checked":"" %>> Numerar linhas</label><label class="form-check"><input class="form-check-input" type="checkbox" name="exibe_total" value="1" <%= totalRd?"checked":"" %>> Exibir total</label><label class="form-check"><input class="form-check-input" type="checkbox" name="exibe_data" value="1" <%= dataRd?"checked":"" %>> Exibir data</label><label class="form-check"><input class="form-check-input" type="checkbox" name="exibe_grade" value="1" <%= gradeRd?"checked":"" %>> Grade</label><label class="form-check"><input class="form-check-input" type="checkbox" name="lista_zebrada" value="1" <%= zebraRd?"checked":"" %>> Linhas zebradas</label></div></section>
<section class="rd-box mb-4"><div class="d-flex justify-content-between align-items-center mb-3"><div><h4 class="mb-1">Campos</h4><small class="text-muted">Marque as colunas, personalize o título e use as setas para definir a ordem.</small></div><button type="button" class="btn btn-sm btn-outline-secondary" onclick="rdAlternar()">Marcar/desmarcar todos</button></div><div class="rd-fields"><% List<String> ordemTelaRd=new ArrayList<String>(camposRd);for(String x:disponiveisRd.keySet())if(!ordemTelaRd.contains(x))ordemTelaRd.add(x);int posRd=0;for(String c:ordemTelaRd){boolean marcado=camposRd.contains(c);String rot=request.getParameter("rotulo_"+c);posRd++; %><div class="rd-field"><input class="form-check-input rd-check" type="checkbox" name="campos" value="<%= rdH(c) %>" <%= marcado?"checked":"" %>><span class="rd-field-number"><%= posRd %></span><strong><%= rdH(rdLabel(c)) %></strong><input class="form-control form-control-sm rd-label" name="rotulo_<%= rdH(c) %>" value="<%= rdH(rot==null?"":rot) %>" placeholder="Título personalizado"><span class="rd-order"><button type="button" class="btn btn-sm btn-outline-secondary" onclick="rdMover(this,-1)" title="Mover para cima"><i class="bi bi-arrow-up"></i></button><button type="button" class="btn btn-sm btn-outline-secondary" onclick="rdMover(this,1)" title="Mover para baixo"><i class="bi bi-arrow-down"></i></button></span></div><% } %></div></section>
<section class="rd-box mb-4"><h4 class="mb-3">Filtros</h4><% for(int f=1;f<=3;f++){String fc=request.getParameter("fcampo"+f),fo=request.getParameter("fop"+f),fv=request.getParameter("fvalor"+f); %><div class="row g-2 mb-2"><div class="col-md-4"><select name="fcampo<%= f %>" class="form-select"><option value="">Campo...</option><% for(String c:disponiveisRd.keySet()){ %><option value="<%= rdH(c) %>" <%= c.equals(fc)?"selected":"" %>><%= rdH(rdLabel(c)) %></option><% } %></select></div><div class="col-md-3"><select name="fop<%= f %>" class="form-select"><option value="CONTEM">Contém</option><option value="IGUAL" <%= "IGUAL".equals(fo)?"selected":"" %>>Igual a</option><option value="INICIA" <%= "INICIA".equals(fo)?"selected":"" %>>Começa com</option><option value="VAZIO" <%= "VAZIO".equals(fo)?"selected":"" %>>Está vazio</option><option value="PREENCHIDO" <%= "PREENCHIDO".equals(fo)?"selected":"" %>>Está preenchido</option></select></div><div class="col-md-5"><input name="fvalor<%= f %>" class="form-control" value="<%= rdH(fv==null?"":fv) %>" placeholder="Valor do filtro"></div></div><% } %></section>
<section class="rd-box mb-4"><h4 class="mb-3">Ordenação e agrupamento</h4><div class="row g-3"><div class="col-md-4"><label class="form-label">Ordenar por</label><select name="ordem" class="form-select"><% for(String c:disponiveisRd.keySet()){ %><option value="<%= rdH(c) %>" <%= c.equals(ordemRd)?"selected":"" %>><%= rdH(rdLabel(c)) %></option><% } %></select></div><div class="col-md-3"><label class="form-label">Direção</label><select name="direcao" class="form-select"><option value="ASC">Crescente</option><option value="DESC" <%= "DESC".equals(direcaoRd)?"selected":"" %>>Decrescente</option></select></div><div class="col-md-5"><label class="form-label">Agrupar visualmente por</label><select name="agrupar" class="form-select"><option value="">Sem agrupamento</option><% for(String c:disponiveisRd.keySet()){ %><option value="<%= rdH(c) %>" <%= c.equals(grupoVisualRd)?"selected":"" %>><%= rdH(rdLabel(c)) %></option><% } %></select><small class="text-muted">O campo precisa estar selecionado.</small></div></div></section><button class="btn btn-orange btn-lg mb-4"><i class="bi bi-play-fill"></i> Gerar relatório</button></form>
<% if(erroRd!=null){ %><div class="alert alert-danger"><%= rdH(erroRd) %></div><% } %>
<% if(gerarRd&&erroRd==null){ %><section class="rd-box"><div class="rd-print-head mb-3"><h2><%= rdH(tituloRd) %></h2></div><div class="d-flex justify-content-between align-items-center mb-3"><h3 class="mb-0"><%= rdH(tituloRd) %></h3><span class="text-muted"><%= linhasRd.size() %> registro(s)</span></div><div class="rd-result"><table class="table rd-table <%= gradeRd?"grade":"" %> <%= zebraRd?"zebra":"" %> <%= densidadeRd %>"><thead><tr><% if(linhaRd){ %><th>#</th><% } %><% for(String h:cabecalhosRd){ %><th><%= rdH(h) %></th><% } %></tr></thead><tbody><% String ultimoGrupo=null;int gi=grupoVisualRd.isEmpty()?-1:camposRd.indexOf(grupoVisualRd),n=0;for(String[] l:linhasRd){if(gi>=0&&!Objects.equals(ultimoGrupo,l[gi])){ultimoGrupo=l[gi]; %><tr class="rd-group"><td colspan="<%= camposRd.size()+(linhaRd?1:0) %>"><%= rdH(rdLabel(grupoVisualRd)) %>: <%= rdH(ultimoGrupo==null?"Não informado":ultimoGrupo) %></td></tr><% }n++; %><tr><% if(linhaRd){ %><td><%= n %></td><% } %><% for(String v:l){ %><td><%= v==null||v.isEmpty()?"—":rdH(v) %></td><% } %></tr><% } %><% if(linhasRd.isEmpty()){ %><tr><td colspan="<%= camposRd.size()+(linhaRd?1:0) %>" class="text-center text-muted py-4">Nenhum registro encontrado.</td></tr><% } %></tbody></table></div><% if(totalRd){ %><p class="mt-3 mb-1"><strong>Total de registros:</strong> <%= linhasRd.size() %></p><% } %><% if(dataRd){ %><p class="text-muted mb-0"><em>Gerado em <%= new SimpleDateFormat("dd/MM/yyyy HH:mm").format(Calendar.getInstance().getTime()) %></em></p><% } %></section><% } %>
</main><jsp:include page="includes/footer.jsp"/><script>function rdNumerar(){document.querySelectorAll('.rd-field-number').forEach(function(x,i){x.textContent=i+1})}function rdMover(botao,direcao){var linha=botao.closest('.rd-field'),lista=linha.parentNode;if(direcao<0&&linha.previousElementSibling)lista.insertBefore(linha,linha.previousElementSibling);else if(direcao>0&&linha.nextElementSibling)lista.insertBefore(linha.nextElementSibling,linha);rdNumerar()}function rdAlternar(){var c=document.querySelectorAll('.rd-check'),marcar=Array.prototype.some.call(c,function(x){return!x.checked});Array.prototype.forEach.call(c,function(x){x.checked=marcar})}</script></body></html>
