<%@ page import="java.sql.*,java.util.*" %>
<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ include file="includes/auth.jsp" %>
<%@ include file="includes/escopoRelatorios.jspf" %>
<%!
private String hrr(String v){return v==null?"":v.replace("&","&amp;").replace("<","&lt;").replace(">","&gt;").replace("\"","&quot;").replace("'","&#39;");}
private int irr(String v,int d){try{return Integer.parseInt(v);}catch(Exception e){return d;}}
private String grr(int c){return c==0?"Todos os grupos":cad.grupos.GrupoCatalogo.plural(c);}
%>
<%
String perfilRr=(String)session.getAttribute("usuarioPerfil");if(!"ADM".equals(perfilRr)&&!"REP".equals(perfilRr)&&!"EXT".equals(perfilRr)){response.sendRedirect("index.jsp");return;}
boolean repRr="REP".equals(perfilRr);Integer regiaoSessaoRr=(Integer)session.getAttribute("usuarioRegiaoId");
String escopoRr=cadEscopoRelatorios(session);Integer grupoSessaoRr=(Integer)session.getAttribute("usuarioGrupoId");boolean restringeRegiaoRr=repRr&&"REGIAO_TODOS".equals(escopoRr);
int classeRr=irr(request.getParameter("classe"),0);if(classeRr<0)classeRr=0;int regiaoRr=irr(request.getParameter("regiao"),0);if(repRr&&"PROPRIO".equals(escopoRr))classeRr=grupoSessaoRr==null?-1:grupoSessaoRr;else if(restringeRegiaoRr)regiaoRr=regiaoSessaoRr==null?-1:regiaoSessaoRr;else if(repRr&&"NENHUM".equals(escopoRr))classeRr=-1;
class ParoquiaRr{int id,qtd;String nome,bairro,cidade;Map<Integer,Integer> grupos=new HashMap<Integer,Integer>();}
class RegiaoRr{int id,total;String nome;LinkedHashMap<Integer,ParoquiaRr> paroquias=new LinkedHashMap<Integer,ParoquiaRr>();Map<Integer,Integer> grupos=new HashMap<Integer,Integer>();}
LinkedHashMap<Integer,String> gruposAtivosRr=new LinkedHashMap<Integer,String>();LinkedHashMap<Integer,String> regioesFiltroRr=new LinkedHashMap<Integer,String>();LinkedHashMap<Integer,RegiaoRr> regioesRr=new LinkedHashMap<Integer,RegiaoRr>();String nomeRegiaoRr="",erroRr=null;int totalRr=0,totalParoquiasRr=0;Map<Integer,Integer> totaisGrupoRr=new HashMap<Integer,Integer>();
try{
 try(Connection c=cad.db.Database.getConnection()){
  try(PreparedStatement p=c.prepareStatement("SELECT IdGrupo,NomePlural FROM grupos WHERE StatusGrupo='ATIVO' AND GrupoOperacional=1 AND ModuloRelatorios=1 ORDER BY Ordem,NomePlural");ResultSet r=p.executeQuery()){while(r.next())gruposAtivosRr.put(r.getInt(1),r.getString(2));}
  try(PreparedStatement p=c.prepareStatement("SELECT DISTINCT IdRegiao,Regiao FROM paroquia WHERE IdRegiao IS NOT NULL AND Regiao IS NOT NULL AND Regiao<>'' ORDER BY Regiao");ResultSet r=p.executeQuery()){while(r.next()){int id=r.getInt(1);String nome=r.getString(2);if(!restringeRegiaoRr||id==regiaoRr)regioesFiltroRr.put(id,nome);if(id==regiaoRr)nomeRegiaoRr=nome;}}
  String sql="SELECT pa.IdRegiao,IFNULL(pa.Regiao,'') Regiao,pa.IdParoquia,IFNULL(pa.Descricao,'') Paroquia,IFNULL(pa.Bairro,'') Bairro,IFNULL(pa.Cidade,'') Cidade,p.Classe,COUNT(p.IdPessoa) Qtd FROM pessoas p JOIN grupos g ON g.IdGrupo=p.Classe AND g.StatusGrupo='ATIVO' AND g.GrupoOperacional=1 AND g.ModuloRelatorios=1 JOIN paroquia pa ON pa.IdParoquia=p.IdParoquia WHERE p.Status=1 AND (?=0 OR p.Classe=?) AND (?=0 OR pa.IdRegiao=?) GROUP BY pa.IdRegiao,pa.Regiao,pa.IdParoquia,pa.Descricao,pa.Bairro,pa.Cidade,p.Classe ORDER BY pa.Regiao,pa.Descricao,p.Classe";
  try(PreparedStatement p=c.prepareStatement(sql)){p.setInt(1,classeRr);p.setInt(2,classeRr);p.setInt(3,regiaoRr);p.setInt(4,regiaoRr);try(ResultSet r=p.executeQuery()){while(r.next()){int id=r.getInt("IdRegiao"),idParoquia=r.getInt("IdParoquia"),classe=r.getInt("Classe"),qtd=r.getInt("Qtd");RegiaoRr regiao=regioesRr.get(id);if(regiao==null){regiao=new RegiaoRr();regiao.id=id;regiao.nome=r.getString("Regiao");regioesRr.put(id,regiao);}ParoquiaRr paroquia=regiao.paroquias.get(idParoquia);if(paroquia==null){paroquia=new ParoquiaRr();paroquia.id=idParoquia;paroquia.nome=r.getString("Paroquia");paroquia.bairro=r.getString("Bairro");paroquia.cidade=r.getString("Cidade");regiao.paroquias.put(idParoquia,paroquia);totalParoquiasRr++;}paroquia.grupos.put(classe,paroquia.grupos.getOrDefault(classe,0)+qtd);paroquia.qtd+=qtd;regiao.grupos.put(classe,regiao.grupos.getOrDefault(classe,0)+qtd);regiao.total+=qtd;totaisGrupoRr.put(classe,totaisGrupoRr.getOrDefault(classe,0)+qtd);totalRr+=qtd;}}}
 }
}catch(Exception erro){erro.printStackTrace();erroRr="Não foi possível carregar o resumo por região.";}
%>
<!DOCTYPE html><html lang="pt-br"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Resumo por Região</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"><link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet"><link rel="stylesheet" href="css/style.css"><style>
.rr-filter{background:#fff;border:1px solid #e8edf3;border-radius:16px;padding:20px}.rr-table th{font-size:11px;text-transform:uppercase;color:#64748b}.rr-region-cell{font-weight:700;vertical-align:middle!important;background:#fffaf5!important;min-width:190px}.rr-subtotal td{font-weight:700;background:#f8fafc}.rr-total td{font-weight:800;background:#ecfdf5;color:#166534}.rr-qty{text-align:center;width:130px}.rr-location{font-size:12px;color:#64748b}.rr-print-title{display:none}.rr-region-summary-card{background:#fff;border:1px solid #e8edf3;border-radius:13px;padding:14px 16px;height:100%}.rr-region-count{color:#a85108;background:#fff1e6;border-radius:9px;padding:5px 10px;font-weight:700;min-width:42px;text-align:center}
@media print{@page{size:A4;margin:12mm}.navbar,footer,.no-print{display:none!important}body{background:#fff!important}.container{max-width:none!important;padding:0!important}.dashboard-card,.profile-card,.rr-region-summary-card{box-shadow:none!important}.rr-table{font-size:9pt}.rr-table th,.rr-table td{padding:5px 7px}.rr-print-title{display:block}}
</style></head><body><jsp:include page="includes/header.jsp"/><main class="container py-4">
<div class="d-flex justify-content-between align-items-start gap-3 flex-wrap mb-4"><div><a href="relatorios.jsp" class="btn btn-link px-0 no-print"><i class="bi bi-arrow-left"></i> Voltar aos relatórios</a><h1 class="fw-bold mb-1">Resumo por Região</h1><p class="text-muted mb-0"><%= hrr(grr(classeRr)) %><%= regiaoRr!=0?" · "+hrr(nomeRegiaoRr):" · Todas as regiões" %></p></div><button class="btn btn-outline-secondary no-print" onclick="window.print()"><i class="bi bi-printer"></i> Imprimir</button></div>
<form method="get" class="rr-filter mb-4 no-print"><div class="row g-3 align-items-end"><div class="col-md-4"><label class="form-label">Grupo</label><select name="classe" class="form-select"><option value="0" <%= classeRr==0?"selected":"" %>>Todos</option><option value="1" <%= classeRr==1?"selected":"" %>>Diáconos</option><option value="2" <%= classeRr==2?"selected":"" %>>Candidatos</option><option value="3" <%= classeRr==3?"selected":"" %>>Vocacionados</option></select></div><div class="col-md-5"><label class="form-label">Região episcopal</label><% if(repRr){ %><input class="form-control" value="<%= hrr(nomeRegiaoRr.isEmpty()?"Região não identificada":nomeRegiaoRr) %>" disabled><% }else{ %><select name="regiao" class="form-select"><option value="0">Todas as regiões</option><% for(Map.Entry<Integer,String> x:regioesFiltroRr.entrySet()){ %><option value="<%= x.getKey() %>" <%= x.getKey()==regiaoRr?"selected":"" %>><%= hrr(x.getValue()) %></option><% } %></select><% } %></div><div class="col-md-3"><button class="btn btn-orange w-100"><i class="bi bi-funnel"></i> Aplicar filtros</button></div></div></form>
<% if(erroRr!=null){ %><div class="alert alert-danger"><%= hrr(erroRr) %></div><% } %>
<div class="row g-3 mb-4"><div class="col-md-3"><div class="dashboard-card"><h5>Membros</h5><div class="card-number"><%= totalRr %></div></div></div><div class="col-md-3"><div class="dashboard-card"><h5>Regiões</h5><div class="card-number"><%= regioesRr.size() %></div></div></div><div class="col-md-3"><div class="dashboard-card"><h5>Paróquias</h5><div class="card-number"><%= totalParoquiasRr %></div></div></div><div class="col-md-3"><div class="dashboard-card"><h5>Grupo</h5><span class="badge-tag <%= classeRr==0?"":classeRr==1?"tag-green":classeRr==2?"tag-yellow":"tag-blue" %>"><%= hrr(grr(classeRr)) %></span></div></div></div>
<% if(!regioesRr.isEmpty()){ %><section class="mb-4"><div class="d-flex justify-content-between align-items-end mb-3"><h4 class="mb-0">Resumo por região</h4><span class="text-muted">Distribuição dos membros encontrados</span></div><div class="row g-3"><% for(RegiaoRr regiao:regioesRr.values()){ %><div class="col-md-4"><div class="rr-region-summary-card d-flex justify-content-between align-items-center gap-3"><div><strong><%= hrr(regiao.nome) %></strong><small class="d-block text-muted"><%= regiao.paroquias.size() %> paróquia(s)</small></div><span class="rr-region-count"><%= regiao.total %></span></div></div><% } %></div></section><% } %>
<h2 class="rr-print-title fs-5 mb-3"><%= hrr(grr(classeRr)) %><%= regiaoRr!=0?" · "+hrr(nomeRegiaoRr):" · Todas as regiões" %></h2>
<section class="profile-card"><div class="d-flex justify-content-between align-items-center mb-3"><h4 class="mb-0">Distribuição por região e paróquia</h4><span class="text-muted"><%= totalRr %> membro(s)</span></div><div class="table-responsive"><table class="table table-bordered table-hover rr-table mb-0"><thead><tr><th>Região</th><th>Paróquia</th><% if(classeRr==0){for(Map.Entry<Integer,String> grupoRr:gruposAtivosRr.entrySet()){ %><th class="rr-qty"><%= hrr(grupoRr.getValue()) %></th><% } %><th class="rr-qty">Total</th><% }else{ %><th class="rr-qty">Quantidade</th><% } %></tr></thead><tbody><% for(RegiaoRr regiao:regioesRr.values()){int linhas=regiao.paroquias.size()+1;boolean primeira=true;for(ParoquiaRr paroquia:regiao.paroquias.values()){ %><tr><% if(primeira){ %><td rowspan="<%= linhas %>" class="rr-region-cell"><i class="bi bi-geo-alt-fill text-warning"></i> <%= hrr(regiao.nome) %></td><% primeira=false;} %><td><strong><%= hrr(paroquia.nome) %></strong><div class="rr-location"><%= hrr(paroquia.bairro) %><%= !paroquia.bairro.isEmpty()&&!paroquia.cidade.isEmpty()?" · ":"" %><%= hrr(paroquia.cidade) %></div></td><% if(classeRr==0){for(Integer grupoIdRr:gruposAtivosRr.keySet()){ %><td class="rr-qty"><%= paroquia.grupos.getOrDefault(grupoIdRr,0) %></td><% } %><td class="rr-qty"><strong><%= paroquia.qtd %></strong></td><% }else{ %><td class="rr-qty"><%= paroquia.qtd %></td><% } %></tr><% } %><tr class="rr-subtotal"><td>Total da região</td><% if(classeRr==0){for(Integer grupoIdRr:gruposAtivosRr.keySet()){ %><td class="rr-qty"><%= regiao.grupos.getOrDefault(grupoIdRr,0) %></td><% } %><td class="rr-qty"><%= regiao.total %></td><% }else{ %><td class="rr-qty"><%= regiao.total %></td><% } %></tr><% } %><% if(regioesRr.isEmpty()){ %><tr><td colspan="<%= classeRr==0?gruposAtivosRr.size()+3:3 %>" class="text-center text-muted py-5">Nenhum registro encontrado para os filtros selecionados.</td></tr><% }else{ %><tr class="rr-total"><td colspan="2">Total geral</td><% if(classeRr==0){for(Integer grupoIdRr:gruposAtivosRr.keySet()){ %><td class="rr-qty"><%= totaisGrupoRr.getOrDefault(grupoIdRr,0) %></td><% } %><td class="rr-qty"><%= totalRr %></td><% }else{ %><td class="rr-qty"><%= totalRr %></td><% } %></tr><% } %></tbody></table></div></section>
</main><jsp:include page="includes/footer.jsp"/></body></html>
