<%@ page import="java.sql.*,java.time.*,java.time.format.*,java.util.*,java.math.BigDecimal" %>
<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ include file="includes/auth.jsp" %><%@ include file="includes/access.jsp" %>
<%!
private String hfin(String v){return v==null?"":v.replace("&","&amp;").replace("<","&lt;").replace(">","&gt;").replace("\"","&quot;").replace("'","&#39;");}
private int ifin(String v,int d){try{return Integer.parseInt(v);}catch(Exception e){return d;}}
private String mfin(BigDecimal v){return java.text.NumberFormat.getCurrencyInstance(java.util.Locale.forLanguageTag("pt-BR")).format(v==null?BigDecimal.ZERO:v);}
%>
<%
String perfilFin=(String)session.getAttribute("usuarioPerfil");Integer grupoSessaoFin=(Integer)session.getAttribute("usuarioGrupoId");boolean admFin="ADM".equals(perfilFin);
int mesFin=ifin(request.getParameter("mes"),LocalDate.now().getMonthValue()),anoFin=ifin(request.getParameter("ano"),LocalDate.now().getYear());if(mesFin<1||mesFin>12)mesFin=LocalDate.now().getMonthValue();if(anoFin<2000||anoFin>9999)anoFin=LocalDate.now().getYear();
int grupoFin=admFin?ifin(request.getParameter("grupo"),-1):(grupoSessaoFin==null?-2:grupoSessaoFin);LocalDate inicioFin=LocalDate.of(anoFin,mesFin,1),fimFin=inicioFin.plusMonths(1);String erroFin=null,nomeGrupoFin=grupoFin<0?"Consolidado — todos os grupos":"";
class LinhaFin{String data,grupo,conta,descricao,tipo,origem;BigDecimal valor;}
List<LinhaFin> linhasFin=new ArrayList<LinhaFin>();LinkedHashMap<Integer,String> gruposFin=new LinkedHashMap<Integer,String>();BigDecimal saldoInicialFin=BigDecimal.ZERO,entradasFin=BigDecimal.ZERO,saidasFin=BigDecimal.ZERO;
try(Connection c=cad.db.Database.getConnection()){
 try(PreparedStatement p=c.prepareStatement("SELECT IdGrupo,NomePlural FROM grupos WHERE StatusGrupo='ATIVO' AND GrupoOperacional=1 ORDER BY Ordem,NomePlural");ResultSet r=p.executeQuery()){while(r.next()){gruposFin.put(r.getInt(1),r.getString(2));if(r.getInt(1)==grupoFin)nomeGrupoFin=r.getString(2);}}
 String filtroGrupo=grupoFin>=0?" AND l.IdGrupo=?":"";
 String sqlSaldo="SELECT COALESCE(SUM(CASE WHEN Tipo='ENTRADA' THEN Valor ELSE -Valor END),0) FROM financeiro_lancamentos l WHERE l.Situacao='REALIZADO' AND l.Competencia<?"+filtroGrupo;
 try(PreparedStatement p=c.prepareStatement(sqlSaldo)){p.setDate(1,java.sql.Date.valueOf(inicioFin));if(grupoFin>=0)p.setInt(2,grupoFin);try(ResultSet r=p.executeQuery()){if(r.next())saldoInicialFin=r.getBigDecimal(1);}}
 String sql="SELECT DATE_FORMAT(COALESCE(l.DtRealizada,l.Competencia),'%d/%m/%Y'),g.NomePlural,CONCAT(pc.Codigo,' — ',pc.Nome),l.Descricao,l.Tipo,l.Valor,l.Origem FROM financeiro_lancamentos l JOIN grupos g ON g.IdGrupo=l.IdGrupo JOIN financeiro_contas pc ON pc.IdConta=l.IdConta WHERE l.Situacao='REALIZADO' AND l.Competencia>=? AND l.Competencia<?"+filtroGrupo+" ORDER BY COALESCE(l.DtRealizada,l.Competencia),l.IdLancamento";
 try(PreparedStatement p=c.prepareStatement(sql)){p.setDate(1,java.sql.Date.valueOf(inicioFin));p.setDate(2,java.sql.Date.valueOf(fimFin));if(grupoFin>=0)p.setInt(3,grupoFin);try(ResultSet r=p.executeQuery()){while(r.next()){LinhaFin x=new LinhaFin();x.data=r.getString(1);x.grupo=r.getString(2);x.conta=r.getString(3);x.descricao=r.getString(4);x.tipo=r.getString(5);x.valor=r.getBigDecimal(6);x.origem=r.getString(7);linhasFin.add(x);if("ENTRADA".equals(x.tipo))entradasFin=entradasFin.add(x.valor);else saidasFin=saidasFin.add(x.valor);}}}
}catch(Exception e){e.printStackTrace();erroFin="Não foi possível gerar o relatório. Acesse primeiro o módulo Financeiro para inicializar sua estrutura.";}
BigDecimal saldoFinalFin=saldoInicialFin.add(entradasFin).subtract(saidasFin);String competenciaFin=inicioFin.format(DateTimeFormatter.ofPattern("MMMM 'de' yyyy",new Locale("pt","BR")));
%>
<!doctype html><html lang="pt-br"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Relatório financeiro</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"><link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet"><link rel="stylesheet" href="css/style.css"><style>.rf-filter{background:#fff;border:1px solid #e5eaf0;border-radius:16px;padding:20px}.rf-table th{font-size:11px;text-transform:uppercase;color:#64748b}.rf-balance td{font-weight:700;background:#f8fafc}.rf-final td{font-weight:800;background:#ecfdf5;color:#166534}.rf-value{white-space:nowrap;text-align:right}.rf-title-print{display:none}@media print{@page{size:landscape;margin:10mm}.navbar,footer,.no-print{display:none!important}.container{max-width:none!important;padding:0!important}.profile-card{box-shadow:none!important;border:0!important}.rf-title-print{display:block}.rf-table{font-size:9pt}.rf-table td,.rf-table th{padding:5px}}</style></head><body><jsp:include page="includes/header.jsp"/><main class="container py-4">
<div class="d-flex justify-content-between align-items-start flex-wrap gap-3 mb-4"><div><a href="financeiro.jsp" class="btn btn-link px-0 no-print"><i class="bi bi-arrow-left"></i> Voltar ao financeiro</a><h1 class="fw-bold mb-1">Relatório financeiro</h1><p class="text-muted mb-0"><%= hfin(competenciaFin) %> · <%= hfin(nomeGrupoFin) %></p></div><button class="btn btn-outline-secondary no-print" onclick="window.print()"><i class="bi bi-printer"></i> Imprimir</button></div>
<form class="rf-filter mb-4 no-print" method="get"><div class="row g-3 align-items-end"><div class="col-md-3"><label class="form-label">Mês</label><select name="mes" class="form-select"><%String[] meses={"Janeiro","Fevereiro","Março","Abril","Maio","Junho","Julho","Agosto","Setembro","Outubro","Novembro","Dezembro"};for(int i=1;i<=12;i++){%><option value="<%=i%>" <%=i==mesFin?"selected":""%>><%=meses[i-1]%></option><%}%></select></div><div class="col-md-3"><label class="form-label">Ano</label><input name="ano" type="number" min="2000" max="9999" value="<%=anoFin%>" class="form-control"></div><%if(admFin){%><div class="col-md-4"><label class="form-label">Grupo</label><select name="grupo" class="form-select"><option value="-1">Consolidado — todos os grupos</option><%for(Map.Entry<Integer,String> g:gruposFin.entrySet()){%><option value="<%=g.getKey()%>" <%=g.getKey()==grupoFin?"selected":""%>><%=hfin(g.getValue())%></option><%}%></select></div><%}%><div class="col-md-2"><button class="btn btn-orange w-100">Gerar</button></div></div></form>
<div class="rf-title-print mb-3"><h3>Relatório financeiro — <%=hfin(competenciaFin)%></h3><div><%=hfin(nomeGrupoFin)%></div></div><%if(erroFin!=null){%><div class="alert alert-danger"><%=hfin(erroFin)%></div><%}%>
<div class="row g-3 mb-4"><div class="col-md-4"><div class="dashboard-card"><h5>Entradas do mês</h5><div class="card-number text-success"><%=mfin(entradasFin)%></div></div></div><div class="col-md-4"><div class="dashboard-card"><h5>Saídas do mês</h5><div class="card-number text-danger"><%=mfin(saidasFin)%></div></div></div><div class="col-md-4"><div class="dashboard-card"><h5>Resultado do mês</h5><div class="card-number"><%=mfin(entradasFin.subtract(saidasFin))%></div></div></div></div>
<section class="profile-card"><div class="table-responsive"><table class="table rf-table align-middle"><thead><tr><th>Data</th><th>Grupo</th><th>Conta</th><th>Descrição</th><th>Tipo</th><th class="text-end">Entrada</th><th class="text-end">Saída</th><th class="text-end">Saldo</th></tr></thead><tbody><%BigDecimal saldoCorrente=saldoInicialFin;%><tr class="rf-balance"><td colspan="7">Saldo inicial — saldo final do mês anterior</td><td class="rf-value"><%=mfin(saldoCorrente)%></td></tr><%for(LinhaFin x:linhasFin){saldoCorrente="ENTRADA".equals(x.tipo)?saldoCorrente.add(x.valor):saldoCorrente.subtract(x.valor);%><tr><td><%=hfin(x.data)%></td><td><%=hfin(x.grupo)%></td><td><%=hfin(x.conta)%></td><td><%=hfin(x.descricao)%><%if("CONTRIBUICOES".equals(x.origem)){%><div class="small text-muted">Consolidado das contribuições</div><%}%></td><td><%="ENTRADA".equals(x.tipo)?"Entrada":"Saída"%></td><td class="rf-value text-success"><%="ENTRADA".equals(x.tipo)?mfin(x.valor):"—"%></td><td class="rf-value text-danger"><%="SAIDA".equals(x.tipo)?mfin(x.valor):"—"%></td><td class="rf-value"><%=mfin(saldoCorrente)%></td></tr><%}%><tr class="rf-final"><td colspan="7">Saldo final de <%=hfin(competenciaFin)%></td><td class="rf-value"><%=mfin(saldoFinalFin)%></td></tr></tbody></table></div></section></main><jsp:include page="includes/footer.jsp"/></body></html>
