<%@ page import="java.sql.*,java.util.*" %>
<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ include file="includes/auth.jsp" %>
<%@ include file="includes/escopoRelatorios.jspf" %>
<%!
private String hdoc(String valor){return valor==null?"":valor.replace("&","&amp;").replace("<","&lt;").replace(">","&gt;").replace("\"","&quot;").replace("'","&#39;");}
private int ndoc(String valor){try{return Integer.parseInt(valor);}catch(Exception erro){return 0;}}
private String gdoc(int classe){return cad.grupos.GrupoCatalogo.plural(classe);}
%>
<%
String perfilRelDoc=(String)session.getAttribute("usuarioPerfil");if(!"ADM".equals(perfilRelDoc)&&!"REP".equals(perfilRelDoc)&&!"EXT".equals(perfilRelDoc)){response.sendRedirect("index.jsp");return;}
Integer regiaoSessaoRelDoc=(Integer)session.getAttribute("usuarioRegiaoId"),grupoSessaoRelDoc=(Integer)session.getAttribute("usuarioGrupoId");String escopoRelDoc=cadEscopoRelatorios(session);int regiaoRestritaRelDoc="REP".equals(perfilRelDoc)&&"REGIAO_TODOS".equals(escopoRelDoc)?(regiaoSessaoRelDoc==null?-1:regiaoSessaoRelDoc.intValue()):0;int grupoRestritoRelDoc="REP".equals(perfilRelDoc)&&"PROPRIO".equals(escopoRelDoc)?(grupoSessaoRelDoc==null?-1:grupoSessaoRelDoc.intValue()):"REP".equals(perfilRelDoc)&&"NENHUM".equals(escopoRelDoc)?-1:0;
int checklistRelDoc=ndoc(request.getParameter("checklist"));String nomeRelDoc=request.getParameter("nome");if(nomeRelDoc==null)nomeRelDoc="";nomeRelDoc=nomeRelDoc.trim();String regiaoRelDoc=request.getParameter("regiao");if(regiaoRelDoc==null)regiaoRelDoc="";String turmaRelDoc=request.getParameter("turma");if(turmaRelDoc==null)turmaRelDoc="";String situacaoRelDoc=request.getParameter("situacao");if(situacaoRelDoc==null)situacaoRelDoc="";
class ChecklistRelDoc{int id,classe;String nome,status;}
class ItemRelDoc{int id;String descricao;}
class PessoaRelDoc{int id;String nome,regiao,paroquia,bairro,turma;Map<Integer,Boolean> entregas=new HashMap<Integer,Boolean>();int entregues=0;}
List<ChecklistRelDoc> checklistsRelDoc=new ArrayList<ChecklistRelDoc>();List<ItemRelDoc> itensRelDoc=new ArrayList<ItemRelDoc>();List<PessoaRelDoc> pessoasRelDoc=new ArrayList<PessoaRelDoc>();List<String> regioesRelDoc=new ArrayList<String>();List<String> turmasRelDoc=new ArrayList<String>();String erroRelDoc=null;ChecklistRelDoc selecionadoRelDoc=null;
try{
 try(Connection c=cad.db.Database.getConnection()){
  try(PreparedStatement p=c.prepareStatement("SELECT IdChecklist,Nome,Classe,StatusChecklist FROM documentacao_checklist WHERE (?=0 OR Classe=?) ORDER BY StatusChecklist='ATIVO' DESC,Classe,Nome")){p.setInt(1,grupoRestritoRelDoc);p.setInt(2,grupoRestritoRelDoc);try(ResultSet r=p.executeQuery()){while(r.next()){ChecklistRelDoc x=new ChecklistRelDoc();x.id=r.getInt(1);x.nome=r.getString(2);x.classe=r.getInt(3);x.status=r.getString(4);checklistsRelDoc.add(x);if(checklistRelDoc==x.id)selecionadoRelDoc=x;}}}
  if(checklistRelDoc==0&&!checklistsRelDoc.isEmpty()){selecionadoRelDoc=checklistsRelDoc.get(0);checklistRelDoc=selecionadoRelDoc.id;}
  if(selecionadoRelDoc!=null){
   try(PreparedStatement p=c.prepareStatement("SELECT DISTINCT IFNULL(pa.Regiao,'') Regiao FROM pessoas p LEFT JOIN paroquia pa ON pa.IdParoquia=p.IdParoquia WHERE p.Classe=? AND p.status=1 AND IFNULL(pa.Regiao,'')<>'' AND (?=0 OR IFNULL(pa.IdRegiao,0)=?) ORDER BY Regiao")){p.setInt(1,selecionadoRelDoc.classe);p.setInt(2,regiaoRestritaRelDoc);p.setInt(3,regiaoRestritaRelDoc);try(ResultSet r=p.executeQuery()){while(r.next())regioesRelDoc.add(r.getString(1));}}
   try(PreparedStatement p=c.prepareStatement("SELECT DISTINCT IFNULL(p.Turma,'') Turma FROM pessoas p LEFT JOIN paroquia pa ON pa.IdParoquia=p.IdParoquia WHERE p.Classe=? AND p.status=1 AND IFNULL(p.Turma,'')<>'' AND (?=0 OR IFNULL(pa.IdRegiao,0)=?) ORDER BY p.Turma")){p.setInt(1,selecionadoRelDoc.classe);p.setInt(2,regiaoRestritaRelDoc);p.setInt(3,regiaoRestritaRelDoc);try(ResultSet r=p.executeQuery()){while(r.next())turmasRelDoc.add(r.getString(1));}}
   try(PreparedStatement p=c.prepareStatement("SELECT IdItem,Descricao FROM documentacao_checklist_item WHERE IdChecklist=? AND StatusItem='ATIVO' ORDER BY Ordem,Descricao")){p.setInt(1,checklistRelDoc);try(ResultSet r=p.executeQuery()){while(r.next()){ItemRelDoc x=new ItemRelDoc();x.id=r.getInt(1);x.descricao=r.getString(2);itensRelDoc.add(x);}}}
   String sql="SELECT p.IdPessoa,p.Nome,IFNULL(pa.Regiao,'') Regiao,IFNULL(pa.Descricao,'') Paroquia,IFNULL(pa.Bairro,'') Bairro,IFNULL(p.Turma,'') Turma,i.IdItem,IFNULL(pi.StatusEntrega,'PENDENTE') StatusEntrega FROM pessoas p LEFT JOIN paroquia pa ON pa.IdParoquia=p.IdParoquia JOIN documentacao_checklist_item i ON i.IdChecklist=? AND i.StatusItem='ATIVO' LEFT JOIN documentacao_pessoa_item pi ON pi.IdPessoa=p.IdPessoa AND pi.IdItem=i.IdItem WHERE p.Classe=? AND p.status=1 AND (?='' OR p.Nome LIKE CONCAT('%',?,'%')) AND (?='' OR IFNULL(pa.Regiao,'')=?) AND (?='' OR IFNULL(p.Turma,'')=?) AND (?=0 OR IFNULL(pa.IdRegiao,0)=?) ORDER BY pa.Regiao,pa.Descricao,p.Nome,i.Ordem,i.Descricao";
   LinkedHashMap<Integer,PessoaRelDoc> mapa=new LinkedHashMap<Integer,PessoaRelDoc>();
   try(PreparedStatement p=c.prepareStatement(sql)){p.setInt(1,checklistRelDoc);p.setInt(2,selecionadoRelDoc.classe);p.setString(3,nomeRelDoc);p.setString(4,nomeRelDoc);p.setString(5,regiaoRelDoc);p.setString(6,regiaoRelDoc);p.setString(7,turmaRelDoc);p.setString(8,turmaRelDoc);p.setInt(9,regiaoRestritaRelDoc);p.setInt(10,regiaoRestritaRelDoc);try(ResultSet r=p.executeQuery()){while(r.next()){int id=r.getInt("IdPessoa");PessoaRelDoc pessoa=mapa.get(id);if(pessoa==null){pessoa=new PessoaRelDoc();pessoa.id=id;pessoa.nome=r.getString("Nome");pessoa.regiao=r.getString("Regiao");pessoa.paroquia=r.getString("Paroquia");pessoa.bairro=r.getString("Bairro");pessoa.turma=r.getString("Turma");mapa.put(id,pessoa);}boolean entregue="CONCLUIDO".equals(r.getString("StatusEntrega"));pessoa.entregas.put(r.getInt("IdItem"),entregue);if(entregue)pessoa.entregues++;}}}
   for(PessoaRelDoc pessoa:mapa.values()){boolean completo=!itensRelDoc.isEmpty()&&pessoa.entregues==itensRelDoc.size();if(("PENDENTE".equals(situacaoRelDoc)&&completo)||("CONCLUIDO".equals(situacaoRelDoc)&&!completo))continue;pessoasRelDoc.add(pessoa);}
  }
 }
}catch(Exception erro){erro.printStackTrace();erroRelDoc="Não foi possível carregar o relatório. Verifique se as tabelas de documentação foram criadas.";}
%>
<!DOCTYPE html><html lang="pt-br"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Relatório de Documentações</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"><link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet"><link rel="stylesheet" href="css/style.css"><style>.matrix-photo{width:40px;height:40px;border-radius:50%;object-fit:cover;background:#edf2f7}.matrix-table th{font-size:.75rem;vertical-align:bottom}.matrix-table td{vertical-align:middle}.matrix-item{min-width:135px;max-width:190px}.matrix-status{white-space:nowrap;font-weight:600;font-size:.78rem}.matrix-ok{color:#15803d}.matrix-pending{color:#b45309}.matrix-member{min-width:220px;position:sticky;left:0;background:#fff!important;z-index:1}@media print{@page{size:landscape;margin:7mm}.navbar,footer,.no-print{display:none!important}body{background:#fff!important}.container{max-width:none!important;padding:0!important}.profile-card{border:0!important;box-shadow:none!important;padding:0!important}.matrix-table{font-size:7.5pt}.matrix-table th,.matrix-table td{padding:4px!important}.matrix-photo{display:none}.matrix-member{min-width:130px;position:static}.matrix-item{min-width:75px;max-width:110px}.matrix-status{font-size:7pt}.matrix-ok,.matrix-pending{color:#000!important}}</style></head><body><jsp:include page="includes/header.jsp"/>
<main class="container py-4"><div class="d-flex justify-content-between align-items-start gap-3 mb-4"><div><a href="relatorios.jsp" class="btn btn-link px-0 no-print"><i class="bi bi-arrow-left"></i> Voltar aos relatórios</a><h1 class="fw-bold mb-1">Checklist de documentações</h1><p class="text-muted mb-0"><%= selecionadoRelDoc==null?"Selecione um checklist":hdoc(selecionadoRelDoc.nome)+" · "+hdoc(gdoc(selecionadoRelDoc.classe)) %></p></div><button class="btn btn-outline-secondary no-print" onclick="window.print()"><i class="bi bi-printer"></i> Imprimir</button></div>
<form method="get" class="profile-card mb-4 no-print"><div class="row g-3 align-items-end"><div class="col-md-3"><label class="form-label">Checklist</label><select name="checklist" class="form-select"><% for(ChecklistRelDoc x:checklistsRelDoc){ %><option value="<%= x.id %>" <%= x.id==checklistRelDoc?"selected":"" %>><%= hdoc(x.nome) %> — <%= hdoc(gdoc(x.classe)) %><%= "INATIVO".equals(x.status)?" (inativo)":"" %></option><% } %></select></div><div class="col-md-3"><label class="form-label">Nome do membro</label><input name="nome" value="<%= hdoc(nomeRelDoc) %>" class="form-control" placeholder="Pesquisar por nome"></div><div class="col-md-2"><label class="form-label">Região</label><select name="regiao" class="form-select"><option value="">Todas</option><% for(String x:regioesRelDoc){ %><option value="<%= hdoc(x) %>" <%= x.equals(regiaoRelDoc)?"selected":"" %>><%= hdoc(x) %></option><% } %></select></div><div class="col-md-2"><label class="form-label">Turma</label><select name="turma" class="form-select"><option value="">Todas</option><% for(String x:turmasRelDoc){ %><option value="<%= hdoc(x) %>" <%= x.equals(turmaRelDoc)?"selected":"" %>><%= hdoc(x) %></option><% } %></select></div><div class="col-md-2"><label class="form-label">Situação geral</label><select name="situacao" class="form-select"><option value="">Todos</option><option value="PENDENTE" <%= "PENDENTE".equals(situacaoRelDoc)?"selected":"" %>>Com pendências</option><option value="CONCLUIDO" <%= "CONCLUIDO".equals(situacaoRelDoc)?"selected":"" %>>Tudo entregue</option></select></div><div class="col-12 d-flex justify-content-end gap-2"><a href="relatorioDocumentacoes.jsp" class="btn btn-light">Limpar</a><button class="btn btn-orange"><i class="bi bi-funnel"></i> Aplicar filtros</button></div></div></form>
<% if(erroRelDoc!=null){ %><div class="alert alert-danger"><%= hdoc(erroRelDoc) %></div><% } %>
<div class="d-flex justify-content-between align-items-center mb-3"><strong><%= pessoasRelDoc.size() %> membro(s)</strong><span class="text-muted"><%= itensRelDoc.size() %> item(ns) no checklist</span></div>
<section class="profile-card"><div class="table-responsive"><table class="table table-bordered table-hover matrix-table mb-0"><thead><tr><th>Região</th><th>Paróquia - Bairro</th><th class="matrix-member">Nome</th><th>Turma</th><% for(ItemRelDoc item:itensRelDoc){ %><th class="matrix-item"><%= hdoc(item.descricao) %></th><% } %><th>Resumo</th></tr></thead><tbody><% for(PessoaRelDoc pessoa:pessoasRelDoc){String paroquiaBairro=(pessoa.paroquia==null?"":pessoa.paroquia)+(pessoa.bairro==null||pessoa.bairro.isEmpty()?"":" - "+pessoa.bairro); %><tr><td><%= hdoc(pessoa.regiao==null||pessoa.regiao.isEmpty()?"—":pessoa.regiao) %></td><td><%= hdoc(paroquiaBairro.isEmpty()?"—":paroquiaBairro) %></td><td class="matrix-member"><div class="d-flex align-items-center gap-2"><img src="fotos/foto_<%= pessoa.id %>.jpg" class="matrix-photo" alt="" onerror="this.style.display='none'"><strong><%= hdoc(pessoa.nome) %></strong></div></td><td><%= hdoc(pessoa.turma==null||pessoa.turma.isEmpty()?"—":pessoa.turma) %></td><% for(ItemRelDoc item:itensRelDoc){boolean entregue=Boolean.TRUE.equals(pessoa.entregas.get(item.id)); %><td><span class="matrix-status <%= entregue?"matrix-ok":"matrix-pending" %>"><i class="bi <%= entregue?"bi-check-circle-fill":"bi-clock-fill" %>"></i> <%= entregue?"Entregue":"Pendente" %></span></td><% } %><td><strong><%= pessoa.entregues %>/<%= itensRelDoc.size() %></strong></td></tr><% } %><% if(pessoasRelDoc.isEmpty()){ %><tr><td colspan="<%= itensRelDoc.size()+5 %>" class="text-center text-muted py-5">Nenhum membro encontrado para os filtros selecionados.</td></tr><% } %></tbody></table></div></section></main><jsp:include page="includes/footer.jsp"/></body></html>
