<%@ page import="java.sql.*,java.io.*,java.nio.file.*,java.text.Normalizer,java.util.*,java.net.URLDecoder" %>
<%@ page contentType="application/json; charset=UTF-8" pageEncoding="UTF-8" %>
<%!
private String jud(String s){return s==null?"":s.replace("\\","\\\\").replace("\"","\\\"").replace("\r","\\r").replace("\n","\\n");}
private String sud(String s){String n=Normalizer.normalize(s==null?"":s,Normalizer.Form.NFD).replaceAll("\\p{M}","").toUpperCase(Locale.ROOT).replaceAll("[^A-Z0-9]+","_").replaceAll("^_+|_+$","");return n.isEmpty()?"ARQUIVO":n;}
private String[] tud(byte[] b){if(b.length>=4&&b[0]=='%'&&b[1]=='P'&&b[2]=='D'&&b[3]=='F')return new String[]{"PDF","application/pdf"};if(b.length>=3&&(b[0]&255)==255&&(b[1]&255)==216&&(b[2]&255)==255)return new String[]{"JPG","image/jpeg"};if(b.length>=8&&(b[0]&255)==137&&b[1]=='P'&&b[2]=='N'&&b[3]=='G')return new String[]{"PNG","image/png"};if(b.length>=6&&b[0]=='G'&&b[1]=='I'&&b[2]=='F')return new String[]{"GIF","image/gif"};if(b.length>=12&&b[0]=='R'&&b[1]=='I'&&b[2]=='F'&&b[3]=='F'&&b[8]=='W'&&b[9]=='E'&&b[10]=='B'&&b[11]=='P')return new String[]{"WEBP","image/webp"};return null;}
%>
<%
Integer usuario=(Integer)session.getAttribute("usuarioId");String perfilUpload=(String)session.getAttribute("usuarioPerfil");if(usuario==null){response.setStatus(401);out.print("{\"ok\":false,\"mensagem\":\"Sessão inválida.\"}");return;}int pessoaUpload=usuario;try{String pv=request.getParameter("pessoa");if(pv!=null&&!pv.isEmpty())pessoaUpload=Integer.parseInt(pv);}catch(Exception e){response.setStatus(400);out.print("{\"ok\":false,\"mensagem\":\"Membro inválido.\"}");return;}if(pessoaUpload!=usuario.intValue()&&!"ADM".equals(perfilUpload)){response.setStatus(403);out.print("{\"ok\":false,\"mensagem\":\"Acesso não autorizado.\"}");return;}
int item=0;try{item=Integer.parseInt(request.getParameter("item"));}catch(Exception e){}
final int maximo=3*1024*1024;int tamanho=request.getContentLength();
if(item==0||tamanho<=0||tamanho>maximo){response.setStatus(400);out.print("{\"ok\":false,\"mensagem\":\"O arquivo deve ter no máximo 3 MB.\"}");return;}
try{
 ByteArrayOutputStream dados=new ByteArrayOutputStream(tamanho);byte[] buffer=new byte[8192];int l,total=0;try(InputStream in=request.getInputStream()){while((l=in.read(buffer))!=-1){total+=l;if(total>maximo)throw new IllegalArgumentException("O arquivo deve ter no máximo 3 MB.");dados.write(buffer,0,l);}}
 byte[] bytes=dados.toByteArray();String[] tipo=tud(bytes);if(tipo==null)throw new IllegalArgumentException("Envie um PDF ou uma imagem JPG, PNG ou GIF.");
 String original=request.getHeader("X-File-Name");if(original!=null)original=URLDecoder.decode(original,"UTF-8");else original="arquivo."+tipo[0].toLowerCase(Locale.ROOT);
 try(Connection c=cad.db.Database.getConnection();PreparedStatement p=c.prepareStatement("SELECT g.Sigla,i.PrefixoArquivo,p.Nome FROM pessoas p JOIN grupos g ON g.IdGrupo=p.Classe JOIN documentacao_checklist ch ON ch.Classe=p.Classe AND ch.StatusChecklist='ATIVO' JOIN documentacao_checklist_item i ON i.IdChecklist=ch.IdChecklist AND i.IdItem=? AND i.StatusItem='ATIVO' AND i.ExibirMembro=1 AND i.PermiteUpload=1 WHERE p.IdPessoa=? AND p.Status=1")){
  p.setInt(1,item);p.setInt(2,pessoaUpload);String sigla,prefixo,nomePessoa;try(ResultSet r=p.executeQuery()){if(!r.next())throw new IllegalArgumentException("Este item não está disponível para upload.");sigla=r.getString(1);prefixo=r.getString(2);nomePessoa=r.getString(3);}
  if(sigla==null||sigla.trim().isEmpty())throw new IllegalArgumentException("O grupo não possui sigla cadastrada.");String[] nomes=sud(nomePessoa).split("_");String dois=nomes[0]+(nomes.length>1?"_"+nomes[1]:"");String nome=sud(sigla)+"_"+sud(prefixo)+"_"+pessoaUpload+"_"+dois+"."+tipo[0];
  File pasta=new File(application.getRealPath("/WEB-INF"),"documentos_membros");if(!pasta.exists()&&!pasta.mkdirs())throw new IOException("Não foi possível criar a pasta de documentos.");Path temporario=Files.createTempFile(pasta.toPath(),"UPLOAD_",".TMP"),destino=new File(pasta,nome).toPath();Files.write(temporario,bytes);try{Files.move(temporario,destino,StandardCopyOption.REPLACE_EXISTING,StandardCopyOption.ATOMIC_MOVE);}catch(AtomicMoveNotSupportedException e){Files.move(temporario,destino,StandardCopyOption.REPLACE_EXISTING);}
  try(PreparedStatement grava=c.prepareStatement("INSERT INTO documentacao_pessoa_arquivo(IdPessoa,IdItem,NomeArquivo,NomeOriginal,TipoMime,TamanhoBytes,IdUsuarioUpload) VALUES(?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE NomeArquivo=VALUES(NomeArquivo),NomeOriginal=VALUES(NomeOriginal),TipoMime=VALUES(TipoMime),TamanhoBytes=VALUES(TamanhoBytes),DtUpload=NOW(),IdUsuarioUpload=VALUES(IdUsuarioUpload)")){grava.setInt(1,pessoaUpload);grava.setInt(2,item);grava.setString(3,nome);grava.setString(4,original);grava.setString(5,tipo[1]);grava.setInt(6,bytes.length);grava.setInt(7,usuario);grava.executeUpdate();}
  try(PreparedStatement entrega=c.prepareStatement("INSERT INTO documentacao_pessoa_item(IdPessoa,IdItem,StatusEntrega,DtConclusao,IdUsuarioAtualizacao) VALUES(?,?,'CONCLUIDO',CURDATE(),?) ON DUPLICATE KEY UPDATE StatusEntrega='CONCLUIDO',DtConclusao=CURDATE(),IdUsuarioAtualizacao=VALUES(IdUsuarioAtualizacao),DtAtualizacao=NOW()")){entrega.setInt(1,pessoaUpload);entrega.setInt(2,item);entrega.setInt(3,usuario);entrega.executeUpdate();}
  out.print("{\"ok\":true,\"arquivo\":\""+jud(nome)+"\"}");
 }
}catch(IllegalArgumentException e){response.setStatus(400);out.print("{\"ok\":false,\"mensagem\":\""+jud(e.getMessage())+"\"}");}catch(Exception e){e.printStackTrace();response.setStatus(500);out.print("{\"ok\":false,\"mensagem\":\"Não foi possível salvar o arquivo.\"}");}
%>
